### ISSUE TITLE
Документация на параметрические тесты

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#167]
Документация на параметрические тесты
Например, на этой странице [Создание файлов тестов](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2)

**Comment by ODemidenko** [comment]
Документации так и не появилось, а жаль. Проект, кажется, развивается активно. Но для его понимания хотелось бы не исходники читать (хотя это, безусловно, полезно), а быстро ознакомиться хотя бы с идеей функционала, чтобы понимать для чего это замыслили и использовать по назначению.

**Comment by artbear** [comment]
Какого вида документации не хватает? Вики проекта смотрел?
21 Мар 2015 г. 14:08 пользователь "ODemidenko" <notifications@github.com>
написал:

**Comment by ODemidenko** [comment]
@artbear в вики ничего не нашел, но посмотрев самотесты проекта - разобрался, спасибо!

**Comment by ODemidenko** [comment]
@artbear Сегодня начал пользоваться параметризованными тестами на практике (до этого только изучал) и выяснил, что в тестовую процедуру может передавать только один параметр, просто он может быть структурой. Ранее это было не очевидно.

**Comment by artbear** [comment]
Параметр может быть каким угодно, главное, чтобы тест умел его обрабатывать.
Специально не делал никаких ограничений на этот счет.
Структура - это просто пример удобный работы с набором различных параметров.
Например, у меня есть тесты со строками, числами и т.п.

**Comment by artbear** [comment]
Есть куча тестов, где параметр - это метаданное (документ) или имя формы или ссылка на объект

**Comment by artbear** [comment]
Документация давно есть.
