### ISSUE TITLE
Добавить список ранее открытых файлов-тестов и каталогов тестов на форму

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#234]
Добавить список ранее открытых файлов-тестов и каталогов тестов на форму
По умолчанию должно сохраняться 10 позиций в списке
Списки должны быть едиными для различных видов запуска (толстый/тонкий клиент и т.п.) - возможно, что нужно хранить в хранилище общих настроек базы.

**Comment by artbear** [comment]
@pbazeliuk >Мне такой вид нравится, технологично и удобно.

Вопрос - как подобное реализовать? вызовом отдельной формы? или все-таки можно сделать подобное подменю?

**Comment by ValeraS** [comment]
В управляемой форме при загрузке тестов из файла разрешен множественный выбор файлов, а в обычной - запрещен. Какой из вариантов правильный?

**Comment by artbear** [comment]
В обычной форме пока не Реализован механизм работы с несколькими файлами
или каталогами, как в УФ.
Если это реализовать, то и множественный выбор можно добавить

**Comment by ValeraS** [comment]
Тогда, какое поведение ожидается, если сразу выбрали 15 файлов? 10 случайных попали в историю, а 5 нет? или при выборе сразу нескольких файлов это будет одна строчка в истории?

**Comment by artbear** [comment]
Имхо это редкий случай. Пусть будет 10 первых путей, возможно, случайных

**Comment by artbear** [comment]
И конечно, это 10 разных строк в истории

**Comment by ValeraS** [comment]
Для каталогов и файлов разные истории или одна общая?

**Comment by artbear** [comment]
@pbazeliuk [выше](https://github.com/xDrivenDevelopment/xUnitFor1C/issues/234#issuecomment-55869659) предлагал разную.
Я также думаю о разных историях.

**Comment by artbear** [comment]
для УФ сделано.

**Comment by artbear** [comment]
Выполнено в 2.7.1.3
