### ISSUE TITLE
Вывод xml-файлов в формате Allure

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#247]
Вывод xml-файлов в формате Allure
[Затравочная статья про Allure от Яндекса](http://habrahabr.ru/company/yandex/blog/232697/)
[Куча исходников проекта Allure для разных языков](https://github.com/allure-framework/allure-core)

**Comment by pbazeliuk** [comment]
Хотелось бы это реализовать. @pumbaEO что изменилось за 2 года и остались ли противоречия?

**Comment by pumbaEO** [comment]
Главное отказаться от идеи глобальной транзакции при выполнении тестов на клиенте и противоречий не будет.

**Comment by artbear** [comment]
>Главное отказаться от идеи глобальной транзакции при выполнении тестов на клиенте и противоречий не будет.

@pumbaEO расшифруй. что за `глобальная транзакция при выполнении тестов на клиенте` ?
на клиенте вообще транзакций нету.

**Comment by artbear** [comment]
Давно выполнено.
