### ISSUE TITLE
Статусы тестов в формате тестовых фреймворков (JUnit, NUnit и т.п.)

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#248]
Статусы тестов в формате тестовых фреймворков (JUnit, NUnit и т.п.)
* Failed - отдельные статусы для падения после проверки (по assert)
* Broken - для падения из-за возникшего исключения
* Pending показывает исключенные из запуска тесты (аннотация @Ignore в JUnit)
* Canceled — тесты, пропущенные в рантайме из-за падения предусловия (assume failure)
* Passed - "зеленые" тесты (уже есть)

Статусы удобны для анализа результатов тестирования.

**Comment by artbear** [comment]
@ValeraS
>Сейчас все ошибки выглядят одинакова, была ли это ошибка проверки или это какая-то не запланированная ошибка. Предлагается ввести две категории ошибок:
errors - не запланированные ошибки
failures - ошибки, возникшие при выполнении проверочных методов.

>При формировании отчета в mxl для ошибок failures не выводить служебную информацию (имя модуля, строка модуля и т.д.), так как, в данном случае, эта информация не информативна.

**Comment by ValeraS** [comment]
Предлагаю для реализации функциональности статуса Pending(skip), добавить метод

ЮТест.ПропуститьТест(ПричинаПропуска);

Вызывать его из метода теста.

Для пропущенных тестов, в дереве тестов устанавливать состояние мЗначенияСостоянияТестов.НеРеализован?
Но при этом выводить отчет по ошибкам, с указанием пропущенных тестов.

Про статус Canceled, кажется он излишен. Например, в JUnit, в раннере по умолчанию, такие тесты обрабатываются как пропущенные(https://github.com/junit-team/junit/wiki/Assumptions-with-assume).

**Comment by artbear** [comment]
1 `Canceled` - заготовка на будущее, я написал, чтобы не забыть. у нас все равно нет предусловий :)

2 по `ПропуститьТест` согласен. 

3
> Для пропущенных тестов, в дереве тестов устанавливать состояние мЗначенияСостоянияТестов.НеРеализован?

Сейчас так и есть, состояние же ставится именно так.

4
> Но при этом выводить отчет по ошибкам, с указанием пропущенных тестов.

Здесь не понял, поясни. сейчас пропущенные тесты указываются в хмл-файле как пропущенные/pending

**Comment by ValeraS** [comment]
3. Сейчас, состояние НеРеализован устанавливается, если тестовый метод заявлен, а по факту отсутствует. В тестах есть места, где так сделано специально (например, есть тест где при формировании списка тестов на linux к именам методов добавляется суффикс). А в большинстве  случаев, если тестовые методы в текущем режиме запуска должны пропускаться, то они просто не добавляются в список тестов.
Предлагается, тесты, которые реализованы, но не должны выполнятся обозначать вызовом `ПропуститьТест`, и считать их выполненными со статусом `Pending`. А если отсутствует реализация, то просто пропускать тест (как сейчас и делается)

4. При формировании отчета в xml, на текущий момент, указывается только два статуса `passed` и `failure`. Причем, не реализованные тесты отмечаются как пройденные успешно.

**Comment by artbear** [comment]
1. Возможно, мы об одном. 
Предлагаю совместить оба варианта - тесты с вызовом `ПропуститьТест` получают статус `Pending` + тесты, у которых нет метода-реализации, также пропускаются и получают этот статус (как и сейчас).
2. Когда выполнял предыдущую доработку для pending, я смотрел xsd-файл для JUnit XML, не увидел там варианта для записи количества `pending` в итоговые атрибуты. Плохо смотрел?

**Comment by ValeraS** [comment]
1. Наверное о разном)) Состояния тестов в обоих случаях будет одинаковым, а статус результата выполнения, предлагаю делать только для явно указанных.
2. там вроде `skipped` должен быть.

**Comment by artbear** [comment]
1. Нет, тогда не соглашусь. Нужно совместить оба подхода, юзабилити наше все.

**Comment by ValeraS** [comment]
1. Хорошо, тогда в xml тесты без реализации писать как skipped c сообщением "Отсутствует реализация тестового метода".

**Comment by artbear** [comment]
Со `skipped` в хмл согласен
