### ISSUE TITLE
На тестовом случаии в контекстном меню добавить пункт "Выполнить с исключением" 

### ISSUE THREAD

**Issue by pumbaEO** [xDrivenDevelopment/xUnitFor1C#251]
Когда   есть устоявшийся набор тестов и какой-либо один или два теста проваливается,
тогда   хотелось бы оперативно попасть в режим отладки именно для этого теста.

Сценарий: 
когда   стоим в дереве тестов на любом тесет, из контестного меню выбираем пункт "выполнить тест с исключением" 
тогда   появляеться стандартное окно ошибки и можно открыть конфигуратор
тогда   находясь в конфигураторе, можно установить "Останавливаться по ошибке" можно сразу установить точку останова в необходимом тесте.

**Comment by artbear** [comment]
Выполнено в 2.7.0.0

**Comment by artbear** [comment]
@ValeraS эта фича теперь не работает. 
Окно ошибки не выдается, а текст ошибки выводится в отчет о тестировании

ИМХО проблема в том, что метод `ВыполнитьТестовыйМетод` вызывается внутри Попытка-Исключение
