### ISSUE TITLE
Возможность запуска тестов в случайном порядке

### ISSUE THREAD

**Issue by pbazeliuk** [xDrivenDevelopment/xUnitFor1C#296]
Фича поможет выявить зависимости, связанные с порядком выполнения тестов.

**Comment by artbear** [comment]
Реализация для обычных форм (пока в отдельной ветке):
[ОФ: тесты (все или только выделенные) могут выполняться в случайном порядке при интерактивном прогоне тестов #296](https://github.com/xDrivenDevelopment/xUnitFor1C/commit/4801d87146240e9013817316ff3b002acbbb09c5)

**Comment by artbear** [comment]
Выполнено в 2.6.1.7
