### ISSUE TITLE
Сравнение макетов по значению ячеек, без учёта оформления. Утверждение ПроверитьРавенствоТабличныхДокументовТолькоПоЗначениям

### ISSUE THREAD

**Issue by Pr-Mex** [xDrivenDevelopment/xUnitFor1C#334]
На данный момент, если использовать
юТест.ПроверитьРавенствоФайлов
то при сравнении макетов (mxl), происходит сравнение и всего оформления макетов (размер шрифтов и т.д.), а часто это бывает не важно, т.к. в требованиях к отчету нет чёткого описания оформления. В итоге, при изменении, например, размера шрифта в отчете - получаем падение теста.
Хочется получить функцию сравнения макетов только по содержимому ячеек.

**Comment by artbear** [comment]
Можно выгрузить табличный документ в таблицу значений и сравнить через ПроверитьРавенствоТаблиц #386

**Comment by artbear** [comment]
По ранее указанной схеме
>Можно выгрузить табличный документ в таблицу значений и сравнить через ПроверитьРавенствоТаблиц #386

Сделал метод ПроверитьРавенствоТабличныхДокументовТолькоПоЗначениям.

**Comment by artbear** [comment]
Реализовал этот метод для УФ
[Коммит](https://github.com/xDrivenDevelopment/xUnitFor1C/commit/6e466fe3470cc6672bab24e36339d2102e7811e0)
