### ISSUE TITLE
Пустое ссылочное значение реквизита составного типа неверно выгружается в макет

### ISSUE THREAD

**Issue by nalsa** [xDrivenDevelopment/xUnitFor1C#346]
Имеется справочник с табличной частью, в которой есть реквизит составного типа: Число, Строка, Булево, Дата и некоторые справочники. При генерации макета, когда реквизит имеет тип какого либо справочника (значение = пустая ссылка) в макет такое значение не выводится.
В итоге при загрузке в реквизите значение "Неопределено".

**Comment by artbear** [comment]
Выполнено.
