### ISSUE TITLE
ОФ+УФ: Убрать попытку загрузки тестов из каталога .git

### ISSUE THREAD

**Issue by JohnyDeath** [xDrivenDevelopment/xUnitFor1C#364]
Если каталог с тестами находится под управлением git, а в хуках у него добавлен разбор на исходные коды (precommit1C), то браузер тестов пытается загрузить v8Reader.epf
Предлагаю добавить жесткое игнорирование служебного каталога ".git" или вообще не сканировать скрытые папки или начинающиеся на "." в линукс-случае

**Comment by artbear** [comment]
для тестов УФ проверки на скрытый каталог .git нет.
Нужно исправить
