### ISSUE TITLE
Незначащие строки в конце макета приводят к ошибке при создании тестовых данных

### ISSUE THREAD

**Issue by artross** [xDrivenDevelopment/xUnitFor1C#367]
Версия 2.6.0.8, скрин прилагается, незначащие строки выделены и подписаны.

Тест-раннер считает их продолжением последнего загружаемого объекта и пытается заполнить ему реквизиты с пустыми именами.

![default](https://cloud.githubusercontent.com/assets/9880207/5438684/2806bcb0-848b-11e4-82c3-bcfd066cff54.png)

**Comment by e-mc2** [comment]
После перехода на новую версию (2.6.1.0) ошибка сохраняется, в результате все мои старые тесты упали (

**Comment by artbear** [comment]
Выполнено.
https://github.com/xDrivenDevelopment/xUnitFor1C/commit/16eb5c71e6969707721674df2961e1fc69141765
