### ISSUE TITLE
Создание данных на основе макета, при создании элемента справочника группы, очищаются табличные части которых нет.

### ISSUE THREAD

**Issue by IvanSub** [xDrivenDevelopment/xUnitFor1C#376]
Создание данных на основе макета, при создании элемента справочника группы, очищаются табличные части которых нет(не доступны для групп).

Функция СоздатьОбъект_Справочник
"
Для каждого мдТабЧасть из Объект.Метаданные().ТабличныеЧасти Цикл
		Объект[мдТабЧасть.Имя].Очистить();
	КонецЦикла;
"

//Заполняем реквизиты справочника
	НаборМдРеквизитов = НаборРеквизитовМетаданных(ПротоОбъект.Тип, Объект.Метаданные());
	Для каждого стрПоле Из ПротоОбъект.ПоляОбъекта Цикл
		Объект[стрПоле.Имя] = ПолучитьЗначениеПоля(ПротоДанные,стрПоле,НаборМдРеквизитов);
	КонецЦикла;
	
	Для каждого мдТабЧасть из Объект.Метаданные().ТабличныеЧасти Цикл
		Объект[мдТабЧасть.Имя].Очистить();
	КонецЦикла;
	Для каждого ТабЧасть из ПротоОбъект.ТабличныеЧасти Цикл
		Для каждого СтрокаТабЧасти Из ТабЧасть.Значение Цикл
			СтрокаТабЧастиОбъекта = Объект[ТабЧасть.Ключ].Добавить();
			объектМетаданныеТабличнаяЧасть = Объект.Метаданные().ТабличныеЧасти[ТабЧасть.Ключ];
			НаборМдРеквизитовТЧ = объектМетаданныеТабличнаяЧасть.Реквизиты;
			Для каждого стрПоле Из СтрокаТабЧасти Цикл
				СтрокаТабЧастиОбъекта[стрПоле.Имя] = ПолучитьЗначениеПоля(ПротоДанные,стрПоле,НаборМдРеквизитовТЧ);
			КонецЦикла;
		КонецЦикла;
	КонецЦикла;

**Comment by e-mc2** [comment]
Спасибо, доработка помогла!

**Comment by artbear** [comment]
Исправлено https://github.com/xDrivenDevelopment/xUnitFor1C/commit/4c896fcc42857d4959f14922be7bf0642bb6137e

**Comment by artbear** [comment]
Ошибка появилась повторно.
@ValeraS сможешь посмотреть и добавить к своему пулл-реквесту https://github.com/xDrivenDevelopment/xUnitFor1C/pull/427 ?

**Comment by ValeraS** [comment]
@artbear Так ошибка только в отсутствии тестов или что-то ещё?

**Comment by artbear** [comment]
Нет, сейчас эта ошибка повторяется.
Проблема в том, что при создании макета из боевых данных не устанавливается режим Группа.
@ValeraS этой проблемой не занимайся.
У меня уже есть пулл-реквест не через Гитхаб, в котором этот баг поправлен.
Сам буду мержить.
