### ISSUE TITLE
Некорректная работа с транзакциями внутри тестов

### ISSUE THREAD

**Issue by EvilBeaver** [xDrivenDevelopment/xUnitFor1C#378]
1. xddRunner запускает тест вне транзакции
2. Внутри тестируемого кода открывается транзакция
3. Выбрасывается исключение
4. Исключение перехватывается xddRunner, но транзакция не откатывается
5. Все очередные тесты выполняются в транзакции, в которой уже было исключение
6. Все очередные тесты при попытке обращения к базе выбрасывают исключение "В данной транзакции уже происходили ошибки"
7. Переход к пункту № 4

В результате, иногда обращение к базе внутри сбойной транзакции приводит даже не к исключению, а к падению клиента 1С:Предприятия. Это зависит уже от тестируемой конфигурации, глубоких исследований причин падения пока не проводил.

Ожидается поведение:
1. Запускается тест внутри Попытки
2. Мы не доверяем тесту и если поймали исключение, то отменяем транзакцию, т.к. она неизбежно испорчена
3. Следующий тест начинает работать вне транзакции (может снова ее начать в ПередЗапускомТеста, если захочет)

**Comment by artbear** [comment]
ИМХО Кто начинает транзакцию, тот и должен её отменить. 
Так что если тест начал транзакцию, то в коде теста в методе ПослеЗапускаТеста нужно добавить
  Если ТранзакцияАктивна() Тогда
    ОтменитьТранзакцию();
  КонецЕсли;

Это нужно записать в список известных проблем в Вики. 

Но можно и xUnitFor1C доработать конечно :)

**Comment by EvilBeaver** [comment]
Тут дело совсем в другом. Тест не начинал транзакций. Он понятия не имеет есть ли транзакции в нижних уровнях проверяемого кода. А они там есть. И есть оттуда выбрасываемый эксепшен. Тест не начинал транзакций и не собирается их отменять.

Дело в уровнях абстракции. Runner запускает некий код и восстанавливает свое состояние. Если он обнаружил, что отловил исключение и активна транзакция, значит все, алес капут. Все последующие тесты будут поломаны. Нужно откатывать на уровне раннера в блоке "Исключение". Это не "список известных проблем", это обязанность фреймворка.

**Comment by artbear** [comment]
Выполнено в 2.6.1.2

**Comment by Zaidfly** [comment]
Теперь, у меня такое поведение: Тест начал транзакцию (для создания тестовых данных), на проверке юТест.ПроверитьРавенство() - упал. В этом случае тесты всегда падают по исключению. В соответствие с доработкой, фреймворк, поймав исключение, отменяет транзакцию. Дальше выполняется процедура ПослеЗапускаТеста(), где тоже пытается отменить транзакцию - снова падает. Это фреймворком считается как еще одно падение и в результате в отчет попадает 2 ошибки из одного теста и в общем количестве упавших тестов - 2.

Что-то тут явно теперь не так.

**Comment by artbear** [comment]
У тебя, видимо, простая отмена без проверки.
ИМХО код отмены транзакции всегда нужно писать так
```
Если ТранзакцияАктивна() Тогда
  ОтменитьТранзакцию();
КонецЕсли;
```

**Comment by Zaidfly** [comment]
Ок. Тогда это нужно поменять во всех тестах. Может написать где-нибудь об этом? У других возможны подобные вопросы.

**Comment by EvilBeaver** [comment]
Во-первых, Артур прав и транзакции лучше всегда отменять с предварительной проверкой. Это вообще, без привязки к текущему pull-request.
Что касается текущей проблемы, то можно проверять - если упал тест, который взвел флаг транзакции (и планирует ей управлять) - то вот эту отмену, которую я внес - не делать.

**Comment by artbear** [comment]
Лады. Напишу в известных проблемах на Вики.

**Comment by artbear** [comment]
Написал в [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8)

**Comment by artbear** [comment]
Блок 
```
Если ТранзакцияАктивна() Тогда
  ОтменитьТранзакцию();
КонецЕсли;
```
нужно заменить на цикл
```
Пока ТранзакцияАктивна() Цикл
  ОтменитьТранзакцию();
КонецЦикла;
```
т.к. 1С при использовании `ОтменитьТранзакцию` не гарантирует отмену *всех* вложенных и внешних транзакций.
Нашли совместно с @EvilBeaver

**Comment by artbear** [comment]
Еще подумали и решили, что использования циклической отмены транзакций юзать нельзя, т.к. это может привести к сюрпризу - записи данных вне транзакции, хотя разработчик теста рассчитывал на транзакцию.

А главной ошибкой является то, что транзакция может начинаться в ПередЗапускомТеста, далее в этом же методе происходит ошибка, а отката транзакции в хЮнит не происходит. 
В итоге счетчик транзакций просто увеличивается и 1С считает, что работаем со вложенными транзакциями, что приводит к той самой ошибке `"В данной транзакции уже происходили ошибки"`.

Исправление готово, сколько залью.

**Comment by artbear** [comment]
Исправление внесено.
