### ISSUE TITLE
Режим поиска элементов при создании данных по макету.

### ISSUE THREAD

**Issue by Pr-Mex** [xDrivenDevelopment/xUnitFor1C#380]
Необходимо добавить возможность поиска по ключевым реквизитам как в Конвертации данных.
Сейчас всегда создаются новые элементы, а не обновляются существующие.

**Comment by artbear** [comment]
Предлагаю в качестве решения добавлять специальную табличную часть типа xddSearch/xddFind
в которой будут указаны реквизиты для поиска ссылки на элемент.
Народ, что скажете?
@Zaidfly @Pr-Mex ?

**Comment by Zaidfly** [comment]
Мне кажется это не удобно. Я бы сделал режим "Ключ" у реквизита. Если нужно найти элемент по коду - то напротив кода пишем "Ключ". Если необходимо найти элемент по составному реквизиту - добавляем режим "ключ" для всех полей, комбинация которых будетя вляться искомым ключом.

**Comment by artbear** [comment]
@Zaidfly Каким образом ты у реквизита укажешь 2 ключа - например, уже стоит ключ Перем, и нужно еще указать ключ поиска?
приведи пример заполнения (или даже вставь картинку с примером макета)

**Comment by Zaidfly** [comment]
![image](https://cloud.githubusercontent.com/assets/7807831/6441586/5dbf382c-c0fa-11e4-9ee4-373d2150feea.png)

**Comment by artbear** [comment]
Как-то не лежит душа у меня по заданию ключей через разделители в одной ячейке :(
У боевого объекта куча реквизитов и выискивать глазами, какие реквизиты являются ключевыми, совсем неудобно.
А отдельная ТЧ структурирована и легко читается. И режим реквизита не меняется.
Что скажете?

**Comment by Zaidfly** [comment]
Я уже сказал. Я вижу описание реквезитов и хочу в этом описании видеть какие из реквизитов для объекта ключевые. Мне это наоборот кажется логичным и удобным.

**Comment by Zaidfly** [comment]
Так:
![image](https://cloud.githubusercontent.com/assets/7807831/6445574/da829b40-c115-11e4-8055-bc2eeab26553.png)

**Comment by artbear** [comment]
Да, пока предварительно договорились c @Zaidfly будем для ключей использовать цвет Красный (RGB, R=255)

**Comment by xdd-ci-admin** [comment]
​Здесь дерево наблюдается, может не стоит использовать красный как признак
ключевых реквизитов.
Может перейти на строковое представление дерева ?

Аналогии можно своровать из yml. Я сейчас тестовые данные выгружаю в JSON и
загружаю оттуда же:

​

**Comment by allustin** [comment]
![2015-03-03 13-43-13](https://cloud.githubusercontent.com/assets/55323/6460799/8381cfdc-c1ab-11e4-94a1-1d1acb3dc9ee.png)

По e-mail ответилось от CI админа (странно)

**Comment by artbear** [comment]
@allustin Если ты или кто-то другой реализует подобное поведение (JSon-представление) для xUnitFor1C, буду только рад.
А я вряд ли буду заниматься подобной реализацией, т.к. считаю его не очень дружелюбным для восприятия человеком. ИМХО Табличный документ рулит для человека.
Как внутреннее представление макета в виде текста внутри гита такое представление вполне возможно, но для человека оно смотрится не очень.

По цвету - мы перебирали несколько вариантов (отдельная колонка, несколько режимов реквизита через разделитель в одной ячейке, отдельная ТЧ для ключевых реквизитов). у всех есть свои плюсы и минусы. Приняли решение, что цветовая раскраска быстро сообщит человеку о составе ключевых реквизитов.

**Comment by pumbaEO** [comment]
Мне больше yaml импонирует, все-таки в json очень часто запутываешься в ковычках и скобках.
![yaml](https://cloud.githubusercontent.com/assets/166003/6462610/366e4b64-c1b3-11e4-9c66-f3e1fde3557b.png)

**Comment by artbear** [comment]
@allustin @pumbaEO Приведи, плиз, примеры одного и того же макета данных в разных форматах. Желательно, чтобы макет не был самым простым :)
Скриншот табличный документ и скриншот предлагаемого варианта.
Мы в сравнении сразу увидим плюсы и минусы.

**Comment by artbear** [comment]
@pumbaEO ага, yaml выглядит прикольно, но нужны реальные примеры и сравнения с табличным документом.

**Comment by pumbaEO** [comment]
@artbear yaml вытянит настройку в глубь, в сравнении с табличным документом будет значительно больше экранов занимать... 
В тоже время, простой текстовый конфиг, позволяет проще смотреть на различия в версионном контроле чем табличный документ, имхо преобразование в cvs , было-бы интерестным решением.

**Comment by allustin** [comment]
@pumbaEO мне тоже yaml импонирует - он базовый для меня последние года 3, в том числе и с docker и c ruby (rspec и cucumber). Но как реализовать такой интерпретатор для 1С в виде библиотеки - я думал что можно будет работать через NativeAPI, а библиотеку брать по крутому отсюда https://code.google.com/p/yaml-cpp/source/browse/#hg. Поэтому для простоты указал JSON. С ним в 1С проще.

yaml поддерживает кросс-ссылки на другие элементы внутри файла. Соответственно можно выгружать через ODataToYAML - тогда платформа сама выгрузит все необходимые объекты по ссылкам.

@artbear человеко-читаемость должна быть и на портале исходных кодов, а не только в Конфигураторе - как Сode Review проводить то. А тут что для Stash, что для Redmine (gitlab) необходим plain text. И это будет проблемой.

Если вы сейчас сделаете признак заточенный только под MXL (я про цвет), тогда это навсегда - обратной совместимости при переходе на yaml

**Comment by allustin** [comment]
@pumbaEO ты имел ввиде csv ?

**Comment by allustin** [comment]
@artbear  реальный пример я дал выше, у меня тестовые данные хранятся в файлах *-fix.json

fix - сокращение от fixtures http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
пока до YAML я не добрался, но мы работаем

такой комплект тестовых данных повторно используемый - что для 1С, что для Rails, что для Clojure

**Comment by artbear** [comment]
Я уже предлагал выше, что можно различать представление для пользователя и представление для гита. Фактически это бинарник (сборка) и его исходники.
Т.е. для пользователя макет хранится в бинарном виде (табличный макет), а при помещении в гит идет разбор на текстовое представление.
Фактически это задача для проекта precommit1c

**Comment by allustin** [comment]
@artbear типа такого ?

Функция ТабличныйДокументToJSON() Экспорт
Функция ТабличныйДокументToYAML() Экспорт
Функция ТабличныйДокументToCSV() Экспорт

тогда может не будете использовать цвет, а выделите группу как xddMods, типа xddKeys

**Comment by artbear** [comment]
@allustin я согласен с @pumbaEO - при работе с json быстро запутаешься с количество скобочек разных видов :)
Трудно его редактировать :(

**Comment by allustin** [comment]
Просто это штатный метод выгрузки из 1С, точнее наиболее быстрый.

причем быблиотека JSON которая НЕ 1С-ная, умеет расшифровывать ссылочные типы автоматиически.

Но я делаю аналог вот этого https://github.com/cucumber/cucumber/wiki/Fixtures
И там придется использовать именно YAML

**Comment by EvilBeaver** [comment]
Позвольте вставить пару слов?
Во-первых, кодирование цветом - это фу-фу. Так не делается. С другой стороны, моксель действительно, более читабельный чем XML или даже YAML.
Компромисс - создание тестовых данных в таб. документе и экспорт в текст для контроля версий. Табличный документ элементарно выгружается в XML из 1С в две-три строчки, но это не семантический XML, а "оформительский".
Предлагаю начать не с выбора формата, а с постановки целей и сценариев использования.

Считаю, что формат тестовых данных должен быть семантическим. А ТабличныйДокумент - неплохой редактор (визуальное представление) для этого формата.

**Comment by pumbaEO** [comment]
@EvilBeaver :+1:  про цвет согласен. Имхо как раз варинат ТабличныйДокументToCSV() и обратное ТабличныйДокументFromCSV() позволит как хранить данные в удобном формате для code-review , так и для merge. (CSV поменять на json, jaml) - это отдельная задача получается. 

Т.е. цветом некошерно, предлагаю по сути вопроса добавлять еще одну колонку в табличный макет(необязательную) по которой уже можно и определять "поиск/не поиск".

**Comment by artbear** [comment]
Я уже писал выше 
>По цвету - мы перебирали несколько вариантов (отдельная колонка, несколько режимов реквизита через разделитель в одной ячейке, отдельная ТЧ для ключевых реквизитов). у всех есть свои плюсы и минусы. 

Предлагайте свои варианты, я вообще изначально был за отдельную колонку.

**Comment by artbear** [comment]
@pumbaEO ТабличныйДокументToCSV() и прочие преобразования предлагаю делать именно в precommit1c и v83unpack. для пользователя xUnitFor1C ничего не должно поменяться.

**Comment by EvilBeaver** [comment]
Если вернуться к формулировке задачи, то я за отдельную колонку. А вообще - за доработку, в которой макет тестовых данных будет на некоем "markup language", а таб.документ - просто визуальное представление этого ML

**Comment by artbear** [comment]
Да, мы с @EvilBeaver поговорили и пришли к выводу, что есть смысл задуматься о редакторе тестовых данных, в котором реализовано отделение визуального представления и внутреннего формата данных.
Фактически, я уже сделал в генераторе макетов редактор тестовых данных - можно вставить любой макет в поле табличного документа, доработать его, протестировать на правильность и сохранить куда-нибудь в файл. Но отдельно этот функционал редактирования не выделял.

Но это вопрос отдельной задачи. сейчас все-таки нужно решить задачу попроще :)

**Comment by artbear** [comment]
Предлагаю принять решение по табличному документу.
Сейчас есть 3 голоса за отдельную колонку ключей.
Еще какие варианты предлагаете?

**Comment by artbear** [comment]
Добавил поиск по ключам для справочников, документов, задачи и бизнес-процессов
Прошу проверить.
@Pr-Mex посмотришь?
![image](https://cloud.githubusercontent.com/assets/2920817/6744382/ed0ec8b8-ceb9-11e4-846b-5a2fb29f98c7.png)

**Comment by Pr-Mex** [comment]
Да, только как доберусь.
