### ISSUE TITLE
В генераторе макетов сделать сохранение настроек

### ISSUE THREAD

**Issue by Pr-Mex** [xDrivenDevelopment/xUnitFor1C#387]
Сделать сохранение/загрузку настроек в какие-либо внешние файлы.
Иногда настройки бывают сложными.
Каждый раз их воспроизводить руками - надоедает.

**Comment by artbear** [comment]
Какие именно настройки? Дерева метаданных? или что-то еще?
Опиши сценарий, когда нужны абсолютно те же самые настройки.

**Comment by Zaidfly** [comment]
Плюс. Нужная фича.
> Дерева метаданных? или что-то еще?
Дерево, выставленные галочки, отборы и все остальные насктройки, которыми мы кастомизируем генерацию макета.

**Comment by artbear** [comment]
Давно реализовано
