### ISSUE TITLE
Неудобные имена уникальных переменных в макетах тестовых данных

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#390]
Неудобные имена уникальных переменных в макетах тестовых данных
Например, если для регистра сведений АдресноеХранение в макет выгружаем 3 записи, будут созданы 3 записи по регистру.
У 1-й записи имя переменной будет АдресноеХранение_1
У 2-й записи имя переменной будет АдресноеХранение_12
У 3-й записи имя переменной будет АдресноеХранение_123
Это очень неудобно при увеличении количества записей.
Автор @PR-Mex

**Comment by artbear** [comment]
ИМХО удобно реализовать, чтобы не добавлялась строка, а добавлялось число
и тогда
У 1-й записи имя переменной будет АдресноеХранение_1
У 2-й записи имя переменной будет АдресноеХранение_2
У 3-й записи имя переменной будет АдресноеХранение_3

**Comment by Pr-Mex** [comment]
Да. Это то что нужно.
