### ISSUE TITLE
Обращение к переменной, которая была создана по ГУИДу 

### ISSUE THREAD

**Issue by e-mc2** [xDrivenDevelopment/xUnitFor1C#391]
Если я создаю элемент справочника по ГУИДу, то не могу обратиться к этому элементу через режим "Перем":

![2015-01-28_17-40-15](https://cloud.githubusercontent.com/assets/3093170/5939449/d546b852-a714-11e4-8e0d-3649d63ec66c.jpg)

такое использование выдает ошибку:

{ВнешняяОбработка.xddTestRunner.МодульОбъекта(1436)}: ЗначениеНеНайдено: Реквизит <Свойство>: Искали значение <КоммУслуги>, но не нашли!

**Comment by artbear** [comment]
@e-mc2 Пока не подтверждается.
Макет, указанный ниже, как видно, прекрасно тестируется и создается.
![image](https://cloud.githubusercontent.com/assets/2920817/5993520/1d4be390-aa65-11e4-856b-f334fc7da207.png)

Проверь на последнее версии из девелоп 2.7.0.9
Я вносил некоторые исправления

ОФФ. Приглашай, готов посмотреть реальный макет и твой тест.

**Comment by artbear** [comment]
ИМХО давно исправлено.
