### ISSUE TITLE
Реализовать создание первого пользователя "admin" при первом запуске ИБ xUnitFor1C 

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#397]
Реализовать создание первого пользователя "admin" при первом запуске ИБ xUnitFor1C 
Важно для исключения хранения бинарника TestBase.dt и упрощения запуска тестов непрерывной интеграции.

**Comment by artbear** [comment]
Уточню требование - сделать отдельный шаг "Создание пользователя в чистой базе" - при запуске из командной строки если пользователей нет, создать пользователя и выйти. если пользователи есть, сразу выйти из базы.
ИМХО перезапуск после создания базы нужен только для интерактивной работы.
При запуске из командной строки перезапуск не нужен.
В командной строке задается отдельный параметр `AdminCreate`/`СоздатьАдминистратора`
и строка запуска конфигурации 1С выглядит так `1cv8.exe /С "AdminCreate"`

**Comment by ValeraS** [comment]
Так не получиться. Если пользователи есть, а в строке запуска не указан параметр /NИмя, то появится окно с выбором пользователя и автоматом не войдешь.

**Comment by artbear** [comment]
Для автозапуска все будет работать автоматом. Схема:
1 шаг - создание пользователя `1cv8.exe /С "AdminCreate"`
2 шаг - запуск тестированиz `1cv8.exe /NAdmin /Execute xddTestRunner.epf /С "КомандыТестирования"`

А для интерактива пусть будет перезапуск
