### ISSUE TITLE
При случайном порядке запуска тестов иногда падает тест ТестыГенератораДанных.Тест_ДолженСоздатьПростойСправочникПоискомПоГуид

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#400]
При случайном порядке запуска тестов иногда падает тест ТестыГенератораДанных.Тест_ДолженСоздатьПростойСправочникПоискомПоГуид

**Comment by ValeraS** [comment]
Тест падает, если перед ним выполнить тест ТестыГенератораДанных.Тест_ДолженНайтиИПерезаполнитьПростойСправочникПоискомПоГуидуСсылки. Так же падает тест ТестыГенератораДанных.Тест_ДолженНайтиИПерезаполнитьПростойСправочникПоискомПоГуидуСсылки если его два раза подряд выполнить.
Поведение какое-то странное:
 При первом проходе теста, все хорошо. А при втором, когда записывается новые элемент справочника, то Объект.ВерсияДанных <> Объект.Ссылка.ВерсияДанных. И дальше работа с объектом, полученным по ссылке приводит к ошибке.

Похоже на ошибку платформы.
![2015-02-05 18-03-06](https://cloud.githubusercontent.com/assets/10867286/6062545/a5ae2d34-ad61-11e4-971a-2c442430e1c4.png)

**Comment by artbear** [comment]
Ага, спасибо за исследование.
Меня периодическое падение этого теста также замучило :(
Также подозреваю платформу.

**Comment by artbear** [comment]
@ValeraS Большое спасибо!

**Comment by artbear** [comment]
Самое интересное, что тесты гарантированно разделены транзакциями.
