### ISSUE TITLE
Ошибка при попытке создать каталог в тесте Tests_CmdLine.epf когда в имени каталога временных файлов присутствуют точки

### ISSUE THREAD

**Issue by Kotje** [xDrivenDevelopment/xUnitFor1C#401]
В процедуре "ВыполнитьОдинТестЧерезЗапуск1СПредприятия"
удаление точки в текущем виде:
ПутьОтчетов = СтрЗаменить(ПолучитьИмяВременногоФайла(), ".", "")
является некорректным, т.к. в пути может присутствовать каталог с точкой, например ivan.ivanov

**Comment by artbear** [comment]
Спасибо. 
На днях выпускаю релиз. Поправлю.
