### ISSUE TITLE
Генератор макета данных. Ошибка реквизита "Субконто". БП 3.0

### ISSUE THREAD

**Issue by JohnyDeath** [xDrivenDevelopment/xUnitFor1C#409]
при создании макета на основании реальных данных в конфигурации Бухгалтерия 3.0 на документе ПоступленияТоваровУслуг, вылетает ошибка 
>
> <<< Генератор макета из реальных данных: Не умею обрабатывать такой тип <Не определено> Не умею обрабатывать реквизит <Субконто2> у объекта > <Документ.ПоступлениеТоваровУслуг>

ругается на незаполненное(неопределенное) субконто, и макет вообще не формируется. т.к. вызывается исключение. это и в ОФ и в УФ

**Comment by artbear** [comment]
Исправлено в 2.7.1.4
