### ISSUE TITLE
Падает в дамп при открытии тест ранера внешнего на 8.2.18.102, 19.83

### ISSUE THREAD

**Issue by Ndochp** [xDrivenDevelopment/xUnitFor1C#412]
Падает на последней строке модуля объекта

ЭтоВстроеннаяОбработка = Не Метаданные.НайтиПоТипу(ТипЗнч(ЭтотОбъект)) = Неопределено;

по причине того, что ТипЗнч(ВнешниеОтчеты.Создать("F:\1CBase\xddTestRunner.epf")) у меня вызывает ошибку вида:
"Тип не определен "некий гуид" 
Завершить работу/Перезапустить

**Comment by artbear** [comment]
Какие действия выполняешь? 
какую версию обработки юзаешь? из какой ветки?

**Comment by artbear** [comment]
Странная ошибка, боюсь, опять что-то из-за особенностей платформы 1С.
Я дома нарвался на эту же ошибку на 8.2.19.68 при открытии на ОФ на файловой базе
несколько раз запускал, был баг.
Затем открыл через отладчик, посмотрел эту строчку и баг перестал повторяться :(
в отладчике, без отладчика баг уже не повторяется.
попытался смоделировать баг - 
- создавал новую пустую файловую базу, запускал раннер, 
- загружал старую тестовую базу, запускал раннер
- загружал в эту базу новую конфигурации, запускал раннер
- еще несколько странных шаманских тестов,
ошибка больше ни разу не повторилась :(

**Comment by Ndochp** [comment]
Действие - файл-открыть тест ранер.
Режим - толстый ОФ
Работает действительно не стабильно. Гонял туда обратно вариант исправления, падать перестало само.
Похоже глюк платформы в объекте "ВнешниеОтчеты". Гонял в консоли следующий код:
``` 1c
цй = ВнешниеОтчеты.Создать("F:\1CBase\xddTestRunner.epf");
йц = ТипЗнч(цй);
//йц = ТипЗнч(ВнешниеОтчеты.Создать("F:\1CBase\xddTestRunner.epf"));
```
В таком режиме отрабатывает, а если раскомментировать третью строку и закрыть первые две- падает стабильно. То-ли времени иногда не хватает на регистрацию, толи еще что.

В итоге переписал у себя функцию в модуле объекта тест ранера "ЭтоВнешняяОбработка" на работу с "ИспользуемоеИмяФайла". Может включить ее в таком виде, раз не только у меня порой воспроизводится?

```1C
Функция ЭтоВнешняяОбработка(ПарамОбъект = Неопределено) Экспорт
	Перем НужныйОбъект;
	НужныйОбъект = ПарамОбъект;
	Если НужныйОбъект = Неопределено Тогда
		НужныйОбъект = ЭтотОбъект;
	КонецЕсли;
	
	#Если ТолстыйКлиентОбычноеПриложение или ТолстыйКлиентУправляемоеПриложение или Сервер Тогда
		СисИнфо = Новый СистемнаяИнформация;
		Если СисИнфо.ВерсияПриложения < "8.2.19.83" Тогда
			Рез = ЗначениеЗаполнено(НужныйОбъект.ИспользуемоеИмяФайла);
		Иначе
			Рез = Метаданные.НайтиПоТипу(ТипЗнч(НужныйОбъект)) = Неопределено;
		КонецЕсли;
	#Иначе
		Рез = Метаданные.НайтиПоТипу(ТипЗнч(НужныйОбъект)) = Неопределено;
	#КонецЕсли
	
	Возврат Рез; 
КонецФункции
```

**Comment by artbear** [comment]
Давно хотел спросить, почему `ВнешниеОтчеты`, когда у нас внешняя обработка и в коде юзается  `ВнешниеОбработки` ?

**Comment by artbear** [comment]
В общем, пока не понятно :(

**Comment by artbear** [comment]
Жду ответа.

**Comment by Ndochp** [comment]
Это была копипаста из запуска Мобильных инструментов разработчика, не заметил. Да собственно платформе без разницы, она съедает ТестРанера как отчет вроде.
Ну и ```цй = ТипЗнч(ВнешниеОбработки.Создать("F:\1CBase\xddTestRunner.epf"));``` кладет базу.
Но, эта фраза у меня успешно кладет базу и на 19.83, так что может проблема и не в этом.

С другой стороны, если исходная ошибка прояляется (хоть и не стабильно) только в толстом клиенте обычных формах, то может для этого случая переписать определение "внешности" через ```ИспользуемоеИмяФайла``` в попытке исключении? (падает в исключение - значит встроенная).

**Comment by artbear** [comment]
Ошибка сегодня дома еще несколько раз повторилась на 8.2.19.68 :(
Лечилась просто - я перед проверкой `Метаданные.НайтиПоТипу(ТипЗнч(НужныйОбъект)) = Неопределено` вставлял пустую строку, перезаписывал файл и перезапускал 1С.
очень странно.

**Comment by ValeraS** [comment]
У меня раннер  в режиме обычных форм стал валить предприятие при запуске, во время загрузки тестов из-за информатора. Падает в дамп на строке 214 модуля объекта xddInformator: 		ScrptCtrl.AddCode(ТекстМодуля);

**Comment by artbear** [comment]
@ValeraS платформа 1С какая? платформы винды? клиент-сервер, 32/64?

**Comment by ValeraS** [comment]
8.2.19.121 файловая Windows 7 64
на этой же конфигурации раньше не падало.

**Comment by artbear** [comment]
Странно, буду проверять.

**Comment by Ndochp** [comment]
Аналогичный случай (с падением на ScrptCtrl.AddCode(ТекстМодуля); ) у меня объяснился тем, что тест не проходил синтакс контроль. В итоге, от загрузок тестов из папки пришлось перейти на загрузку теста из файла, так как иначе тест ранер конфликтует с автосохранением внешних обработок из снегопата.

**Comment by artbear** [comment]
@Ndochp поясни конкретнее, при чем здесь синтакс-контроль. что-то я совсем не понял связи с Информатором.

**Comment by Ndochp** [comment]
текс.... Поясни ть не могу, в следующий раз как столкнусь, создам ишшку с примером воспроизведения. 
Но у меня было несколько раз, что при наличии теста с синтакс ошибкой, при загрузке тестов система падала, вместо того, чтобы просто ругнуться ```Ошибка: {ВнешняяОбработка.xddTestRunner.МодульОбъекта(2929)}: Ошибка при вызове метода контекста (Создать)```

**Comment by artbear** [comment]
У меня подобных сообщений очень давно не было.
Да и народ, кто юзает раннер, не обращался с подобными ошибками очень давно.
Предлагаю закрыть задачу до следующего проявления и я наконец-то выпущу релиз :)

@Ndochp @ValeraS Жду ответа от обоих

**Comment by Ndochp** [comment]
Согласен. Сейчас еще попинал со всех сторон, не воспроизвелось.

**Comment by ValeraS** [comment]
Воспроизводится. При открытии раннера во время получения тестовых случаев из обработки. Не могу понять причину, может раз запуститься, а потом постоянно падает. Чаще падает чем, запускается.

На другой машине с XP не воспроизводится.

**Comment by artbear** [comment]
@ValeraS У тебя вылет именно по Информатору?

**Comment by ValeraS** [comment]
@artbear да

**Comment by artbear** [comment]
@Zaidfly насколько для тебя критично использование Информатора?
т.е. у тебя все скрипты используют Информатор?

**Comment by Zaidfly** [comment]
@artbear, да, все тесты используют информатор в обоих проектах.

**Comment by artbear** [comment]
Нужно какое-то решение - возможность простого и удобного отключения/включения Информатора.
Т.е. по умолчанию он включен для ОФ, как и сейчас, но его можно отключить при желании.
В тестах несложно сделать через спец.параметр командной строки, а вот с интерактивом сложнее.
Не могу придумать для интерактива удобный вариант.
Народ, что предложите?

**Comment by artbear** [comment]
Родилась идея - 
1. сделать некую прослойку - обработка, которая настраивает запуск браузера тестов для текущей ИБ в сложных ситуациях. Например, включить/выключить Информатор, включить/выключить автозагрузку последнего открытого теста (для исключения #442 ), т.е. загрузка раннера без тестов
2. или просто перед запуском в хранилище ИБ запоминать флаг, что раннер запускается. в обычном случае после нормальной загрузки раннера этот флаг сбрасывается и все хорошо.
в случае неудачи загрузки флаг не изменится. При следующем запуске проверять этот флаг, если он включен, значит, раннер не смог загрузиться и нужно дать пользователю возможность выбора. например, упомянутые ранее отключения/включения в отдельной форме раннера.

Все это только для интерактива, для командной строки поведение не должно меняться.
максимум - можно добавить команду в командную строку по использованию Информатора.

юзабельность продукта явно повысится.
Что скажете?

**Comment by Zaidfly** [comment]
@artbear Почему это вообще проблема? При открытии ТестРанера проверять, если информатор есть - он используется, если его нет - не пытаться его инициализировать. Тот, кому он мешает - не ставит его себе в конфигурацию/папку с обработками. О том, что в некоторых случаях информатор может вызывать дамп - написать в известных проблемах.

**Comment by artbear** [comment]
Представь, человек разворачивает хюнит и получает сразу падение 1с1С.
Пытается запустить второй раз и снова падение и снова и снова.  негатив :(
Зачем лишние трудности для пользователей?
Человеку должно быть удобно пользоваться продуктом.
Недавно нас даже похвалили за неожиданно дружественным интерфейс для
пользователя :)

**Comment by artbear** [comment]
Я дома периодически получаю падение :(

**Comment by artbear** [comment]
Реализовал п.2 из https://github.com/xDrivenDevelopment/xUnitFor1C/issues/412#issuecomment-77556309
https://github.com/xDrivenDevelopment/xUnitFor1C/commit/0525547404a56b28c3d57fc7c0a920c4296b56ff

**Comment by xdd-ci-admin** [comment]
А если запускать 1с предприятие с флагом "конвертировать внешние обработки"?

2015-03-18 20:41 GMT+02:00 Artur Ayukhanov <notifications@github.com>:

> Реализовал п.2 из #412 (comment)
> <https://github.com/xDrivenDevelopment/xUnitFor1C/issues/412#issuecomment-77556309>
> 0525547
> <https://github.com/xDrivenDevelopment/xUnitFor1C/commit/0525547404a56b28c3d57fc7c0a920c4296b56ff>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xDrivenDevelopment/xUnitFor1C/issues/412#issuecomment-83116353>
> .
>



-- 
Сосна Евгений Викторович
mail:shenjasosna@gmail.com

**Comment by ValeraS** [comment]
@artbear Информатор используется только для внутренних нужд раннера и не доступен для тестовых обработок? Может сделать обратную настройку, то есть, по умолчанию, информатор отключен, а если надо то в настройках его включать.

Если раннер запускается под вновь созданным пользователем, то у него ещё нет настроек и, соответственно, информатор подключается, что, в дальнейшем, приводит к ошибке.

**Comment by artbear** [comment]
Информатор как раз полезен для тестовых обработок.
Позволяет не описывать каждый тест в ПолучитьСписокТестов(), т.к. Информатор получает список методов тест.объекта в рантайме. очень удобно, т.к. не нужно дублировать описание и определение теста.
К сожалению, работает только в ОФ.

У нескольких команд есть тесты, в которых юзается эта фича, они наверняка будут против.
@Zaidfly что скажешь?

По новому пользователю - если у него будет вылет при первом запуске, это, конечно, грустно. Но при втором запуске он сможет отключить неверный компонент.

Давайте обсудим

**Comment by ValeraS** [comment]
В `Тест_ЗапускТестовВСеансеДругихПользователей` каждый раз создается новый пользователь и ему нет возможности указать эту настройку. Может, тогда, добавить параметр запуска `ЗапретитьИспользованиеИнформатора`?

**Comment by pumbaEO** [comment]
Мое имхо: в основном информатором не пользуюсь, т.к. как уже сказали "УФ" не поддерживает, описать тестовые процедуры, опять таки мне удобней сначало напротипировать названия тестовых процедур и потом только их реализовывать. 
Если вызвает падение, да еще при первом разе, то считаю неправильным оставлять включенным по умолчанию.

**Comment by artbear** [comment]
Информатор не всегда вызывает падение.
У нас старая версия, chessman недавно выкладывал доработку под 8.3.6 в нашей исходной ветке Информатора http://www.1cpp.ru/forum/YaBB.pl?num=1313560540/150
Я ему написал сейчас, попробуем посмотреть, в чем проблема.
Плохо, что вылетает не всегда, а эпизодически :(

**Comment by ValeraS** [comment]
Ещё вариант, сначала пытаться получить тестовые методы через `ТестОбъект.ПолучитьСписокТестов()`, если такого метода не существует и есть информатор, использовать его.

**Comment by artbear** [comment]
К сожалению, такой вариант нельзя использовать.
`ПолучитьСписокТестов` - это метод, обязательный для теста.
А тесты самостоятельно внутри этого метода вызывают спец.метод для получения набора тестов
```
// Получает с помощью Информатора массив тестовых экспортных методов, начинающихся с Тест
// может вызываться из теста из его метода ПолучитьСписокТестов(ЮнитТестирование)
Функция ДобавитьПростыеТестыИзОбъекта(массивТестов, ТестовыйОбъект) Экспорт
```

**Comment by ValeraS** [comment]
Разобрался, просто не надо использовать информатор для определения существования метода `ПолучитьСписокТестов`.

**Comment by artbear** [comment]
На лету Информатор также нельзя подключить, т.к. из особенностей реализации его нужно подключать только в обработчике ПередОткрытием ОФ.

Предлагаю дождаться chessman-а. Может быть, с ним удастся что-то поправить :)
В инструментах разработчика Информатор также юзается, теперь уже и в 8.3.6, там проблем не было.

**Comment by artbear** [comment]
@ValeraS
> Разобрался, просто не надо использовать информатор для определения существования метода `ПолучитьСписокТестов`.

Поясни.

**Comment by ValeraS** [comment]
Это решит проблему, для тех кто не использует `ДобавитьПростыеТестыИзОбъекта`. В случае определения наличия метода `ПолучитьСписокТестов` использование информатора излишне.

**Comment by artbear** [comment]
Как я уже выше написал, Информатор требует загрузки перед открытием тест-раннера.
и тут нужно решать кардинально - как его грузить с сохранением совместимости.

**Comment by artbear** [comment]
А вообще для боевых применений можно удалить xddInformator и тогда вообще проблем с ним не будет :)

**Comment by ValeraS** [comment]
Это понятно, но обращение к информатору в описанном случае, всё равно, убрать нужно.

**Comment by artbear** [comment]
Не уверен в последнем :(
1 проверка через Информатор идет намного быстрее. При загрузке на большом количество файлов или встроенных обработок это критично.
2 Информатор все равно загружен, почему бы им не воспользоваться!

**Comment by ValeraS** [comment]
2. Потому что на этой проверке падает ))

**Comment by artbear** [comment]
Ты смог добиться повторяемости падения?

**Comment by pumbaEO** [comment]
Хм, так может просто перенести обработк информатора в externals и написать простейший bat который скопирует эту обработку, для deploy?

- [x] Win - ОФ 
- [ ] Win - УФ
- [ ] Lin - OФ 
- [ ] Lin - УФ

**Comment by artbear** [comment]
Пока нет инсталлятора, народ пользуется ручным копированием файлов :)
Да и при наличии инсталлятора ручной способ будет рулить, например, для встраивания внутрь конфигурации.

**Comment by ValeraS** [comment]
Сейчас, на win7x64, 1cv8.2.19.121 файловый , падает с завидной постоянностью ))

**Comment by artbear** [comment]
А можешь новую версию Информатора проверить?
http://www.1cpp.ru/forumfiles/Attachments/DWX____________83_epf.7z
Если не сможешь скачать, выложу отдельно.
Будет ли падать также часто?
зы у меня сейчас на домашней машине перестало падать. вчера ночью несколько раз падало. повторяемости нету.

**Comment by ValeraS** [comment]
Ещё быстрее падает ))

**Comment by artbear** [comment]
Ага, я протупил. Оказывается. вчера ночью выключил использование Информатора и падать перестало :)
Сейчас поразбираюсь

**Comment by ValeraS** [comment]
По поводу быстродействия: мне кажется странным решение передавать объект раннера через метод `ПолучитьСписокТестов`, логичнее было его передавать в тестовый метод напрямую. Тогда бы получение тестовых методов происходило только один раз для каждой обработки.

**Comment by artbear** [comment]
Поясни, не понял.

**Comment by ValeraS** [comment]
Сейчас, метод `ПолучитьСписокТестов` вызывается перед каждым выполнением тестового случая, потому что туда передается объект раннера, который сохраняется в переменной модуля тестовой обработки, и потом используется в тестовом методе. (`ТестОбъект.ПолучитьСписокТестов(ЭтотОбъект)`)

А правильным кажется такой вариант `Выполнить("Тест." + ИмяТестовогоСлучая + "(ЭтотОбъект, " + строкаПараметров + ");)"`

**Comment by ValeraS** [comment]
В общем, кажется логичным, во все методы тестовой обработки, вызываемые из раннера, передавать объект раннера.

**Comment by artbear** [comment]
Нет, это нелогично. Зачем в каждый метод передавать этот метод, когда это можно сделать один раз при инициализации?
Сейчас вызов ПолучитьСписокТестов перед выполнением теста нужен для того, чтобы развязать тесты и сделать их независимыми. Для каждого теста создается отдельный экземпляр объекта-обработки. После создания его нужно инициализировать, для этого и вызывается ПолучитьСписокТестов.
У нас есть задача https://github.com/xDrivenDevelopment/xUnitFor1C/issues/253 по отключению независимости тестов.

**Comment by artbear** [comment]
Ну и плюс красота тест.метода пропадет, если ему будет передаваться спец.параметр.
Юзабельность сильно понизится.

**Comment by Ndochp** [comment]
Вот в чем нарушение красоты и гармонии. Функция "ПолучитьСписокТестов"
занимается еще и инициализацией тестовой обработки. Может их развести?

**Comment by artbear** [comment]
Так сделано для упрощения интерфейса тестов и повышения юзабельности.
Инициализация в ПолучитьСписокТестов - это неявная фича :)
я сделал спец.задачу #395 `Методы "ПередЗапускомТестовогоНабора"/"ПослеЗапускаТестовогоНабора" - для запуска перед/после первого/последнего тестов из тестового набора` для реального разделения

**Comment by ValeraS** [comment]
Чем это не логично? С точки зрения ООП, по сути, тестовая обработка это потомок раннера. А дальше можно посмотреть на объекты в python, в каждый метод объекта первым параметром передается экземпляр класса (`self`). Просто у нас это будет не `self` а `super`(родительская часть объекта).

**Comment by artbear** [comment]
В этом вопросе за неявную передачу self/this, как, например, в С++/C#/Java.
С этим синтаксическим сахаром код смотрится намного проще.

**Comment by pumbaEO** [comment]
Согласен с @artbear , вот чего бы не хотелось - это нести с из питона self :( .

**Comment by ValeraS** [comment]
А в результате, инициализация через `ПолучитьСписокТестов`, и медленная работа без информатора.
Хорошо, когда будет сделана задача #395, больше не будет постоянно вызываться `ПолучитьСписокТестов`?

**Comment by ValeraS** [comment]
А зачем каждый раз при выполнении тестов проверять существование метода `ПолучитьСписокТестов`? Его существование было проверено при загрузке.

**Comment by pumbaEO** [comment]
Мы только в ПолучитьСписокТестов можем получить юТест, т.е. или кажый раз передавть объект в процедуру теста self или же каждый раз вызывать ПолучитьСписокТестов, ну или требование в обработке объявлять экспортную переменную и туда явно писать Обработка.юТест = ЭтаФорма.

**Comment by artbear** [comment]
> когда будет сделана задача #395, больше не будет постоянно вызываться ПолучитьСписокТестов?

Метод `ПолучитьСписокТестов` будет вызвать каждый раз при создании тест-объекта. 
Когда будет решена #253, тогда создание будет происходить реже и вызов этого метода автоматически также будет вызываться реже.

>А зачем каждый раз при выполнении тестов проверять существование метода ПолучитьСписокТестов? Его существование было проверено при загрузке.

Оптимизация работы разработчика и повышения юзабельности.
Разработчик может загрузить тесты один раз, а потом просто менять код обработки, изменять набор тестов, менять код тестов и т.п. Хотелось, чтобы все его изменения подхватывались на лету, без необходимости использования кнопки "Перезагрузить".

**Comment by ValeraS** [comment]
Использование информатора для быстродействия в случае определения наличия метода `ПолучитьСписокТестов` какое-то странное. Если у нас куча тестовых обработок, то их имеет смысл хранить отдельно (в папке, в подсистеме) , соответственно у них этот метод будет присутствовать и проверка не нужна. Для большого набора, это ещё быстрее работать будет)).

В тесты из модуля объекта в управляемом режиме, сейчас, не подхватывают изменения. Клиентские тесты переподключаются каждый раз.

**Comment by artbear** [comment]
У ОФ и УФ свои особенности.
В итоге все упирается в использование Информатора.
Нужно решить/договориться, как включать/отключать его использования для новых и существующих пользователей.
остальное это детали/производные от этого решения.

**Comment by artbear** [comment]
Плюс из-за особенностей 1С я лично люблю хранить и тесты, и боевой код в одной обработке, т.к. я работаю по ТДД.

**Comment by artbear** [comment]
@pumbaEO Не нужно эту задачу закрывать, я ее специально переоткрыл вчера для дальнейшего обсуждения.
Договоримся и тогда закрою.
Лады?

**Comment by artbear** [comment]
Еще вариант решения:
для определенных платформ (например, 8.2.19, 8.2.18) для новых ИБ/новых пользователей в интерактивном режиме при запуске раннера в ОФ задавать вопрос о подключении Информатора.

Если пользователь разрешает, то Информатор включается. Если ответ "Нет", то Информатор выключается.

Один минус - вопрос придется задавать в ПередНачаломРаботыСистемы.

Лично мне сейчас этот вариант импонирует больше всего, т.к. на 8.2.17 и 8.3 проблем пока не замечено :(

**Comment by artbear** [comment]
Работы по Информатору уже выполнены.
В случае интерактивного режима вопросы после падения 1С задаются.
Закрываю.
