### ISSUE TITLE
Модальный метод "ПоместитьФайл"

### ISSUE THREAD

**Issue by artross** [xDrivenDevelopment/xUnitFor1C#415]
ОШИБКА загрузки тестов: {Обработка.xddTestRunner.Форма.УправляемаяФорма.Форма(894)}: Ошибка при вызове метода контекста (ПоместитьФайл): Использование модальных окон в данном режиме запрещено!

В конфе отключено использование модального функционала.

**Comment by artbear** [comment]
@ValeraS Народ обновился на релиз 2.7.1.0 и получил проблемы в Такси.
ошибка из-за твоего кода
`	ЕстьПоддержкаАсинхронныхВызовов = (СравнитьВерсии(СистемнаяИнформация.ВерсияПриложения, "8.3.5.1383") >= 0);`

а у народа тесты в режиме Такси на платформе 8.3.4 давно работали, с какой-то из версий 2.6.**
Буду исправлять этот код на 8.3.4

**Comment by artbear** [comment]
Нужно срочно исправлять.

**Comment by artross** [comment]
Асинхронные методы, в том числе "НачатьПомещениеФайла", появились уже в 8.3.3
http://its.1c.ru/db/metod8dev/content/5272/hdoc

**Comment by artbear** [comment]
В общем, в режиме Такси на платформе 8.3.4 (отключена модальность) и 8.3.5 (отключена модальность, но включен режим синхронности расширений и внешних компонент)
тесты работают, если включить проверку не на 8.3.5.1383, а на 8.3.3.0

Пример настройки для 8.3.5 Такси, в которой работают тесты
![image](https://cloud.githubusercontent.com/assets/2920817/6215376/046196ba-b611-11e4-9073-d756db4a8de2.png)

**Comment by artbear** [comment]
А вообще баг случился из-за отсутствия автоматического тестирования для режима Такси, т.к. для автотестирования требуется отдельный файл конфигурации для 8.3 :(
Буду добавлять

**Comment by ValeraS** [comment]
Тогда с 8.3.3641? http://v8.1c.ru/o7/201301nm/

**Comment by artbear** [comment]
Да,  8.3.3.641 меня устраивает.
ЗЫ у тебя опечатка мелкая

**Comment by artbear** [comment]
Исправлено в 2.7.1.6
