### ISSUE TITLE
Не открывается форма тестирования в 8.3.5 с отключенным режимом синхронности расширений и внешних компонент

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#416]
Не открывается форма тестирования в 8.3.5 в режимах Такси, ОФ+УФ с отключенным режимом синхронности расширений и внешних компонент, т.е. с максимальным отключением совместимости
![image](https://cloud.githubusercontent.com/assets/2920817/6215442/b697ee2e-b611-11e4-9d54-7886ae659716.png)

**Comment by artbear** [comment]
Похожая задача #415

**Comment by artbear** [comment]
[Асинхронные вызовы расширений и внешних компонентов - Заметки из Зазеркалья](http://v8.1c.ru/o7/201412async/index.htm)
>Реализовано в версии 8.3.5.1383, планируется в версии 8.3.6.

**Comment by ValeraS** [comment]
На самом деле все гораздо хуже. Режим использования синхронности не зависит от интерфейса. В режиме обычных форм, с отключенным использованием синхронных вызовов, так же открываться не будет.

**Comment by artbear** [comment]
Исправил наименование

**Comment by artbear** [comment]
@karnilaev :
При открытии xddTestRunner'a в тонком клиенте с отключенным режимом использования синхронных вызовов в конфигурации вызывается исключение и форма не открывается.
Если перевести конфигурацию в режим использования синхронных вызовов = Использовать с предупреждениями, то форма открывается с сообщениями "Использование синхронных методов на клиенте запрещено!"

![2015-03-26 17 00 36](https://cloud.githubusercontent.com/assets/5828648/6847747/d8f584fa-d3d9-11e4-89e6-52eb75ee648f.png)

Такое же поведение происходит при нажатии на кнопку "Перезагрузить"

**Comment by artbear** [comment]
Задача выполнена для УФ.
для ОФ создана отдельная задача #503
