### ISSUE TITLE
В xddDataFixtureGen избавиться от использования COMОбъектов

### ISSUE THREAD

**Issue by ValeraS** [xDrivenDevelopment/xUnitFor1C#418]
Необходимо для работы в Linux.

COMОбъект используется только в одном месте (функция ПолучитьИдентификаторИзПредставления_Лкс) для вычисления "регулярок". Данную функцию можно легко переписать без использования regexp-ов.

**Comment by artbear** [comment]
Да, можно исправить.
С помощью нескольких тестов несложно.
