### ISSUE TITLE
Показать время выполнения каждого теста и в сумме по группе тестов в дереве тестов xddTestRunner'a

### ISSUE THREAD

**Issue by Zaidfly** [xDrivenDevelopment/xUnitFor1C#421]
УФ+ОФ: Показать время выполнения каждого теста и в сумме по группе тестов в дереве формы xddTestRunner'a.

**Comment by artbear** [comment]
Народ очень просит.
Тесты стали выполняться долго. Хочется понять, какие тесты занимают основное время.

**Comment by artbear** [comment]
@ValeraS Если задача интересна, посмотришь?
