### ISSUE TITLE
Ошибки выполнения тестов разделить на две группы errors и failures

### ISSUE THREAD

**Issue by ValeraS** [xDrivenDevelopment/xUnitFor1C#433]
Сейчас все ошибки выглядят одинакова, была ли это ошибка проверки или это какая-то не запланированная ошибка. Предлагается ввести две категории ошибок:
errors - не запланированные ошибки
failures - ошибки, возникшие при выполнении проверочных методов.

При формировании отчета в mxl для ошибок failures не выводить служебную информацию (имя модуля, строка модуля и т.д.), так как, в данном случае, эта информация не информативна.

**Comment by artbear** [comment]
Дубль #248
Предлагаю добавить комментарии к указанной задаче.
