### ISSUE TITLE
При загрузке данных из макетов хотелось бы указывать общие параметры создания всех данных из макетов

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#436]
При загрузке данных из макетов хотелось бы указывать общие параметры создания всех данных из макетов
например, загрузка всех данных в режиме ОбменДанными.Загрузка.
Тогда для каждого объекта в макете не нужно генерить дополнительную строку с ОбменДанными.
Например, 
```
СоздатьДанныеПоМакетам(ТестОбъект, ИменаМакетов, Параметры = Неопределено) Экспорт

СоздатьДанныеПоТабличномуДокументу(ТабличныйДокументИлиМассивТабличныхДокументов,
ПараметрыИлиИмяКолонкиЗамещения = Неопределено, ИмяКолонкиЗамещения = Неопределено) Экспорт
```

**Comment by artbear** [comment]
@Zaidfly @Pr-mex что скажете?

**Comment by Zaidfly** [comment]
Зачем? Эти режимы устанавливаются в самом макете для объекта. Генератор данных умеет в макетах проставлять эти режимы при взведенном соответствующем флажке.

**Comment by Pr-Mex** [comment]
У меня, например, при начальном заполнении базы загружается много макетов за раз, и для всех объектов в этих макетах надо выставить режим - ОбменДанными.Загрузка. Нет смысла это прописывать для каждого элемента загрузки.
