### ISSUE TITLE
Коммандная строка CreateAdmin не закрывает предприятие

### ISSUE THREAD

**Issue by pumbaEO** [xDrivenDevelopment/xUnitFor1C#437]
В build плане добавленна команда 
echo "create admin"
"%oneC_root%1cv8.exe" ENTERPRISE /F"%WORKSPACE%\build\ib" /C"AdminCreate" /out"%WORKSPACE%\AdminCreate.txt"

но, т.к. в результате этого экземпляр предприяти 1с не закрывается автоматом, то все тесты останавливаются.

**Comment by artbear** [comment]
У меня все в порядке прошло на домашнем билд-сервере.
Я отключил загрузку из dt и добавил отдельный шаг создания админа.
Ты на ветке девелоп проверяешь?

**Comment by artbear** [comment]
У тебя не задан шаг создания ИБ
У меня на локальном ТимСити работает следующий код
```
echo "create database"
"%oneC_root%1cv8.exe" CREATEINFOBASE  File=%teamcity.build.checkoutDir%\build\ib /Lru /DumpResult "%teamcity.build.checkoutDir%\dump12.txt"  /Out "%teamcity.build.checkoutDir%\log12.txt" /Visible 

echo "update database"
"%oneC_root%1cv8.exe" DESIGNER /F"%teamcity.build.checkoutDir%\build\ib" /Lru /LoadCfg"%teamcity.build.checkoutDir%\Tests\TestConfig.cf" /UpdateDBCfg /DisableStartupMessages  /DumpResult"%teamcity.build.checkoutDir%\dump14.txt"  /Out"%teamcity.build.checkoutDir%\log14.txt" /Visible 

echo "create admin"
"%oneC_root%1cv8.exe" ENTERPRISE /F"%teamcity.build.checkoutDir%\build\ib\" /C"AdminCreate" /outAdminCreate.txt
```
Проверишь?
Если все успешно, задачу закроешь?

**Comment by artbear** [comment]
Как-то оно странно.
Дома все работает, на работе на 8.2.19 сработало, а дальше начало опять висеть :(
Буду разбираться.

**Comment by artbear** [comment]
@ValeraS также посмотришь? что не так?

**Comment by artbear** [comment]
Ага, все понятно. В ветке issue_248 не было мержа с правками из девелоп, куда были залиты доработки для `AdminCreate`
Исправил. залив в ветку origin\issue_248.
Тесты перестали зависать

**Comment by artbear** [comment]
@pumbaEO Закрываем issue ?
