### ISSUE TITLE
Запущено тестов: 1, из них упало - 2

### ISSUE THREAD

**Issue by artross** [xDrivenDevelopment/xUnitFor1C#438]
Вот такой забавный баг. Появляется, когда тест падает, плюс в нем же возникает ошибка отмены транзакции.

![default](https://cloud.githubusercontent.com/assets/9880207/6372438/48d2c8ae-bd15-11e4-9211-d4c2b438e15e.png)

Заодно можно привести выделенное сообщение к единому формату, а то после "запущено" стоит "двоеточие", а после "упало" - "тире" :)

**Comment by ValeraS** [comment]
В данном случае, баг заключается в том, что заголовок некорректно отражает суть происшедшего?

Предлагаю такой заголовок:
Запущено тестов - N, не прошло проверку - F, возникло ошибок - E, пропущено - S

Для приведенного примера:
Запущено тестов - 1, не прошло проверку - 1, возникло ошибок - 1, пропущено - 0

**Comment by artbear** [comment]
Согласен.
Но у тебя в итоге опять запущен 1 тест, а ошибки 2 :)
Должен выполняться инвариант "не прошло проверку + возникло ошибок + пропущено" == "запущено тестов"

**Comment by ValeraS** [comment]
Не согласен, и данный пример это показывает.
Инвариант, вообще то, в идеале "прошло проверку + не прошло проверку + пропущено" == "запущено тестов", а вот с ошибками сложнее, они могут возникнуть как в самом тесте, так и перед/после теста (как в примере).

**Comment by artbear** [comment]
ИМХО указывать нужно как одну ошибку, а вот показывать ее в описании полностью, т.е. описание от 2х ошибок. 
Понятно написал? :)

**Comment by ValeraS** [comment]
И куда же её зачислять в `failures` или `errors`

В примере, тест не прошел проверку, а потом, при выполнении `ПослеЗапускаТеста`, возникло исключение (что является ошибкой написания теста).

Вообще, если количество `errors > 0`, то это либо некорректно написаны тесты, либо ошибка фреймворка.

ИМХО, нужно указывать в итоге именно 2 ошибки.

**Comment by artbear** [comment]
Я также считаю, что все ошибки нужно показать.
тогда предлагаю писать
Запущено тестов - 1, не прошло проверку - 0, возникло ошибок - 1, пропущено - 0
возникло доп.ошибок - 1

**Comment by ValeraS** [comment]
Вообще то, для примера в твоем варианте записи, должно быть так:
Запущено тестов - 1, не прошло проверку - 1, возникло ошибок - 0, пропущено - 0
возникло доп.ошибок - 1

и тогда становится непонятно, почему эту доп. ошибку не указать просто в ошибку?

**Comment by ValeraS** [comment]
Может, просто, `возникло ошибок` перенести в отдельную строку.

**Comment by artbear** [comment]
Лады.
Запущено тестов - 1
Возникло ошибок - 2

**Comment by ValeraS** [comment]
@artbear давай ещё раз:)
Есть два вида ошибок:
1 Ошибка в проверяемом функционале (т.е. сработал assert)
2. Все остальные ошибки (ошибки в модуле теста, в раннере и .т.д.)

В xml отчет будет выводится `failures=#(1) errors=#(2)`.
В mxl предлагается выводить аналогично:
`не прошло проверку - #(1), возникло ошибок - #(2)`
 или все таки хочешь не разбивать по типам ошибок:
`возникло ошибок - #(1) + #(2)`?

**Comment by artbear** [comment]
Лады. согласен. 
код посмотрю попозже

**Comment by e-mc2** [comment]
В версии 2.8.0.1 (обычный приложение), если запускаю не все тесты, а только определенную группу (через контекстное меню) или один тест, в случае падения теста(-ов) в отчете выводится: "Запущено тестов: 0" (как было описано выше)

**Comment by artbear** [comment]
Подтверждаю.
@ValeraS поправишь?

**Comment by ValeraS** [comment]
@artbear Формально, эта ошибка не относится к этому обсуждению. Она существовала за долго до изменений внесенных в 2.8.0.1. Связана с тем, что в обычной форме код выполняющий все тесты и только выбранные дублирует друг друга. И во втором случае, забыли про счетчик запущенных тестов. Есть два варианта, просто добавить подсчет запущенных тестов или провести рефакторинг кода.

**Comment by artbear** [comment]
@ValeraS Лучше, конечно, с исключением дублирования сделать.

**Comment by artbear** [comment]
Выполнено.
