### ISSUE TITLE
При загрузке тестов и возникновении платформенной ошибки браузер тестов не открывается.

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#442]
При загрузке тестов и возникновении платформенной ошибки браузер тестов не открывается.
Ошибка описана в [Вики - Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8)

Если после этого закрыть браузер или завершить Предприятие и заново запустить, то далее не удается открыть браузер тестов, т.к. браузер пытается открыть снова эти же тесты, 1С вылетает, не возвращая управление браузера :(
Для пользователя это выглядит, что браузер тестов не открывается :(

Пример теста - в коде тестового метода достаточно написать
`А = Новый НеизвестныйТип();`

Я нарвался на подобное поведение, когда запустил 1С:Предприятие 8.3.4 без ключа "/TESTMANAGER" и попытался открыть чужие тесты под GUI-тестирование 8.3.
```
&НаКлиенте
Процедура ПриОткрытии(Отказ)
	Подопытный = Новый ТестируемоеПриложение(,"1577");
КонецПроцедуры
```

**Comment by ValeraS** [comment]
@artbear А почему проверку на наличие ошибки переделали на файл, чем не устроило ХранилищеОбщихНастроек?

**Comment by artbear** [comment]
@ValeraS Реально данные из хранилища записываются во внешние файлы настроек только при штатном закрытии 1С. При нештатном падении 1С никакой записи не происходит, поэтому хранилищем пользоваться нельзя. В итоге только внешний файл остается.

Сейчас положу этот коммент в код, чтобы больше вопросов у народа не возникало.

**Comment by ValeraS** [comment]
@artbear В Linux не работает.  Ещё, это исправление не будет работает при отключенном использовании модальности(Вопрос - ПоказатьВопрос).

**Comment by artbear** [comment]
@ValeraS Линукса нет, проверить не могу и потому все равно про него забываю :(
По модальности я помню. 
@ValeraS если можешь исправить обе или одну ошибки, исправь, пожалуйста.
Жду ответа.

**Comment by ValeraS** [comment]
@artbear Сейчас, попробовал следующее, загрузил в раннер произвольный тест, установил точку останова после сохранения настроек (которое при закрытии формы), попал на эту точку останова, убил сеанс предприятия (через диспетчер задач), запустил снова, настройки сохранились. Что я делаю не так?))
Сейчас могу проверить только на Linux под 8.3.6.

**Comment by artbear** [comment]
@ValeraS 1. Возможно, в Линукс реализовано по-другому.
2. Нужно ронять 1С на этапе загрузки тестов, когда тесты еще не загрузились. Например, сразу после вызова метода УстановитьНастройку_БылаОшибкаПриПредыдущейЗагрузке(Истина)
3. Ты проверяешь УФ или ОФ ?

**Comment by artbear** [comment]
@ValeraS Да, дополнительно проверил сохранение настроек в хранилище общих настроек и падение 1С.
Все сохраняется. 
Странно, ведь по опыту знаю, что не все настройки, сделанные в текущем сеансе, сохраняются при падении этого сеанса.
Буду исправлять.
