### ISSUE TITLE
Статусы выполнения юнит-тестов не различимы для дальтоников

### ISSUE THREAD

**Issue by karnilaev** [xDrivenDevelopment/xUnitFor1C#448]
Я, как дальтоник, не могу понять, выполнился юнит-тест с ошибкой, или без, из-за того, что красный кружок и зеленый кружок для меня практически идентичны.
Предлагаю красный кружок исправить на красный крестик. Так дальтоники смогут отличить "хорошие" тесты от "плохих"

**Comment by artbear** [comment]
На крестик согласен.
Я давно хочу немного доработать интерфейс в плане повышения юзабилити.
Для тестов, которые были пропущены, можно еще какой-нибудь значок поставить (например, пауза или квадрат/стоп)

**Comment by artbear** [comment]
Жду пулл-реквест

**Comment by artbear** [comment]
Выполнено.

**Comment by karnilaev** [comment]
Спасибо! Я пока не понял как правильно пул-реквесты делать. Точнее не понял, как обновить свой форк до состояния оригинального репозитария. Как только разберусь, буду присылать правильные пул-реквесты )

**Comment by artbear** [comment]
Тебе нужно добавить ещё один remote/origin для своего локального репо. 1й
remote указывает на твой форк, второй на основной репо хЮнит на Гитхабе.
Затем делаешь pull со второго репо и получаешь к себе наши изменения

**Comment by xdd-ci-admin** [comment]
Если изменения небольшие можешь просто у себя fork удалить и потом сделать
форк заново. Обработку при этом можешь сохранить и потом сделать
сравнение/объединение внешних обработок.

Можно по инструкции github
http://stackoverflow.com/questions/7244321/how-to-update-github-forked-repository


20 марта 2015 г., 9:18 пользователь karnilaev <notifications@github.com>
написал:

> Спасибо! Я пока не понял как правильно пул-реквесты делать. Точнее не
> понял, как обновить свой форк до состояния оригинального репозитария. Как
> только разберусь, буду присылать правильные пул-реквесты )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xDrivenDevelopment/xUnitFor1C/issues/448#issuecomment-83942162>
> .
>



-- 
Сосна Евгений Викторович
mail:shenjasosna@gmail.com

**Comment by karnilaev** [comment]
Спасибо большое. Разобрался! :)
