### ISSUE TITLE
Добавить кнопку "выполнить выбранные тесты" на форму раннера

### ISSUE THREAD

**Issue by Ndochp** [xDrivenDevelopment/xUnitFor1C#451]
У меня довольно частый сценарий - создать по одному файлу на объект метаданных и при возникновении требований написать тест сразу под требуемое поведение. Так как в большинстве случаев я работаю отчетами, то делаю их внешними файлами и регулярно что-то правлю, сохраняю и сразу жму кнопку выполнить тест в предприятии. В большинстве случаев новый тест упадет, а я смотрю, чтобы он упал как задумывалось. При этом мне нужен только один тест, а полный контроль по этому объекту я запускаю только когда перехожу к другому участку кода.
В итоге, на десяток нажатий "выполнить выбранное" у меня приходится одно "выполнить все тесты". Не думаю, что я сильно уникален, так что предлагаю добавить пятую кнопку в шапку ранера.

**Comment by pumbaEO** [comment]
А если 2 раза левой клавишей мыши = запуск теста сделать?

**Comment by artbear** [comment]
Да, сам об этом давно думаю, т.к. также часто пользуюсь именно разработкой отдельного теста или набора тестов.
Мышкой неудобно, лучше всего по хоткею типа Альт+Ф7

**Comment by pumbaEO** [comment]
Enter?

**Comment by artbear** [comment]
А Энтер для строки дерева это какое событие? выбор?
Удобно для старожилов, но не очень юзабельно для новичков.
Все-таки отдельная кнопка юзабельна.
ИМХО нужно оба варианта сделать - и Энтер и кнопка

**Comment by artbear** [comment]
ОФ+УФ: Добавлен хоткей Ctrl+Enter на кнопку "выполнить выделенные" на форме браузера тестов
