### ISSUE TITLE
ОФ+УФ: Добавить контекст для использования разными тестами

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#453]
ОФ+УФ: Добавить контекст для использования разными тестами
Интерфейс:
`процедура УстановитьКонтекст(Контекст, ИдентификаторКонтекста = Неопределено)`
`функция ПолучитьКонтекст(ИдентификаторКонтекста = Неопределено)`

В дополнение к задачам о зависимости/независимости тестов #249 и #253

в ОФ контекст может быть любым, в т.ч. и несериализуемым.
в УФ контекст должен быть только сериализуемым.

**Comment by pumbaEO** [comment]
Это в xddRunner экспортные процедуры?

**Comment by artbear** [comment]
в ОФ контекст может быть любым, в т.ч. и несериализуемым.
в УФ контекст должен быть только сериализуемым.

**Comment by artbear** [comment]
Да, конечно, это интерфейс хЮнит, т.е. экспортные методы.

**Comment by pumbaEO** [comment]
:+1:

**Comment by artbear** [comment]
https://github.com/xDrivenDevelopment/xUnitFor1C/issues/253#ref-commit-139823d

**Comment by artbear** [comment]
Также для УФ нужно сделать работающими серверные тесты взаимных зависимостей тестов через контекст
