### ISSUE TITLE
Ошибка при загрузке тестов

### ISSUE THREAD

**Issue by part1zan** [xDrivenDevelopment/xUnitFor1C#458]
![image](https://cloud.githubusercontent.com/assets/2269427/6779839/1f6117f8-d171-11e4-9f73-5a55d9360f69.png)
Платформа 8.3.5.1460, УФ

**Comment by part1zan** [comment]
Забирал из master-ветки

**Comment by xdd-ci-admin** [comment]
В мастере версия 2.8.0.0

На другой платформе не пробовали? У меня на 8.3.6 все ок и на 8.3.5.1383
тоже все нормально.
23 марта 2015 г. 14:29 пользователь "Alexey" <notifications@github.com>
написал:

**Comment by artbear** [comment]
Разобрались. 
Конфигурация, в которой запускаются тесты, не умеет пропускать "чужие" оповещения.
А xUnitFor1C пользуется оповещениями в УФ.
Нужно исправлять конфигурацию, а именно код обработки оповещений. 

Рекомендую глобальный поиск по `ПодключитьОбработчикОповещения ` и доработку кода всех найденных обработчиков оповещений.

**Comment by artbear** [comment]
Документировал проблему в [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8)
Закрываю.

**Comment by IvanSub** [comment]
Старая проблема находили давно у нас на проекте. Обрабатывали чужеродные оповещения.
