### ISSUE TITLE
xddTestRunner УФ не открывается с отключенным режимом использования синхронных вызовов

### ISSUE THREAD

**Issue by karnilaev** [xDrivenDevelopment/xUnitFor1C#468]
При открытии xddTestRunner'a в тонком клиенте с отключенным режимом использования синхронных вызовов в конфигурации вызывается исключение и форма не открывается.
Если перевести конфигурацию в режим использования синхронных вызовов = Использовать с предупреждениями, то форма открывается с сообщениями "Использование синхронных методов на клиенте запрещено!"

![2015-03-26 17 00 36](https://cloud.githubusercontent.com/assets/5828648/6847747/d8f584fa-d3d9-11e4-89e6-52eb75ee648f.png)

Такое же поведение происходит при нажатии на кнопку "Перезагрузить"

**Comment by karnilaev** [comment]
Проверил на версии обработки 2.8.0.27 - поведение такое же.

**Comment by artbear** [comment]
Уже есть такая задача #416
Закрываю.

**Comment by karnilaev** [comment]
Спасибо, искал, но не нашел. Буду лучше искать в будущем.
