### ISSUE TITLE
Выбор лицензии

### ISSUE THREAD

**Issue by allustin** [xDrivenDevelopment/xUnitFor1C#476]
для включения накопленных тестов и обработки тестирования в поставку совместно с Конфигурацией для лицензионной чистоты необходимо указать third party license, а её нет.

Продукты без явной лицензии по ГК РФ опасно включать в поставку, можно нарваться.

Поэтому прошу в корень репозитория добавить файл LICENSE.md

**Comment by pumbaEO** [comment]
Я за Apache 2.0.

**Comment by allustin** [comment]
Я тоже за Apache 2.0.

**Comment by artbear** [comment]
Добавлю в ближайшие дни лицензию.
@kuntashov Что скажешь? ты за какую лицензию?

**Comment by kuntashov** [comment]
Если бы мы сейчас только начинали, я бы выбрал GPL, т.к. она требует распространять сделанные доработки. Но поскольку над xUnit уже давно трудятся команды других организаций, это будет выглядеть как нападение на их закрытые разработки на базе xUnit.

Так что да, поддержу Apache 2.0.
