### ISSUE TITLE
ОФ 8.3 тесты запускаются дважды при отключенной модальности и совместимости 

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#479]
Интерактивно запускаю все тесты генератора данных - **в 8.3 ОФ при включенных режимах из #477**! (файл TestConfig-Taxi83.cf)
по окну сообщений вижу, что тесты запускались дважды :(

![image](https://cloud.githubusercontent.com/assets/2920817/6969427/3b5aa4f2-d977-11e4-81e4-9af219efd689.png)

**Comment by ValeraS** [comment]
Воспроизведение ошибки не зависит от модальности и режима совместимости.
