### ISSUE TITLE
Возможность создавать узлы Плана обмена при генерации тестовых данных

### ISSUE THREAD

**Issue by bf0rce** [xDrivenDevelopment/xUnitFor1C#481]
Делаю интеграционный тест выгрузки из базы 1С во внешний источник SQL-запросами. В структуре выгружаемых данных присутствуют ссылки на узлы Плана обмена. На данный момент создать их из макета с тестовыми данными невозможно.
Собираюсь дорабатывать такую возможность для себя.

**Comment by artbear** [comment]
Буду ждать пулл-реквест с реализацией.

**Comment by bf0rce** [comment]
В инструкции не указано чем "разбирать" обработки на исходники. Я этого делать не должен?

**Comment by artbear** [comment]
Нужно использовать подход из проекта precommit1c
