### ISSUE TITLE
Не проходит тест "Протестить несколько успешных встроенных тестов в отдельном сеансе пользователя..."

### ISSUE THREAD

**Issue by bf0rce** [xDrivenDevelopment/xUnitFor1C#482]
После коммита 7496cce стали падать 3 теста из набора Tests_CmdLine.
"[Failed] Сравниваемые значения (2; 1) не равны, а хотели, чтобы были равны.
Ожидали, что пройдут тесты (2шт), а остальные упадут, а получили <1> прошедших тестов."

**Comment by artbear** [comment]
Уже есть #465 
Закрываю.

**Comment by artbear** [comment]
@bf0rce Извини, я рано закрыл, здесь другая проблема, не связанная с #465

**Comment by artbear** [comment]
Твоя проблема у меня не подтверждается.
Вот результаты на разных платформах
В ветке девелоп проблемы только с 8.3 Такси/Модальность и 8.3.4 (там проблемы с COM при установленном 8.3.5)
"Твоих" падений нет.
![image](https://cloud.githubusercontent.com/assets/2920817/7020306/a09058c4-dd20-11e4-9534-726f6f90e3b0.png)

@bf0rce Рассказывай подробнее, какая платформа 1С, какой режим 1С запускаешь(ОФ/УФ, тонкий/толстый), если 8.3, то настройки (Такси, совместимость, модальность и т.п.)

**Comment by bf0rce** [comment]
Нет, все-таки дублирует #472. Коммит 4d1a6dc все исправил.
Спасибо. Буду чаще обновляться.

**Comment by artbear** [comment]
Закрываю.
