### ISSUE TITLE
Тестовые обработки должны загружаться в определенном порядке - по возрастанию имени файла

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#484]
Тестовые обработки должны загружаться в определенном порядке - по возрастанию имени файла

**Comment by artbear** [comment]
Сейчас этот порядок нарушается, если загружать произвольные файлы-тест.обработки и в окне выбора файлов используется сортировка, отличная от сортировка "возрастание по имени файла"

**Comment by acsent80** [comment]
также нарушается, если выделить несколько тестов и запустить выделенные
