### ISSUE TITLE
Выгрузка планов обмена из ИБ в макет данных

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#486]
Выгрузка планов обмена из ИБ в макет данных (в xddDataFixtureGen)
Загрузка из макета уже реализована в #481

**Comment by bf0rce** [comment]
Я возьмусь

**Comment by artbear** [comment]
Отлично. Буду ждать реализации.

**Comment by artbear** [comment]
Выполнено.
