### ISSUE TITLE
Ошибка при создании макета данных документа. 

### ISSUE THREAD

**Issue by asheichenko** [xDrivenDevelopment/xUnitFor1C#493]
При создании макета данных документа, если стоит галочка "Выгружать с документом все его движения" выскакивает ошибка
![default](https://cloud.githubusercontent.com/assets/8320910/7472718/219df5c4-f33e-11e4-80cb-5cc4894440c9.PNG)

Не учитывается КорневойТипКонфигурации в строке 490 модуля объекта обработки xddDataFixtureGen.epf

**Comment by Ndochp** [comment]
Кажется та же тема, что была в  #422
Для небалансовой штуки будет валютная сумма Дт и Кт

**Comment by asheichenko** [comment]
Да, но только в #422 это описано для измерений, а это проявляется при небалансовом ресурсе.

**Comment by asheichenko** [comment]
Вроде там не сложно, попробую заняться исправлением.
