### ISSUE TITLE
Неверное определение типа реквизита при генерации макета

### ISSUE THREAD

**Issue by asheichenko** [xDrivenDevelopment/xUnitFor1C#496]
Если у реквизита тип - ПеречислениеСсылка и он не заполнен, то тип определяется как ПеречислениеСсылка.  См. СубконтоКтНУ2. 
![default](https://cloud.githubusercontent.com/assets/8320910/7498562/7641480a-f42a-11e4-8aca-7774a4751e48.PNG)

Затем, при попытке протестировать загрузку выдает ошибку.

**Comment by asheichenko** [comment]
Далее при исправлении получения типа, начинает вылетать при получении значения перечисления в этом коде
<code>
			Если Режим = "ПРЕДОПРЕДЕЛЕННЫЙ" Тогда
				Значение = менеджерОбъекта[стрПоле.Значение];
			ИначеЕсли Режим = "КОД" Тогда
				Значение = менеджерОбъекта.НайтиПоКоду(стрПоле.Значение);
			ИначеЕсли Режим = "НОМЕР" Тогда
				Значение = НайтиБлижайшийДокументПоНомеру(МетаданныеТипаРеквизита, стрПоле.Значение);
			ИначеЕсли Режим = "НАИМЕНОВАНИЕ" Тогда
				Значение = менеджерОбъекта.НайтиПоНаименованию(стрПоле.Значение, Истина);
			ИначеЕсли Режим = "ГУИД" Тогда
				Значение = менеджерОбъекта.ПолучитьСсылку(Новый УникальныйИдентификатор(стрПоле.Значение));
			Иначе
				ВызватьИсключение "НеверныйРежимПоиска: Не поддерживаемый режим поиска. Реквизит <"+стрПоле.Имя+">: Искали значение <"+стрПоле.Значение+">";
			КонецЕсли;

</code>
Думаю, если стрПоле.Значение не заполнено, надо получать пустую ссылку.
Вопрос, надо ли создавать тест на этот случай?

**Comment by artbear** [comment]
Пока сложно сказать, покажи, как хочешь поменять.
ЗЫ поправил твой код для правильного просмотра, посмотри.

**Comment by asheichenko** [comment]
Вот так изменил, вроде заработало
<code>
			Если Режим = "ПРЕДОПРЕДЕЛЕННЫЙ" Тогда
				Если ЗначениеЗаполнено(стрПоле.Значение) Тогда
					Значение = менеджерОбъекта[стрПоле.Значение];
				Иначе
					Значение = менеджерОбъекта.ПустаяСсылка();
				КонецЕсли;
			ИначеЕсли Режим = "КОД" Тогда
				Значение = менеджерОбъекта.НайтиПоКоду(стрПоле.Значение);
			ИначеЕсли Режим = "НОМЕР" Тогда
				Значение = НайтиБлижайшийДокументПоНомеру(МетаданныеТипаРеквизита, стрПоле.Значение);
			ИначеЕсли Режим = "НАИМЕНОВАНИЕ" Тогда
				Значение = менеджерОбъекта.НайтиПоНаименованию(стрПоле.Значение, Истина);
			ИначеЕсли Режим = "ГУИД" Тогда
				Значение = менеджерОбъекта.ПолучитьСсылку(Новый УникальныйИдентификатор(стрПоле.Значение));
			Иначе
				ВызватьИсключение "НеверныйРежимПоиска: Не поддерживаемый режим поиска. Реквизит <"+стрПоле.Имя+">: Искали значение <"+стрПоле.Значение+">";
			КонецЕсли;			
			Если ЗначениеЗаполнено(стрПоле.Значение) И Не ЗначениеЗаполнено(Значение) Тогда
				ВызватьИсключение "ЗначениеНеНайдено: Реквизит <"+стрПоле.Имя+">: Искали значение <"+стрПоле.Значение+">, но не нашли!";
			КонецЕсли;
</code>

**Comment by artbear** [comment]
Пожалуйста, Исправь код по образцу выше.
Иначе читать невозможно :(

**Comment by asheichenko** [comment]
Не совсем понял как это сделать и где образец, у меня выше так же код отображается.
![default](https://cloud.githubusercontent.com/assets/8320910/7515400/5bb425f2-f4cf-11e4-9c6f-ed94839d70cc.PNG)

**Comment by artbear** [comment]
Ага, так нормально

**Comment by artbear** [comment]
>Далее при исправлении получения типа

@asheichenko Дай код исправления получения типа в xddTestRunner
