### ISSUE TITLE
Выгрузка и загрузка регистров расчета в генераторе макета данных

### ISSUE THREAD

**Issue by asheichenko** [xDrivenDevelopment/xUnitFor1C#500]
Не нашел в открытых задачах, хотя есть закомментированный код. В данный момент не реализована выгрузка из ИБ и загрузка регистров расчета в обработке xddDataFixtureGen.

**Comment by artbear** [comment]
Уже выполнено, есть в ветке develop.
@asheichenko Проверишь?

**Comment by asheichenko** [comment]
Только увидел PR. Да попробую.
