### ISSUE TITLE
предопределенное имя лога JUnit

### ISSUE THREAD

**Issue by EvilBeaver** [xDrivenDevelopment/xUnitFor1C#502]
В xunit предопределенное имя лога "лог\_тестирования.xml". Если в сценарии сборки под TeamCity xUnit запускается несколько раз, то обработчик отчетов JUnit видит, что файл "лог\_тестирования.xml" он уже обрабатывал и второй раз его в обработку не берет.

Сценарий:

* Запустили xUnit для первичного наполнения тестовыми данными - создался файл "лог_тестирования.xml"
* Запустили xUnit второй раз, для прогона тестов - перезаписался файл "лог_тестирования.xml"
* TeamCity парсит отчет "лог_тестирования.xml" только от первого запуска, а второй игнорирует.

Нужно как-то управлять именем формируемого отчета JUnit

**Comment by ValeraS** [comment]
Так это уже есть (из wiki):
xddReportPath / Тесты_Команда_КаталогОтчетов : указывается каталог для сохранения отчетов тестирования или `путь к файлу отчета тестирования`

**Comment by EvilBeaver** [comment]
Да, действительно :)
