### ISSUE TITLE
Реализация плагинов/расширений

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#505]
Переход на плагины.
Архитектура и реализация разрабатывается в режиме парного программирования - @wizi4d (Евгений Павлюк) и @artbear (Артур Аюханов)

Фото базовой архитектуры (чертеж на доске для рисования)
![image](https://cloud.githubusercontent.com/assets/2920817/7799689/e8091ec2-0311-11e5-883b-73ebba68ec42.png)

**Comment by artbear** [comment]
Ветка разработки [feature/plugins](https://github.com/xDrivenDevelopment/xUnitFor1C/commits/feature/plugins)

**Comment by pumbaEO** [comment]
А api какое ? Т.е. смогу ли я своим plugin подключиться и
зарегистрироваться на обработку событий n и m?

2015-05-25 19:17 GMT+03:00 Artur Ayukhanov <notifications@github.com>:

> Ветка разработки feature/plugins
> <https://github.com/xDrivenDevelopment/xUnitFor1C/commits/feature/plugins>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xDrivenDevelopment/xUnitFor1C/issues/505#issuecomment-105259595>
> .
>



-- 
З повагою Сосна Євген,
mailto:shenja@sosna.zp.ua
skype:shenjasosna
+380933897103

**Comment by wizi4d** [comment]
Идея в том, что выделены разновидности плагинов, каждая разновидность со своим API.
Пока видятся следующие разновидности плагинов:
* Загрузчик
* ГенераторДанных
* ГенераторОтчетов

Программный интерфейс пока в разработке и может меняться. Ниже то, что уже есть.

Общий программный интерфейс для всех разновидностей:
* ОписаниеПлагина() - возвращает структуру со свойствами Тип (разновидность плагина), Идентификатор, Представление. Доступен на сервере и на клиенте.
* УстановитьЯдро(НовоеЯдро) - передача основного контекста тестового фреймворка, где НовоеЯдро - Объект для сервера и толстого клиента и Форма для тонкого клиента. Доступен на сервере и на клиенте.
* ПолучитьЯдро() - получает основной контекст тестового фреймворка из плагина (пока только для тестов нужен, может в дальнейшем будет полезное применение). Доступен на сервере и на клиенте.

API загрузчика:
* УстановитьПуть(Путь) - для программной установки пути с тестовыми обработками, где Путь - строка. Доступен на сервере и на клиенте.
* ВыбратьПутьИнтерактивно() - показ некого интерфейса для интерактивного выбора пути. Доступен только на клиенте.
* ПолучитьПуть() - получить установленный в загрузчике путь. Доступен на сервере и на клиенте.
* Загрузить() - построить дерево тестов в формате, который понимает Раннер (методы для построения дерева доступны в ядре). Доступен на сервере и на клиенте.

**Comment by wizi4d** [comment]
Мне оказалось проще временно сделать отдельный репо и вести разработку там.
Отслеживать можно по ссылке https://github.com/wizi4d/xUnitFor1C_2
Когда будет готово, вольем в основное хранилище.

**Comment by ValeraS** [comment]
За изменениями по ссылке не удобно следить, так как, при коммитах, помещаемые обработки не разбираются на файлы. Для удобства отслеживания изменений, просьба, разбирать обработки на файлы, как это делается здесь.

**Comment by artbear** [comment]
Разработка переведена в основной репозитарий

Вся история из отдельного репозитария перенесена в специальную ветке [develop_v4_reborn](https://github.com/xDrivenDevelopment/xUnitFor1C/commits/develop_v4_reborn).

Заведены отдельные issue по вехам [4.0.0.0](https://github.com/xDrivenDevelopment/xUnitFor1C/milestones/4.0.0.0) и [4.Х.0.0](https://github.com/xDrivenDevelopment/xUnitFor1C/milestones/4.%D0%A5.0.0)

Закрываю текущую задачу.
