### ISSUE TITLE
Как пользоваться наборами тестов

### ISSUE THREAD

**Issue by a-sitnikov** [xDrivenDevelopment/xUnitFor1C#508]
Как объединять тесты в набор?

**Comment by artbear** [comment]
1 Шаги/тесты одного сценария объединяем в одной обработке тестирования (внешней/встроенной).

- Эта обработка фактически и является набором.

2 Реализуем функцию `РазрешенСлучайныйПорядокВыполненияТестов`, в ней возвращаем Ложь. 

- В этом случае тесты всегда будут запускаться в том порядке, который задан при добавлении тестов в методе `ПолучитьСписокТестов`

3 Для методов начала и завершения тестового сценария можно использовать один из вариантов:

- реализовать методы `ПередЗапускомТестовогоНабора` / `ПослеЗапускаТестовогоНабора`
  - рекомендуется

- использовать первый и последний тесты (по порядке добавления тестов в `ПолучитьСписокТестов`).
  - не рекомендуется, т.к. возможны ошибки выполнения сценария
    - например. если в первом шаге/тесте будут ошибки, все остальные шаги/тесты будут выполнены

**Comment by artbear** [comment]
Смотри [Пример такого тестового набора](https://github.com/xDrivenDevelopment/xUnitFor1C/blob/develop/src/Tests/selftests/_1%D0%A2%D0%B5%D1%81%D1%82%D0%A2%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D0%B9%D0%9D%D0%B0%D0%B1%D0%BE%D1%80/ObjectModule.txt)

**Comment by artbear** [comment]
Также можно объединять несколько тестовых обработок в единый сценарий, использующих единый контекст и выполняющиеся последовательно.
Примеры таких обработок  - [первый сценарий - УстановитьКонтекст](https://github.com/xDrivenDevelopment/xUnitFor1C/blob/develop/src/Tests/selftests/_1%D0%A2%D0%B5%D1%81%D1%82%D0%94%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C%D0%9A%D0%BE%D0%BD%D1%82%D0%B5%D0%BA%D1%81%D1%82/Form/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0.txt) и [следующий сценарий - ПолучитьКонтекст](https://github.com/xDrivenDevelopment/xUnitFor1C/blob/develop/src/Tests/selftests/_2%D0%A2%D0%B5%D1%81%D1%82%D0%94%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C%D0%9A%D0%BE%D0%BD%D1%82%D0%B5%D0%BA%D1%81%D1%82/ObjectModule.txt)

**Comment by acsent80** [comment]
Получается, что тестовый набор - он внутри одной обработки?

**Comment by artbear** [comment]
Это желательно, но не обязательно.
И несколько обработок могут выступать в виде одного набора

**Comment by artbear** [comment]
>А если один тест выпадет, прервется ли выполнение набора?

Нет, пока реализован прогон всех тестов.
Над прерыванием набора тестов нужно будет еще поработать.

**Comment by ValeraS** [comment]
>> А если один тест выпадет, прервется ли выполнение набора?

>Нет, пока реализован прогон всех тестов.
>Над прерыванием набора тестов нужно будет еще поработать.

Данное поведение можно реализовать в самих тестах используя `Контекст`. При выполнении каждого последующего теста из набора проверять, что предыдущий тест установил правильный контекст. Если контекст не тот, то ронять тест с соответствующим сообщением об ошибке.

**Comment by artbear** [comment]
Задокументировал в [Вики](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%A1%D0%B2%D1%8F%D0%B7%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D0%BD%D0%B0%D0%B1%D0%BE%D1%80%D1%8B-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D0%B5-%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8-%D0%B2-%D0%B2%D0%B8%D0%B4%D0%B5-%D1%81%D0%B2%D1%8F%D0%B7%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D1%88%D0%B0%D0%B3%D0%BE%D0%B2-%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D1%8F)

**Comment by artbear** [comment]
@ValeraS +1 по Контексту

**Comment by acsent80** [comment]
Процедура ПередЗапускомНабораТестов() Экспорт
	юТест.УстановитьКонтекст(Истина, "Контекст");
КонецПроцедуры

Процедура ПередЗапускомТеста() Экспорт
	Контекст = юТест.ПолучитьКонтекст("Контекст");
	юТест.ПроверитьРавенство(Контекст, Истина, "Не получен контекст");
КонецПроцедуры

Такой вариает подойдет?

**Comment by artbear** [comment]
Я выше давал примеры связанных обработок, там как раз контекст все разруливается.

`юТест.ПолучитьКонтекст("Контекст");` сразу выдаст исключение, если такого контекста нет.

Для проверки наличия контекста лучше пользоваться методом `КонтекстУстановлен(Идентификатор) `
Этот метод пока реализованы в ветке соседнего форка 741f7be545b0126a6dae961b80c1f0699c7afb45
Доработки скоро будут загружены в основной ствол, ветку девелоп

**Comment by acsent80** [comment]
Сам понял, что не подойдет. Ошибки теста не сбрасывают контекст.
Тогда неплохо бы иметь событие ПриОшибкеТеста

**Comment by ValeraS** [comment]
Проверять, что тест завершился с ошибкой можно в `ПослеЗапускаТеста` используя метод `ДанныеТекущегоТеста`, и там же удалять контекст.
А вообще, все контексты нужно очищать в `ПередЗапускомТестовогоНабора`.

**Comment by artbear** [comment]
или `ПередЗапускомТеста` проверять состояние теста через `ДанныеТекущегоТеста` и прерывать тест с ошибкой, если состояние теста не равно `Выполнился`

**Comment by ValeraS** [comment]
`ПередЗапускомТеста` сотояние будет `НеВыполнялся`.

**Comment by artbear** [comment]
Ага, ты прав.

**Comment by artbear** [comment]
Все вышесказанное задокументировал в [Вики](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%A1%D0%B2%D1%8F%D0%B7%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D0%BD%D0%B0%D0%B1%D0%BE%D1%80%D1%8B-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D0%B5-%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8-%D0%B2-%D0%B2%D0%B8%D0%B4%D0%B5-%D1%81%D0%B2%D1%8F%D0%B7%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D1%88%D0%B0%D0%B3%D0%BE%D0%B2-%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D1%8F)

**Comment by artbear** [comment]
Задокументировал механизм сценарного тестирования для версии 4.Х в [Вики - "Сценарные тесты сценарии в виде связанных и последовательных шагов"]
(https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%A1%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%BD%D1%8B%D0%B5-%D1%82%D0%B5%D1%81%D1%82%D1%8B---%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8-%D0%B2-%D0%B2%D0%B8%D0%B4%D0%B5-%D1%81%D0%B2%D1%8F%D0%B7%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D0%B8-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D1%85-%D1%88%D0%B0%D0%B3%D0%BE%D0%B2)
