### ISSUE TITLE
Таблица значений из макета

### ISSUE THREAD

**Issue by progromaking** [xDrivenDevelopment/xUnitFor1C#510]
Подскажите, пожалуйста, реализована ли возможность загрузки таблицы значений в переменную из макета? 
И будет ли в дальнейшем возможность загрузки из макета данных в универсальные коллекции значений (таблица значений, список значений, структура) ?

Для чего мне это нужно: я хочу протестировать функцию, которая возвращает результат сложного запроса. Эта функция может возвращать большое количество строк. Заполнять все строки ожидаемой таблицы значений кодом - долго и ненаглядно.

**Comment by artbear** [comment]
По пунктам:
> Подскажите, пожалуйста, реализована ли возможность загрузки таблицы значений в переменную из макета? 

Нет, не реализовано.

> И будет ли в дальнейшем возможность загрузки из макета данных в универсальные коллекции значений (таблица значений, список значений, структура) ? 

Пока не было такой необходимости.

Для тестирования данных с помощью макетов-образцов в продукте есть утверждения
- `ПроверитьРавенствоТабличныхДокументовТолькоПоЗначениям`
- `ПроверитьРавенствоТаблиц` 

Схема тестирования при сравнении с образцом:
- исходные данные (образец, таблица значений и т.п.) заранее сохраняются в макет (можно через ЗначениеВСтрокуВнутр, можно через преобразование в табличный документ или любым другим способом)
- в начале кода теста из макета получаем исходную таблицу данных
- выполняется основной код, получается таблица данных 
- далее обе таблицы просто сравниваются указанными утверждениями
- все :)

**Comment by progromaking** [comment]
Понятненько. Будем применять.
