### ISSUE TITLE
Метод инициалиализации тест-объектов при подготовке запуска тестов

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#516]
Добавить вызов метода инициалиализации `Инициализация` тест-объектов при подготовке запуска тестов.
Если данный метод присутствует, то вызов метода `ПолучитьСписокТестов` при подготовке запуска тестов не осуществляется.

**Comment by pumbaEO** [comment]
Как это будет выглядеть?

**Comment by artbear** [comment]
Все просто. [Смотри код теста:](https://github.com/xDrivenDevelopment/xUnitFor1C/blob/develop/src/Tests/selftests/%D0%A2%D0%B5%D1%81%D1%82_%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%B8%D1%82%D1%8C%D0%98%D0%BD%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8E%D0%A2%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE%D0%9D%D0%B0%D0%B1%D0%BE%D1%80%D0%B0/ObjectModule.txt)
```
﻿Перем ЮТест;

Процедура Инициализация(ЮнитТестирование) Экспорт
	ЮТест = ЮнитТестирование;
КонецПроцедуры

Функция ПолучитьСписокТестов(ЮнитТестирование) Экспорт
	
	ВсеТесты = ЮнитТестирование.Новый_НаборТестов();
	
	ЮнитТестирование.НаборТестов_Добавить(ВсеТесты, "ТестДолжен_ПроверитьИнициализациюТестовогоНабора");
	
	Возврат ВсеТесты;
	
КонецФункции

//{ блок тестов - сами тесты

Процедура ТестДолжен_ПроверитьИнициализациюТестовогоНабора() Экспорт
	
	Если ЮТест = Неопределено Тогда
		ВызватьИсключение НСтр("ru = 'Тестовый набор не инициализирован.'");
	КонецЕсли;
	
КонецПроцедуры

//} конец блока тестов
```
