### ISSUE TITLE
Сделать конвертер старых тестовых обработок

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#518]
Реализовать:
- добавление метода `Инициализация` и установка переменных объекта `юТест` (`ЯдроТестирования`), `Утверждения`, `ГенераторТестовыхДанных`
- замена использования типовых утверждений (типа `юТест.ПроверитьРавенство(` на `Утверждения.ПроверитьРавенство(`
- замена кода создания тестовых данных - заменять `юТест.СоздатьДанныеПоМакетам` (и подобные функции создания данных) на `ГенераторТестовыхДанных.СоздатьДанныеПоМакетам` и т.п.

Также добавить документацию на конвертер в Wiki

**Comment by artbear** [comment]
Реализовать:
- добавление метода `Инициализация` и установка переменных объекта `юТест` (`ЯдроТестирования`) и `Утверждения`
- изменение сигнатуры метода `ПолучитьСписокТестов` (метод будет без параметров, а ранее был с одним параметром
- замена использования типовых утверждений (типа `юТест.ПроверитьРавенство(` на `Утверждения.ПроверитьРавенство(`

**Comment by wizi4d** [comment]
Кто за конвертер возьмется? У меня до него руки ой как не скоро дойдут :(

**Comment by artbear** [comment]
Реализовано для ОФ и УФ:
-  установка переменных объекта `юТест` (`ЯдроТестирования`), `Ожидаем`, `Утверждения`
- замена на новое API тестов (`Инициализация` и `ЗаполнитьНаборТестов`) вместо старого (`ПолучитьСписокТестов`)
- пока заменяются только простые объявления тестов. Например, НаборТестов.Добавить("ИмяНужногоТеста")

Все через TDD/BDD, все на тестах.

Еще нужно реализовать:
- установка переменной объекта `ГенераторТестовыхДанных`
- замена использования типовых утверждений (типа `юТест.ПроверитьРавенство(` на `Утверждения.ПроверитьРавенство(`
- замена кода создания тестовых данных - заменять `юТест.СоздатьДанныеПоМакетам` (и подобные функции создания данных) на `ГенераторТестовыхДанных.СоздатьДанныеПоМакетам` и т.п.

**Comment by artbear** [comment]
Реализовано
- установка переменной объекта `ГенераторТестовыхДанных`
- замена использования типовых утверждений (типа `юТест.ПроверитьРавенство(` на `Утверждения.ПроверитьРавенство(`
- замена кода создания тестовых данных - заменять `юТест.СоздатьДанныеПоМакетам` (и подобные функции создания данных) на `ГенераторТестовыхДанных.СоздатьДанныеПоМакетам` и т.п.

**Comment by artbear** [comment]
Конвертер готов. Преобразует тесты и для ОФ, и для УФ
Тест формата 3.0:
```
Перем юТест1;

Функция ПолучитьСписокТестов(ЮнитТестирование1) Экспорт
	юТест1 = ЮнитТестирование1;
	ВсеТесты1 = Новый Массив;
	ВсеТесты1.Добавить("Тест_ДваПлюсДва");
	Возврат ВсеТесты1;
КонецФункции

Процедура Тест_ДваПлюсДва() Экспорт
	юТест1.ПроверитьРавенство(2+2, 4, "2+2 = 4");
	юТест1.ПроверитьНеРавенство(2+2, 5);
	ТестовыеДанные = юТест1.СоздатьДанныеПоМакетам(Объект, "Макет");
	Рез = юТест1.ПолучитьКоличествоЭлементовСправочникаПоОтбору("Спр", Новый Структура);
КонецПроцедуры
```

заменяется на 
```
Перем КонтекстЯдра;
Перем Ожидаем;
Перем Утверждения;
Перем ГенераторТестовыхДанных;
Перем ЗапросыИзБД;

//Перем юТест1;
//Функция ПолучитьСписокТестов(ЮнитТестирование1) Экспорт
//	юТест1 = ЮнитТестирование1;
//	ВсеТесты1 = Новый Массив;
//	ВсеТесты1.Добавить("Тест_ДваПлюсДва");
//	Возврат ВсеТесты1;
//КонецФункции

Процедура Инициализация(КонтекстЯдраПараметр) Экспорт
	КонтекстЯдра = КонтекстЯдраПараметр;
	Ожидаем = КонтекстЯдра.Плагин("УтвержденияBDD");
	Утверждения = КонтекстЯдра.Плагин("БазовыеУтверждения");
КонецПроцедуры

Процедура ЗаполнитьНаборТестов(НаборТестов) Экспорт
	НаборТестов.Добавить("Тест_ДваПлюсДва");
КонецПроцедуры

Процедура Тест_ДваПлюсДва() Экспорт
	Утверждения.ПроверитьРавенство(2+2, 4, "2+2 = 4");
	Утверждения.ПроверитьНеРавенство(2+2, 5);
	ТестовыеДанные = ГенераторТестовыхДанных.СоздатьДанныеПоМакетам(Объект, "Макет");
	Рез = ЗапросыИзБД.ПолучитьКоличествоЭлементовСправочникаПоОтбору("Спр", Новый Структура);
КонецПроцедуры
```

**Comment by artbear** [comment]
Буду рад, если кто-нибудь проверит на своих реальных тестах.

Перед непосредственно конвертацией создается файл-копия ИмяТеста.orig.epf
Файл-копия создается только для тех внешних обработок, у которых в коде модуля обработки и модуле упр.формы найдено объявление "Процедура ПолучитьСписокТестов(...) Экспорт"

**Comment by bytemdfab** [comment]
Вопрос наверное не в тему, но как собственно инициализируется ГенераторТестовыхДанных? Или это плагин, который пока не реализован?

**Comment by artbear** [comment]
@bytemdfab 
`ГенераторТестовыхДанных = Контекст.Ядра("СериализаторMXL.epf");`

Неужели я не добавил его в конвертер? :(

**Comment by artbear** [comment]
>Неужели я не добавил его в конвертер? :(

Да, оказывается, именно эту переменную пропустил. 
исправлю

**Comment by artbear** [comment]
Исправлено: В сконвертированных тестах не инициализировались переменные ГенераторТестовыхДанных и ЗапросыИзБД
 https://github.com/xDrivenDevelopment/xUnitFor1C/commit/93b3c6c7597696d9a1ff5d96d5655d7174bff5ea

**Comment by karnilaev** [comment]
У меня ошибка при конвертации:
```
{ВнешняяОбработка.УтвержденияBDD.МодульОбъекта(283)}: [Failed] Ожидали, что проверяемое значение (4 294 967 295) РАВНО (0).
КодВозврата первый -unpack
	ВызватьИсключение Префикс + " " + СообщениеОшибки;
```
Если нужно - могу скинуть тест на почту, на котором вываливается ошибка.

**Comment by artbear** [comment]
Высылай на aartbear@gmail.com

вс, 20 Дек 2015, 22:03, Юрий <notifications@github.com>:

**Comment by karnilaev** [comment]
Выслал

**Comment by artbear** [comment]
@karnilaev 
>У меня ошибка при конвертации:
```
{ВнешняяОбработка.УтвержденияBDD.МодульОбъекта(283)}: [Failed] Ожидали, что проверяемое значение (4 294 967 295) РАВНО (0).
КодВозврата первый -unpack
	ВызватьИсключение Префикс + " " + СообщениеОшибки;
```
Если нужно - могу скинуть тест на почту, на котором вываливается ошибка.

Посмотрел твой тест, запустил конвертацию на последней версии конвертера на платформе 8.3
Конвертация прошла штатно и успешно
![image](https://cloud.githubusercontent.com/assets/2920817/11933473/1f79a50c-a80d-11e5-972b-cb21b5565192.png)
Возможно, ты проверял на промежуточной версии??
От версии платформы вроде бы не должно зависеть, т.к. все преобразование идет через v8unpack
Проверишь на последней версии конвертера?

Обнаружен только одна фича (или баг?)
У тебя есть код
```
Процедура ПередЗапускомТеста() Экспорт
	
	ЮнитТестирование.ТвойСобственныйМетодКоторогоНетВНашемФреймворке(Параметр);
	НачатьТранзакцию();
);
	
КонецПроцедуры
```
Вот здесь нет преобразования `ЮнитТестирование` на `КонтекстЯдра`, т.к. ни в 3.Х, ни в 4.Х нет метода с твоим наименованием.

Можешь поделиться (здесь или в личку на  мыло), что это за метод? каково его назначение?
Возможно, это будет всем полезно и мы выделим новый плагин?

**Comment by karnilaev** [comment]
Спасибо. Дело было в пути обработки. По такому пути конвертация прошла корректно:
```
C:\ТестыДляКонвертации\Тест_ДокументаВыдачаПаев.epf
```

а по такому уже ошибка:
```
C:\Тесты для конвертации\Тест_ДокументаВыдачаПаев.epf
```

Пробелов в пути быть не должно.

Метод выглядит так:
```
Процедура ПроверкаЗапускаТестаПодПользователемСПрофилем(НаименованиеПрофиля) Экспорт
	
	Если РольДоступна("ПолныеПрава") Тогда 
		ПропуститьТест(СтрШаблон(НСтр("ru = 'Тест предназначен для тестирования под Профилем %1 без полных прав'"), НаименованиеПрофиля));
	КонецЕсли;
	
	УстановитьПривилегированныйРежим(Истина);
	ПроверяемыйПрофиль = Справочники.ПрофилиГруппДоступа.НайтиПоНаименованию(НаименованиеПрофиля);
	Если ЗначениеЗаполнено(ПроверяемыйПрофиль) Тогда  
		УстановленПрофильДоступа = УправлениеДоступомПереопределяемый.ЕстьПрофильГруппПользователей(ПроверяемыйПрофиль, ПараметрыСеанса.ТекущийПользователь);
		Проверить(УстановленПрофильДоступа, СтрШаблон("ru = 'У данного пользователя нет профиля доступа %1'", НаименованиеПрофиля));
	Иначе
		ВызватьИсключение(СтрШаблон(НСтр("ru = 'В системе нет профиля %1'"), НаименованиеПрофиля));
	КонецЕсли;
	
КонецПроцедуры
```

Это является гарантией того, что тесты запускаются под пользователем с нужными правами. Позволяет отлавливать баги нехватки прав.

**Comment by artbear** [comment]
@karnilaev 
>Пробелов в пути быть не должно.
Ага, добавлю работу с путями, содержащими пробелы

**Comment by karnilaev** [comment]
А так конвертор отработал круто! Спасибо. Сильно облегчит жизнь :) Минимальные правки руками будут нужны.
