### ISSUE TITLE
Реализовать работу сценариев (контейнер с несколькими зависимыми методами)

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#520]

**Comment by wizi4d** [comment]
Главный вопрос в способе передачи зависимости.
Стоит учесть тот факт, что если/когда во фреймворк будут добавлены тесты с компилируемыми спецификациями (Gherkin), то, за счет повторного использования шагов сценария, сценарий может быть "размазан" на несколько обработок.

**Comment by wizi4d** [comment]
Кстати один из текущих вариантов очень неплох, в ядре методы ПолучитьКонтекст и УстановитьКонтекст.

Вариант с переменными модуля и реквизитами объекта выглядит как черная магия подверженная случайному использованию и обилию побочных эффектов.
@artbear это как-то в текущей реализации отключается? Метод РазрешенСлучайныйПорядокВыполненияТестов как раз для этого нужен?

**Comment by artbear** [comment]
@wizi4d Вопросы в последнем абзаце не понял. 
перефразируй, пожалуйста.

**Comment by wizi4d** [comment]
@artbear Как происходит включение/выключение передачи зависимости между тестами через переменные модуля и реквизиты объекта?

**Comment by pumbaEO** [comment]
@wizi4d только если используется это в самом тесте. Если желаешь использовать контекст, тогда делаешь проверку есть установлен ли контекст и пытаешься его установить. В другом тесте получаешь контекст. Но это все делаешь именно в тестовых обработках.

**Comment by wizi4d** [comment]
@pumbaEO я уже у @artbear уточнил. Функционал передачи контекста включен всегда и разработчик тестов сам должен следить за тем, чтобы не было побочных эффектов в тестах.

**Comment by wizi4d** [comment]
Для передачи контекста между зависимыми тестами служат методы:
- СохранитьКонтекст(Знач Контекст)
- ПолучитьКонтекст()
Методы доступны только для контейнеров со строгим порядком выполнения тестовых методов. В противном случае выбрасывается исключение. Интерфейс управления режимом строгий/случайный оставлен прежний.
Сами данные контекста сохраняются в контейнере, а не глобально. Иными словами область видимости сохраненных данных - контейнер.
