### ISSUE TITLE
Реализовать запуск тестов в случайном порядке (методы вне сценариев)

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#522]

**Comment by wizi4d** [comment]
Хотел добавить функционал по установке флага перемешивания тестов в ЗагрузчикФайла. Понял, что это нужно делать в рамках задачи #520

**Comment by artbear** [comment]
Не согласен с закрытием задачи.
Это требование полезно и для обычных/не сценарных тестов, чтобы дополнительно гарантировать их независимость друг от друга.

**Comment by artbear** [comment]
ИМХО Решать можно в рамках #520, но требования #520 и #522 различны.

**Comment by wizi4d** [comment]
Переоткрыл то зачем? Сейчас ВСЕ тесты запускаются в случайном порядке.

**Comment by artbear** [comment]
Ага, поторопился, забыл, что коммиты по реализации уже есть
