### ISSUE TITLE
Реализовать загрузку тестов из конфигурации

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#523]
Для запуска серверных тестов в браузере на УФ нужно будет вносить модификации в ядро

**Comment by artbear** [comment]
Для тестов в конфигурации не реализовано новое API загрузки через `ЗаполнитьНаборТестов` и вспомогательные методы нового API
```
// { API нового формата
Процедура СлучайныйПорядокВыполнения() Экспорт
Процедура СтрогийПорядокВыполнения()
Процедура НачатьГруппу(Знач ИмяГруппы, Знач СтрогийПорядокВыполнения = Ложь)
Функция Добавить(Знач ИмяМетода, Знач Параметры = Неопределено, Знач Представление = "")
Функция Добавить(Знач ИмяМетода, Знач Параметры = Неопределено, Знач Представление = "") 

Функция ПараметрыТеста(Знач Парам1, Знач Парам2 = Неопределено, Знач Парам3 = Неопределено, 
Знач Парам4 = Неопределено, Знач Парам5 = Неопределено, Знач Парам6 = Неопределено,
 Знач Парам7 = Неопределено, Знач Парам8 = Неопределено, Знач Парам9 = Неопределено) 
// }
```

сейчас эти методы реализованы непосредственно в загрузчике файлов.

Поэтому есть вопросы: 
+ методы этого API придется дублировать в каждом загрузчике для единого подхода к написания тестов ?? 
+ Если нет, как реализовать эти методы в загрузчике встроенных тестов ?

Переоткрываю issue

**Comment by karnilaev** [comment]
Какую базу использовать для прогона тестов из ветки reborn? У меня на базе из ветки develop в режиме обычного приложения много тестов валится.

**Comment by karnilaev** [comment]
Увидел в папке tests файл TestConfig.cf.

**Comment by karnilaev** [comment]
Что-то у меня и на конфигурации из папки tests куча тестова валится. Это нормально?
![2015-12-09 22 47 09](https://cloud.githubusercontent.com/assets/5828648/11696738/e9822c98-9ec6-11e5-93bc-82ee18b71d53.png)

**Comment by wizi4d** [comment]
Не нормально, все тесты должны проходить.
Какая версия платформы?
При первом запуске предприятия должен был создаться админский пользователь.
Он создался?

22:48, Ср, 09.12.2015, Юрий <notifications@github.com>:

**Comment by karnilaev** [comment]
Запускал на версии предприятия 8.2.19.130.
Изначально загрузил cf в существующую базу из ветки develop. Там пользователь Admin уже был.
Сейчас после твоего комментария загрузил cf в чистую базу. После первого запуска пользователь Admin создался, однако тесты все еще падают. Возможно мне на другой версии платформы проверить?

Предлагаю чтобы не засорять топик этой проблемой перейти в скайп. Мой скайп: karnilaev

**Comment by wizi4d** [comment]
@artbear у тебя есть настроенный CI на reborn ветку? Я со сменой места работы пока без CI :disappointed:. Если что, могу поделиться готовым конфигом под тимсити.

Декабрьские коммиты не могли ничего сломать?

**Comment by artbear** [comment]
Поделись билд-конфигом для тимСити, я забыл настроить на новом месте.
Возможно, мои коммиты поломали, я последние коммиты не особо проверял :(
Доеду до работы, проверю, исправлю

чт, 10 Дек 2015, 10:34, Evgeniy Pavlyuk <notifications@github.com>:

**Comment by wizi4d** [comment]
[XUnitFor1C_Ci.xml](https://files.zenhub.io/56692d109b2939d368c171c8)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by karnilaev** [comment]
Начал пользоваться версией 4.0. Не смотря на то, что раньше пользовался версией 3.0 в версии 4.0 есть фишки, из-за которых стоит на нее перейти. + кодовая база намного лучше
Ребята, спасибо за такую огромную работу!

**Comment by yuriybylinkin** [comment]
Реквестирую подробности. Какие именно фишки в 4.0, из-за которых стоит
перейти? Что именно нельзя сделать в третьей версии?
Мы просто никак не решимся на переход - останавливает большое количество
имеющихся тестов.  Их надо переписывать?

10 декабря 2015 г., 12:45 пользователь Юрий <notifications@github.com>
написал:

> Начал пользоваться версией 4.0. Не смотря на то, что раньше пользовался
> версией 3.0 в версии 4.0 есть фишки, из-за которых стоит на нее перейти. +
> кодовая база намного лучше
> Ребята, спасибо за такую огромную работу!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xDrivenDevelopment/xUnitFor1C/issues/523#issuecomment-163557400>
> .
>



-- 
Былинкин Юрий

**Comment by artbear** [comment]
Для перехода на версию 4.0 есть задача по созданию конвертера тестов в
новый формат. Сделал где-то 70%
Простые тесты сконвертируются,сложные описания частично сконвертируются
А сколько у вас всего тестов,файлов тестов?

чт, 10 Дек 2015, 13:07, Юрий Былинкин <notifications@github.com>:

**Comment by karnilaev** [comment]
@yuriybylinkin, очень большая часть юнит-тестов у нас написана еще до того, как мы узнали о проекте xUnitFor1C. Их получилось очень просто и удобно подключить к новой версии фреймворка благодаря новому API загрузки (пригодился метод "НачатьГруппу", которого не было в версии 3.0). На версии 3.0 было написано не очень много тестов, поэтому переход пройдет более менее безболезненно. 
Из понравившегося:
- Новое API загрузчика в котором достаточно удобно делать связанные одним контекстом тесты.
- Просто гениальный [плагин утверждений в "стиле BDD"](http://habrahabr.ru/post/260013/).
- Механизм плагинов, благодаря которому, уверен, скоро появятся очень крутые плагины к уже существующим. В версию 3.0, думаю, их не так то просто будет портировать.

**Comment by wizi4d** [comment]
@karnilaev спасибо за отзыв. Вот ради этого все и делалось, значит время было потрачено не зря :smile:

**Comment by artbear** [comment]
>Что-то у меня и на конфигурации из папки tests куча тестова валится. Это нормально?

Подтверждаю, ошибка была внесена моим коммитом.
Сегодня исправлю.

**Comment by artbear** [comment]
Исправлено, все тесты проходят.

**Comment by artbear** [comment]
Выполнено в #571
