### ISSUE TITLE
Реализовать запуск из командной строки

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#524]

**Comment by wizi4d** [comment]
Как насчет такого формата?
```
"C:\Program Files (x86)\1cv82\8.2.18.96\bin\1cv8c.exe" /DisableStartupMessages /Execute "\\path\xddTestRunner.epf" /S "server\ib" /LogUI /Out "\\path2\log.txt"  /C "xddRun ЗагрузчикКаталога \\path\tests;xddShutdown;xddReport ГенераторОтчетаJUnitXML \\path2\report.xml"
```
Т.е. команды разделены символом ";". Команда идет единым блоком со своими параметрами разделенными пробелами.
Формат в любом случае менять, потому что нужно указывать какой из плагинов берет на себя загрузку или формирование отчета.

**Comment by artbear** [comment]
ИМХО нормально.
Еще можешь посмотреть на #381

**Comment by wizi4d** [comment]
Реализованы ключи xddRun, xddReport, xddShutdown, что уже позволяет запускать CI на новой версии. По мере необходимости будем расширять в рамках других задач

**Comment by artbear** [comment]
Зафиксирую здесь:
строка запуска для CI

* chcp 1251
* "C:\Program Files (x86)\1cv8\8.3.4.496\bin\1cv8.exe" /DisableStartupMessages /Execute "%teamcity.build.checkoutDir%\xddTestRunner.epf" /F "tempdb" /N "Admin" /C "xddRun ЗагрузчикКаталога ""%teamcity.build.checkoutDir%\Tests"";xddReport ГенераторОтчетаJUnitXML ""%teamcity.build.checkoutDir%\report_ordinary.xml"";xddShutdown;"
