### ISSUE TITLE
Реализовать поддержку параметрических тестов

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#527]

**Comment by wizi4d** [comment]
@artbear текущая реализация тестами покрыта? Я что-то не могу их найти...

**Comment by wizi4d** [comment]
@artbear я бы уже может реализацию сделал бы... Ответь...

**Comment by ValeraS** [comment]
Наверное это:
`xUnitFor1C/Tests/selftests/Тест_ПараметрыТестов.epf`

**Comment by wizi4d** [comment]
Спасибо! То что нужно, я как-то проглядел.

**Comment by artbear** [comment]
Я был в оффлайне.  Только сегодня вернулся в Москву

чт, 2 Июл 2015, 10:02, Evgeniy Pavlyuk <notifications@github.com>:
