### ISSUE TITLE
Выделить плагин "Генератор тестовых данных"

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#531]

**Comment by wizi4d** [comment]
Предлагаю сделать плагин "СериализаторMXL", который будет заниматься как десериализацией и записью в базу (функционал живет я вдре), так и сериализацией в MXL (функционал обработки xddDataFixtureGen)

**Comment by allustin** [comment]
Я просто напомню #380 - чтобы не потерялось. 

Там были обсуждения как раз похожие на плагины связанные c отдельно генератором и отдельно сериализаторами в разные форматы
Возможно генератор и сериализатор(ы) - это разные задачи

**Comment by wizi4d** [comment]
@allustin рациональное зерно в твоих рассуждениях есть, я тоже об этом думал.
Пришел к тому, что я не понимаю, что именно должен делать генератор, если его выделить.
Сейчас я термины рассматриваю так:

- сериализация - данные базы в <некий формат>
- десериализация - <некий формат> в данные базы

**Comment by artbear** [comment]
Тут 2 проблемы:
1 генератор макетов данных должен представлять данные в удобном для человека формате (просмотр и редактироние). Лучшее - это таблица. Отсюда взялся mxl
2 При коллективной разработке (код ревью, гит и прочее) mxl/таблица становится неудобными - нет изменений или их неудобно смотреть, чистый гит накладывает свои ограничения на просмотр изменений через текстовики и т.п.

П.1 решается в генераторе.
П.2 ИМХО должен решаться при выгрузке в Гит, что не имеет отношения к xUnitFor1C, а должно решаться в соседнем проекте.

П.1 это сериализатор данных базы в формат mxl
А п.2 это сериализатор mxl-файла в какой-нибудь текстовый формат, удобный для Гит и коллективной разработки.

Отсюда и возникает разделение этих задач :)

ЗЫ Мы эти пункты достаточно подробно обсуждали в уже указанной задаче #380

**Comment by wizi4d** [comment]
@artbear предлагаю тебе функционал из <xddDataFixtureGen> перенести в <СериализаторMXL> и закрыть задачу.

**Comment by artbear** [comment]
Не понял откуда что перенести. Жду пояснений

пн, 6 Июл 2015, 14:23, Evgeniy Pavlyuk <notifications@github.com>:

**Comment by wizi4d** [comment]
Глюк какой-то с отображением, когда обрамляешь что-нибудь знаками <>
Сообщение было таким:
Предлагаю тебе функционал из "xddDataFixtureGen" перенести в
"СериализаторMXL" и закрыть задачу.


вт, 7 июля 2015 г. в 20:56, Artur Ayukhanov <notifications@github.com>:

**Comment by artbear** [comment]
>Предлагаю тебе функционал из `xddDataFixtureGen` перенести в `СериализаторMXL` и закрыть задачу.

Не хочется смешивать 2 все-таки различающихся функционала в одном.
Поэтому:
1 Я предлагаю оставить утилиту `xddDataFixtureGen` в каталоге утилит, а файл плагина оставить в каталоге плагинов.
2 Я доработаю  `xddDataFixtureGen` для использования плагина `СериализаторMXL`

**Comment by nixel2007** [comment]
> 2 При коллективной разработке (код ревью, гит и прочее) mxl/таблица становится неудобными - нет изменений или их неудобно смотреть, чистый гит накладывает свои ограничения на просмотр изменений через текстовики и т.п.

Вставлю свои пять копеек. В самом гите эту проблему можно решить через настройку git diff на какое-то другое приложение-сравниватель. С гитхабом сложнее, да.

**Comment by artbear** [comment]
@nixel2007 У нас в проекте precommit1c/v8reader уже решена эта задача и табличные макеты дополнительно к бинарнику выгружаются в текстовые файлы.

**Comment by wizi4d** [comment]
Предлагаю отложить до лучших времен, т.к. тема не критичная.

**Comment by artbear** [comment]
Тема довольно критична, т.к. сейчас в ветке 4.0 генерация макета не работает вообще :(
