### ISSUE TITLE
УФ: При загрузке тестов из каталога tests выдаются ошибки (4.0)

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#545]
Тесты загружаются, но в окне сообщений есть ошибки. Неудобно!
```
{ВнешняяОбработка.ЗагрузчикФайла.МодульОбъекта(112)}: Метод объекта не обнаружен (ПолучитьСписокТестов)
{ВнешняяОбработка.ЗагрузчикФайла.МодульОбъекта(112)}: Недостаточно фактических параметров
{ВнешняяОбработка.ЗагрузчикФайла.МодульОбъекта(112)}: Недостаточно фактических параметров
```

**Comment by artbear** [comment]
Проблема в коде
```
Функция ЗагрузитьТестыВСтаромФормате(ПостроительДереваТестов, Обработка, ФайлОбработки)
	Попытка
		СписокТестов = Обработка.ПолучитьСписокТестов(); // строка 112
	Исключение
		// TODO добавить обработку ошибок
		Описание = ОписаниеОшибки();
		Сообщить(Описание);
	КонецПопытки;
```

@wizi4d ИМХО нужно доработать, иначе получаем юзабельность так себе :(

**Comment by artbear** [comment]
Похожая проблема в `ЗагрузчикИзПодсистемКонфигурации`
но там вообще ничего не загружается и выдается исключение :(
```
{ВнешняяОбработка.ЗагрузчикИзПодсистемКонфигурации.МодульОбъекта(105)}: {ВнешняяОбработка.ЗагрузчикИзПодсистемКонфигурации.МодульОбъекта(101)}: Недостаточно фактических параметров
			ВызватьИсключение Описание;
```

```
Функция ЗагрузитьОбработку(МетаданныеОбработки, ПостроительДереваТестов, ЗагрузчикФайла)
	Обработка = СоздатьОбработкуПоМетаданным(МетаданныеОбработки);
	Попытка
		СписокТестов = Обработка.ПолучитьСписокТестов();
	Исключение
		Описание = ОписаниеОшибки();
		Если Найти(Описание, "Метод объекта не обнаружен (ПолучитьСписокТестов)") = 0 Тогда
			ВызватьИсключение Описание;
		КонецЕсли;
	КонецПопытки;
```

@wizi4d Нужно исправить.

**Comment by wizi4d** [comment]
Если честно не понимаю о каких ошибках речь. Обратной совместимости нет со старыми тестовыми обработками нет. Судя по текстам исключений, ты старые тесты новым раннером гонять пытаешься.

**Comment by artbear** [comment]
Нет, точно все новое.
По `ЗагрузчикИзПодсистемКонфигурации` была старая версия конфигурации, я загрузил нужную, ошибка изменилась. Исправил свое сообщение выше.
Посмотри в ручном режиме для тестов конфигурации - не работает ни тестирование всех тестов, ни тестирование выделенного теста.

**Comment by wizi4d** [comment]
Про загрузчик подсистем гляну когда из отпуска выйду. Я менял интерфейс, странно, что CI это не поймал

**Comment by wizi4d** [comment]
Кстати, какое поведение ожидаешь вместо сообщить при загрузке тестов?

**Comment by artbear** [comment]
Как я реализовал в старом варианте, нужно изучать описание ошибки и если там написано, что метод "ПолучитьСписокТестов" не обнаружен, то просто не грузить файл, ничего не сообщая пользователю.
В остальных случаях выдавать ошибку.
Это сильно повышает юзабельность, если идет пересечение тестовых обработок и каких-то других обработок.
Нечто подобное у тебя уже есть в `ЗагрузчикИзПодсистемКонфигурации`

**Comment by wizi4d** [comment]
@artbear проверяй и закрывай

**Comment by artbear** [comment]
@wizi4d Неточно поправил.
Я уже выше писал
>Как я реализовал в старом варианте, нужно изучать описание ошибки и если там написано, что метод "ПолучитьСписокТестов" не обнаружен, то просто не грузить файл, НИЧЕГО НЕ сообщая пользователю.
В остальных случаях выдавать ошибку.
Это сильно повышает юзабельность, если идет пересечение тестовых обработок и каких-то других обработок.

Сейчас выводится совершенно путающее сообщение
"{ВнешняяОбработка.ЗагрузчикФайла.МодульОбъекта(112)}: Метод объекта не обнаружен (ПолучитьСписокТестов)"

**Comment by wizi4d** [comment]
@artbear у меня все хорошо, может ты pull не сделал?
В коммите добавил коммент в место исправления.

**Comment by artbear** [comment]
Да, я ошибся и пулл не сделал.
Подтверждаю, что все исправлено.
