### ISSUE TITLE
Добавить обработку на существование обработчика Инициализация

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#548]
Сейчас в коде используется прямой вызов методов тест-обработки/тест-формы.
`КонтекстВыполнения.Инициализация(ОбъектНаСервере);`
`КонтекстВыполнения.Инициализация(ЭтаФорма);`

Если в коде модуля теста не будет такой обработки, будет возникать не совсем понятные исключения. Например, для тестов в старом формате теста.

Предлагаю сделать поведение аналогично методу `ПолучитьСписокТестов`.
Если метода нет, выдавать исключение со спец.текстом о неподходящем формате теста.

**Comment by wizi4d** [comment]
Будет ругаться на не обнаружен метод Инициализация, что в этом плохого?

**Comment by artbear** [comment]
ИМХО юзабилити выше, если пользователю явно показать "У вас не, реализован метод Инициализация, необходимый для тестирования", чем показать штатное сообщение из исключения.
А вообще этот метод насколько обязателен?

**Comment by wizi4d** [comment]
Метод обязательный, но вызывается при прогоне тестов, а не при загрузке. Если "глушить" исключение сообщением, то будет спам. Можно разве что типовое исключение заменить на свое, возможно станет немного получше

**Comment by wizi4d** [comment]
Если честно, я бы не делал этого. Если есть желание можешь сделать самостоятельно

**Comment by artbear** [comment]
Основная проблема в том, что тестирование полностью останавливается и даже непонятно, какой тест виноват в этой ошибке :(
Так что нужно исправлять.

**Comment by artbear** [comment]
Исправлено.
