### ISSUE TITLE
УФ: при открытии xUnitFor1C невиданная ошибка (только в одной ИБ)

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#550]
УФ: при открытии xUnitFor1C невиданная ошибка (только в одной ИБ)
1С 8.3.6.2299

**При работе формы произошла системная ошибка (нарушена синхронизация состояния формы на клиенте и сервере): "Различаются значения счетчиков для данных форм: 3.5 != 1.1"**

![image](https://cloud.githubusercontent.com/assets/2920817/10666696/eb18f822-78db-11e5-95c1-379fd5190756.png)

Форма никак не открывается, прочие встроенные формы и формы других внешних обработок открываются нормально.

Перегрузка сервера не помогает, чистил кеш пользователя Винды
в соседней ИБ на этой же машине работает.

Что делать, непонятно :(

**Comment by artbear** [comment]
При работе формы произошла системная ошибка (нарушена синхронизация состояния формы на клиенте и сервере): "Различаются значения счетчиков для данных форм: 3.5 != 1.1"

**Comment by Amon-Ra-** [comment]
Ошибку починил?

**Comment by artbear** [comment]
Да, починил, конечно.
Как чинил, не помню :(
