### ISSUE TITLE
Ошибка описания в Wiki

### ISSUE THREAD

**Issue by GaLich83** [xDrivenDevelopment/xUnitFor1C#558]
На странице "Создание файлов тестов" указано, что перед набором тестов выполняется процедура ПередЗапускомТестовогоНабора  (необязательная), а после ПослеЗапускаТестовогоНабора.
Судя по коду обработки сейчас эти процедуры называются ПередЗапускомНабораТестов и ПослеЗапускаНабораТестов соответственно.

**Comment by artbear** [comment]
Спасибо за ошибку.
Исправил.

**Comment by artbear** [comment]
Правильное поведение - gроцедуры называются `ПередЗапускомНабораТестов` и `ПослеЗапускаНабораТестов` соответственно.
