### ISSUE TITLE
При прерывании тестов хотелось бы, чтобы перед остановкой выполнялись процедуры ПослеЗапускаТеста (на котором произошел вызов прерывания) и ПослеЗапускаНабораТестов

### ISSUE THREAD

**Issue by GaLich83** [xDrivenDevelopment/xUnitFor1C#560]
Когда в этих методах реализована зачистка созданных для тестирования данных, то при прерывании пользователем теста желательно, чтобы очистка все-таки производилась.

**Comment by karnilaev** [comment]
Реализовал у себя следующим образом:
После [этой строки](https://github.com/xDrivenDevelopment/xUnitFor1C/blob/develop/src/xddTestRunner/ObjectModule.bsl#L178) вставил строку
``` bsl
ВыполнитьНеобязательнуюПроцедуруТестовогоСлучая(КонтекстВыполнения, "ПослеЗапускаТеста_СОшибкой");
```
В обработке теста соответственно есть следующая строка:
``` bsl
Процедура ПослеЗапускаТеста_СОшибкой() Экспорт
	УдалитьТестовыеДанные();
КонецПроцедуры
```

**Comment by karnilaev** [comment]
Правда это касается тестов, которые упали с ошибкой, а не прерваны пользователем.

**Comment by artbear** [comment]
Предлагаю другую реализацию сценарного теста:
```bsl
Процедура ЗаполнитьНаборТестов(НаборТестов) Экспорт
	НаборТестов.НачатьГруппу("Группа со строгим порядком выполнения и вызовом деструктора группы", Истина);
	НаборТестов.Добавить("КонструкторСценария", ,"Начало сценария");
	НаборТестов.Добавить("ТестДолжен_ПроверитьЖурналВыполнения");
	НаборТестов.ДобавитьДеструктор("ДеструкторСценария", "Обязательное завершение сценария");
КонецПроцедуры

Процедура КонструкторСценария() Экспорт
	ЖурналВыполнения = "КонструкторСценария;";
КонецПроцедуры

Процедура ТестДолжен_ПроверитьЖурналВыполнения() Экспорт
	Ожидаем.Что(ЖурналВыполнения, "ТестДолжен_ПроверитьЖурналВыполнения").Равно("КонструкторСценария;");
	ЖурналВыполнения = ЖурналВыполнения + "ПроверитьЖурналВыполнения;";
	//Сообщить("ТестДолжен_ПроверитьЖурналВыполнения -- ЖурналВыполнения " + ЖурналВыполнения);
КонецПроцедуры

Процедура ДеструкторСценария() Экспорт
	//Сообщить("ПослеЗапускаГруппыТестов -- ЖурналВыполнения " + ЖурналВыполнения);
	Ожидаем.Что(ЖурналВыполнения, "ДеструкторСценария").Равно("КонструкторСценария;ПроверитьЖурналВыполнения;");
	ЖурналВыполнения = ЖурналВыполнения + "ДеструкторСценария;";
КонецПроцедуры
```

Именно ее я начал реализовывать.

ИМХО удобно получается.

**Comment by artbear** [comment]
Деструктор будет вызывать в любом случае.
В случае успеха он вызывается как обычный шаг
В случае падения на любом из шагов он будет вызван перед завершением работы по сценарию.
Если падение происходит в коде самого деструктора, второй раз он не вызывается.

**Comment by artbear** [comment]
Реализовано.
Дополнил [wiki-документацию по работе со сценарными тестами](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%A1%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%BD%D1%8B%D0%B5-%D1%82%D0%B5%D1%81%D1%82%D1%8B---%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8-%D0%B2-%D0%B2%D0%B8%D0%B4%D0%B5-%D1%81%D0%B2%D1%8F%D0%B7%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D0%B8-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D1%85-%D1%88%D0%B0%D0%B3%D0%BE%D0%B2)

**Comment by artbear** [comment]
Обратите внимание, что версия 4.1.0.0, в которой выполнена реализация, работает только в 8.3
Последняя версия под 8.2 - это 4.0.0.7
