### ISSUE TITLE
Добавление возможности включение версии reborn в состав конфигурации

### ISSUE THREAD

**Issue by karnilaev** [xDrivenDevelopment/xUnitFor1C#562]
В силу того, что разработку мы ведем на хранилище 1С нам удобно, чтобы обработка по запуску тестов и плагины были включены в состав конфигурации.

Фича-реквест:
* Добавить возможность запуска обработки когда она встроена в конфигурацию
* Тесты так же имеют возможность встраиваться в конфигурацию, и поиск их осуществляется по префиксу "xddPlugin_", например.

**Comment by artbear** [comment]
@wizi4d Как я уже ранее тебе говорил, народу нужна эта функциональность :)
Обсудим?

**Comment by karnilaev** [comment]
@artbear, спасибо, что не отверг этот реквест как не нужный!

**Comment by karnilaev** [comment]
Для своих нужд я переделаю обработку как считаю нужным, но готов взяться за реализацию согласованной вами архитектуры.

**Comment by artbear** [comment]
@karnilaev 
>готов взяться за реализацию согласованной вами архитектуры.

Отличное предложение.
Ждем @wizi4d

**Comment by karnilaev** [comment]
В принципе у себя пока справились с этой функциональностью следующим образом: вынесли в интерфейс команду "Модульное тестирование", которая
* если путь до внешней обработки запуска юнит-тестовеще не задавался, или он не существует, то спрашивает этот путь у пользователя, 
* а если он ранее был задан, и обработка по этому пути существует, то открывается внешний xddTestRunner.epf

**Comment by wizi4d** [comment]
Смотрите сами, мне не принципиально.
Вот только внутрь конфигурации целый ворох внешних обработок не очень хочется тащить. Тем более, что потребность очень легко обходится приведенным выше способом.
Альтернативный способ - поместить обработки внутрь конфигурации как двоичные макеты, распаковывать их во временный каталог, проводить тестирование и подчищать за собой.

**Comment by karnilaev** [comment]
Мне такая возможность больше не нужна, поэтому задачу закрываю. Можно будет переоткрыть если будет необходимость.
