### ISSUE TITLE
В обычных формах не верная иконка упавших юнит-тестов

### ISSUE THREAD

**Issue by karnilaev** [xDrivenDevelopment/xUnitFor1C#563]
В обычных формах упавшие юнит-тесты выглядят так (т.е. как будто к иконке непрогоняемого юнит-теста добавлены какие-то артефакты):
![2015-12-09 16 49 58](https://cloud.githubusercontent.com/assets/5828648/11686960/1076b53a-9e95-11e5-8883-401ee82271ad.png)

**Comment by karnilaev** [comment]
Для неизвестной ошибки нет иконки. Сейчас исправлю и пришлю пул реквест.

**Comment by karnilaev** [comment]
В управляемых формах иконка тоже не существует для сломанных тестов. Отправил пул-реквест.

**Comment by artbear** [comment]
Пулл-реквест смержил.
Подтверждаешь исправление ошибки?
Если да, задачу закрывай.

Ты молодец, большое спасибо!

**Comment by karnilaev** [comment]
Спасибо!
