### ISSUE TITLE
В плагине загрузки тестов из метаданных конфигурации отсутствует возможность загружать тесты в новом формате.

### ISSUE THREAD

**Issue by karnilaev** [xDrivenDevelopment/xUnitFor1C#565]
Собственно фича реквест. Как перетяну эту функциональность из плагинов загрузки юнит-тестов из файлов - сделаю пул реквест.

**Comment by artbear** [comment]
Дубль. Уже есть https://github.com/xDrivenDevelopment/xUnitFor1C/issues/523#issuecomment-158418998

**Comment by karnilaev** [comment]
Ок, спасибо.
