### ISSUE TITLE
Архитектура взаимодействия плагинов/утилит между собой

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#568]
Предлагаю обсудить архитектуру взаимодействия плагинов/утилит между собой и инициализации плагинов в целом.

У меня следующий кейс:
у меня в тесте создаются временные файлы/каталоги. Этим нужно управлять.
Не хочу дублировать код работы со временными файлами в каждом тесте, а хочу использовать общую утилиту.
хочу добавить простой и полезный плагин ВременныеФайлы (который мы активно юзаем в тестах 1script из oscript-library) для использования временных файлов/каталогов в тестах и автоматического их удаления после завершения тестов.
Этот плагин использует полезный класс Логирование, который также просится для портирования.

Каким образом эти 2 плагина будут взаимодействовать между собой?

ИМХО удобно организовать взаимодействие через контекст ядра как общую часть, которая всегда стартует.
Но сейчас в интерфейсе плагина у нас контекст ядра никак не передается.

И попутная проблема - сейчас никак нельзя параметризовать инициализацию плагина, т.к. нет обработчика создания плагина, кроме простой инициализации в теле модуля (после всех процедур)

Как вариант, напрашивается добавление метода `Инициализация(КонтекстЯдраПараметр)` в интерфейс плагина

Народ, что скажете?
@wizi4d @EvilBeaver @kuntashov @ValeraS @pumbaEO ?

**Comment by kuntashov** [comment]
Я читал статью Евгения Павлюка, но не сильно вникал, поэтому непосредственно рекомендаций давать не буду (в общем и целом с предложением Артура склонен согласиться). Но расскажу, как аналогичный механизм организован в другом фреймворке, который я использую, может быть что-то почерпнете.

В Codeception архитектура следующая (немного упрощаю).  В нем вместо термина "плагин" используется термин "Модуль" (Module). 

Есть глобальный класс-одиночка (singeltone) `SuiteManager`.
Он собственно кроме всего прочего отвечает в том числе и за загрузку модулей и хранит ссылки на все загруженные модули в специальной публично доступной коллекции.

У базового класса Codeception\Module, на основе которого создаются другие модули (наследованием) есть метод `getModule($moduleName)`, который возвращает нужный модуль, обращаясь к коллекции модулей SuiteManager. Есть также метод, позволяющий проверить, подключен ли модуль или нет, называется `hasModule($moduleName)`.

Т.е. внутри своего модуля я могу получить экземпляр  подключенного модуля "Filesystem" (аналог плагина ВременныеФайлы Артура) путем вызова `$this->getModule("Filesystem")`.

Какие модули модули мне надо использовать в данном тестовом наборе, указывается в конфигурационном файле этого тестового набора.

Соответственно он считывает из конфига, какие модули надо загрузить и какие параметры использовать для инициализации модуля (например, строку подключения к БД, логины/пароли и т.п.), создает экземпляры модулей, инициализирует передавая значения параметров из конфига.

Обращаю внимание, что модули загружаются для конкретного тестового набора - это такая оптимизация, не грузить  все подряд плагины/модули, а только те, которые нужны конкретно в данном тестовом наборе.

Что касается логирования -  это функционал, востребованный как в самом ядре, так и в других плагинах, и в самих тестах, поэтому это отдельный случай и логирование в том же Codeception встроено в ядро. Т.е. это не отдельный модуль/плагин, а именно функционал ядра.
