### ISSUE TITLE
Ошибка в преобразовании журнала действий пользователя (UILogToScript)

### ISSUE THREAD

**Issue by Anna1c** [xDrivenDevelopment/xUnitFor1C#583]
Преобразовываю записанные действия пользователя, при нажатии на кнопку "Преобразовать" появляется сообщение об ошибке:
"Неопознанный атрибут switchSelection: true"

**Comment by yuriybylinkin** [comment]
Скачайте обработку с ИТС, в составе xUnit она довольно старая.

25 декабря 2015 г., 13:10 пользователь Anna1c <notifications@github.com>
написал:

> Преобразовываю записанные действия пользователя, при нажатии на кнопку
> "Преобразовать" появляется сообщение об ошибке:
> "Неопознанный атрибут switchSelection: true"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xDrivenDevelopment/xUnitFor1C/issues/583>.
>



-- 
Былинкин Юрий

**Comment by artbear** [comment]
Добавим новую обработку

пт, 25 Дек 2015, 13:30, Юрий Былинкин <notifications@github.com>:

**Comment by artbear** [comment]
Новая версия UILogToScript добавлена для версии 4.0.0.7 и 4.1.Х
