### ISSUE TITLE
При запуске менеджера тестов из ветки develop_v4_reborn получаем ошибку "Использование синхронных методов на клиенте запрещено!"

### ISSUE THREAD

**Issue by GaLich83** [xDrivenDevelopment/xUnitFor1C#584]

**Comment by artbear** [comment]
В ветке v4 пока не реализована фича работы в асинхронном режиме.
Планируем сделать на втором этапе

вт, 29 Дек 2015, 9:51, GaLich83 <notifications@github.com>:

**Comment by artbear** [comment]
Насколько для Вас критично? Какая типовая конфигурация используется?

вт, 29 Дек 2015, 15:55, Артур Аюханов <aartbear@gmail.com>:

**Comment by artbear** [comment]
Исходная issue #521
Закрываю.
