### ISSUE TITLE
Как в тестах ветки Reborn принудительно указывать "строгий" порядок выполнения

### ISSUE THREAD

**Issue by yuriybylinkin** [xDrivenDevelopment/xUnitFor1C#585]
Пытаюсь перейти на Reborn.
По умолчанию тесты проигрываются в случайном порядке. Посмотрел в тестах к фреймворку. 
Вы формируете список программно и так же его проигрываете. Как указать неслучайный порядок для обычных тестов?

**Comment by artbear** [comment]
Посмотри [Тесты_ЗагрузчикФайла_НовыйAPIОбъявленияТестов](https://github.com/xDrivenDevelopment/xUnitFor1C/blob/develop_v4_reborn/src/Tests/Plugins/%D0%A2%D0%B5%D1%81%D1%82%D1%8B_%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D1%87%D0%B8%D0%BA%D0%A4%D0%B0%D0%B9%D0%BB%D0%B0_%D0%9D%D0%BE%D0%B2%D1%8B%D0%B9API%D0%9E%D0%B1%D1%8A%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F%D0%A2%D0%B5%D1%81%D1%82%D0%BE%D0%B2/ObjectModule.txt)

```
Процедура ЗаполнитьНаборТестов(НаборТестов) Экспорт
	// Устанавливает режим выполнения для контейнера обработки
	НаборТестов.СлучайныйПорядокВыполнения();
	//НаборТестов.СтрогийПорядокВыполнения();
	
	НаборТестов.Добавить("ТестДолжен_ПроверитьВыполнение_ПростогоТеста");
	
	НаборТестов.НачатьГруппу("Группа со случайным порядком выполнения");
	НаборТестов.Добавить("ТестДолжен_ПроверитьВыполнение_ПростогоТеста_СПроизвольнымПредставлением", , "Тест с произвольным представлением");
	НаборТестов.Добавить("ТестДолжен_ПроверитьВыполнение_ТестаСПараметром", НаборТестов.ПараметрыТеста(Истина));
	
	НаборТестов.НачатьГруппу("Группа со строгим порядком выполнения", Истина);
	НаборТестов.Добавить("ТестДолжен_СохранитьКонтекст");
	НаборТестов.Добавить("ТестДолжен_ПроверитьСохраненныйКонтекст");
	
	НаборТестов.НачатьГруппу("Группа параметризированных тестов со строгим порядком выполнения", Истина);
	НаборТестов.Добавить("ТестДолжен_СохранитьРезультатСложенияВКонтекст", НаборТестов.ПараметрыТеста(5, 7), "Тест должен сохранить результат сложения (5 + 7) в контекст");
	Тест = НаборТестов.Добавить("ТестДолжен_СравнитьКонтекстСоСвоимПараметром");
	Тест.Параметры.Добавить(12);
КонецПроцедуры
```

**Comment by artbear** [comment]
Если ответ достаточен, пожалуйста, закрой issue

**Comment by yuriybylinkin** [comment]
Спасибо

2016-01-20 16:31 GMT+03:00 Artur Ayukhanov <notifications@github.com>:

> Если ответ достаточен, пожалуйста, закрой issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xDrivenDevelopment/xUnitFor1C/issues/585#issuecomment-173204010>
> .
>



-- 
Былинкин Юрий
