### ISSUE TITLE
А когда релиз 4.0 ?

### ISSUE THREAD

**Issue by JohnyDeath** [xDrivenDevelopment/xUnitFor1C#586]
Привет.
А релиз 4.0 вообще будет? Или он планируется отдельным продуктом?

**Comment by artbear** [comment]
Релиз 4.0 планировался в конце декабря.

В связи с моей затянувшейся болезнью я не смог завершить работу по созданию релиза.
На работу вышел только 21.01.16

Планирую выпустить релиз 4.0 в ближайшие 2 недели (т.е. до 08.02.16)

**Comment by JohnyDeath** [comment]
Т.е. он будет в рамках этого же проекта?

**Comment by artbear** [comment]
Да, именно в рамках этого проекта.
