### ISSUE TITLE
Проблемы при конвертации тестов от версии 3 к версии 4

### ISSUE THREAD

**Issue by bf0rce** [xDrivenDevelopment/xUnitFor1C#590]
После использования обработки xddTestsConvertIntoRebornFormat.epf возникли следующие сложности.

Такая интересная особенность.

- Сравнение файлов в конфигураторе не показывает отличий в модулях объектов, хотя они там есть. Помогает любое изменение и сохранение обновленной обработки. Похоже, 1С сравнивает сначала некие служебные данные, а только потом анализирует содержимое обработки.

Ошибки, которые не позволяют раннеру загрузить обработку.

-  юТест.ПрерватьТест() не заменилось на КонтекстЯдра.ВызватьОшибкуПроверки().

- юТест.РазложитьСтрокуВМассивПодстрок() должно было замениться на ГенераторТестовыхДанных.РазложитьСтрокуВМассивПодстрок() или на ПарсерКоманднойСтроки.РазложитьСтрокуВМассивПодстрок().

- юТест.ВывестиСообщение(). Аналогов не нашел.

- юТест.ПолучитьТаблицуЗначенийИзТабличногоДокумента(). Делали эту функцию экспортной для своих потребностей, но теперь ее нет совсем. Я так понимаю, теперь мы должны сделать собственный плагин и включить ее туда?

И маленький вопрос. Ранее можно было написать так
`юТест.ПроверитьВыполнилось("СоздатьДанныеПоМакетам(Параметры, ""Номенклатура"")", ЭтотОбъект);`.
Теперь нужно писать немного длиннее или я не нашел нужного способа?
`Параметры = Новый Структура("ГенераторТестовыхДанных,ЭтотОбъект", ГенераторТестовыхДанных, ЭтотОбъект);
Утверждения.ПроверитьВыполнилось("Параметры.ГенераторТестовыхДанных.СоздатьДанныеПоМакетам(Параметры.ЭтотОбъект, ""Номенклатура"")", Параметры);`

**Comment by nixel2007** [comment]
> Сравнение файлов в конфигураторе не показывает отличий в модулях объектов, хотя они там есть. Помогает любое изменение и сохранение обновленной обработки. Похоже, 1С сравнивает сначала некие служебные данные, а только потом анализирует содержимое обработки.

версию. 1с на любом объекте сначала сравнивает версию. совпадает версия - дальше сравнения не идет.

**Comment by artbear** [comment]
>юТест.РазложитьСтрокуВМассивПодстрок() должно было замениться на ГенераторТестовыхДанных.РазложитьСтрокуВМассивПодстрок() или на ПарсерКоманднойСтроки.РазложитьСтрокуВМассивПодстрок().

Может быть, какой-то отдельный плагин сделаем (СтроковыеУтилиты). 
Портируем из [oscript-library/src/strings/СтроковыеФункции.os](https://github.com/EvilBeaver/oscript-library/blob/develop/src/strings/%D0%A1%D1%82%D1%80%D0%BE%D0%BA%D0%BE%D0%B2%D1%8B%D0%B5%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8.os) ?

>юТест.ПрерватьТест() не заменилось на КонтекстЯдра.ВызватьОшибкуПроверки().

Проверю, поправлю

>юТест.ВывестиСообщение(). Аналогов не нашел.

Добавлю в контекст ядра

>юТест.ПолучитьТаблицуЗначенийИзТабличногоДокумента(). Делали эту функцию экспортной для своих потребностей, но теперь ее нет совсем. Я так понимаю, теперь мы должны сделать собственный плагин и включить ее туда?

Этот метод предлагаю добавить в сериализатор MXL

**Comment by artbear** [comment]
>> Сравнение файлов в конфигураторе не показывает отличий в модулях объектов, хотя они там есть. Помогает любое изменение и сохранение обновленной обработки. Похоже, 1С сравнивает сначала некие служебные данные, а только потом анализирует содержимое обработки.

>версию. 1с на любом объекте сначала сравнивает версию. совпадает версия - дальше сравнения не идет.

Да, проблема с версией.
Не думал, что это будет важно :)

Я обычно файлы сравниваю из файл-менеджера или из гита, запуская через командную строку  сравнение епф-файлов через v8Diff

Попробую посмотреть, какая из версий меняется, и как ее можно поменять.

**Comment by artbear** [comment]
>И маленький вопрос. Ранее можно было написать так
`юТест.ПроверитьВыполнилось("СоздатьДанныеПоМакетам(Параметры, ""Номенклатура"")", ЭтотОбъект);.`
Теперь нужно писать немного длиннее или я не нашел нужного способа?
```
Параметры = Новый Структура("ГенераторТестовыхДанных,ЭтотОбъект", ГенераторТестовыхДанных, ЭтотОбъект); 
Утверждения.ПроверитьВыполнилось("
Параметры.ГенераторТестовыхДанных.СоздатьДанныеПоМакетам(Параметры.ЭтотОбъект, ""Номенклатура"")", 
Параметры);
```

Навскидку `Параметры = Новый Структура("ГенераторТестовыхДанных,ЭтотОбъект", ГенераторТестовыхДанных, ЭтотОбъект); 
это что-то лишнее`

**Comment by awa15** [comment]
@artbear , версии хранятся в файле versions. Там простой формат
```
{1,<Число N - количество записей о версиях>,<Строка Имя файла 1>,<UUID Версия файла 1>,...,<Строка Имя файла N>,<UUID Версия файла N>}
```
Можно попробовать в файл versions просто писать таким
```
{1,0}
```
так как 1С, вроде бы, нормально относится к тому, что версии файлов не указаны совсем.

**Comment by artbear** [comment]
>И маленький вопрос. Ранее можно было написать так
`юТест.ПроверитьВыполнилось("СоздатьДанныеПоМакетам(Параметры, ""Номенклатура"")", ЭтотОбъект);.`
Теперь нужно писать немного длиннее или я не нашел нужного способа?
```
Параметры = Новый Структура("ГенераторТестовыхДанных,ЭтотОбъект", ГенераторТестовыхДанных, ЭтотОбъект); 
Утверждения.ПроверитьВыполнилось("
Параметры.ГенераторТестовыхДанных.СоздатьДанныеПоМакетам(Параметры.ЭтотОбъект, ""Номенклатура"")", 
Параметры);
```

А зачем проверять выполнение `ГенераторТестовыхДанных.СоздатьДанныеПоМакетам`

Этот метод либо работает либо нет. Если удалось создать данные, он возвращает структуру данных. Если данные создать не удалось, выбрасывается исключение.
Это официально поддерживаемое поведение.

Т.е. проверка выполнения создания данных должна заключаться просто в вызове `ГенераторТестовыхДанных.СоздатьДанныеПоМакетам` :) и не нужны никакие сложности!

**Comment by bf0rce** [comment]
> Да, проблема с версией.
> Не думал, что это будет важно :)
Не то, чтобы сильно важно. В конечном итоге, я же догадался открыть обработку и посмотреть в модуль. Но первое впечатление было немного неожиданным. Хотелось увидеть что конкретно изменила обработка, а сравнение не показывает ничего))

> А зачем так сложно проверять выполнение ГенераторТестовыхДанных.СоздатьДанныеПоМакетам ? ...
> 
> Т.е. проверка выполнения создания данных должна заключаться просто в вызове ГенераторТестовыхДанных.СоздатьДанныеПоМакетам :) и не нужны никакие сложности!
Да, здесь полностью согласен. Я привел не удачный пример. У нас перед таким тестом есть еще несколько других, негативных тестов, где в базу при помощи метода СоздатьДанныеПоМакетам записываются "кривые данные".
`Процедура Тест_ПопыткаСоздатьНекорректныеУзлыПланаОбмена() Экспорт
	
	юТест.ПроверитьНеВыполнилось("СоздатьДанныеПоМакетам(Параметры, ""НекорректныеУзлыПланаОбмена_НеУстановленНиОдинФлаг"")", ЭтотОбъект);
	
КонецПроцедуры`
Может я тоже избрал не тот способ проверки?  Придумать я смог только вариант, когда контекст Генератора передается в Базовые утверждения.

**Comment by artbear** [comment]
Да, с ПроверитьВыполнилось, ПроверитьНеВыполнилось сложно работать, они не имеют доступа к текущему контексту выполнения.
Поэтому приходится юзать параметры.
Раньше была связь Тест - юТест, сейчас усложнилось Тест - юТест - ПлагинУтверждения
Поэтому придется так и передавать, через спец. параметры :(

**Comment by bf0rce** [comment]
> Может быть, какой-то отдельный плагин сделаем (СтроковыеУтилиты). 
> Портируем из oscript-library/src/strings/СтроковыеФункции.os ?
Кажется, написать плагин не крупная задача. Я готов взяться.

**Comment by artbear** [comment]
@bf0rce 
>> Может быть, какой-то отдельный плагин сделаем (СтроковыеУтилиты). 
 Портируем из oscript-library/src/strings/СтроковыеФункции.os ?

>Кажется, написать плагин не крупная задача. Я готов взяться.

Отличное предложение.
Жду пулл-реквест

**Comment by artbear** [comment]
Сделал все, кроме смены версии в файле сконвертированного теста

Пока не реализован #592 при конвертации использую `ГенераторТестовыхДанных.РазложитьСтрокуВМассивПодстрок()` вместо `юТест.РазложитьСтрокуВМассивПодстрок()`

**Comment by bf0rce** [comment]
Спасибо за оперативное исправление. Все преобразовывается, кроме юТест.ПрерватьТест(). Но он у меня всего в одном месте, поэтому я руками поправил.

**Comment by artbear** [comment]
>Все преобразовывается, кроме юТест.ПрерватьТест()

Исправил.

Также исправил "В Конфигураторе 1С при сравнении исходного файла теста и сконвертированного теста нельзя было увидеть отличия, хотя они есть"

**Comment by artbear** [comment]
@awa15 
>@artbear , версии хранятся в файле versions. Там простой формат
```
{1,<Число N - количество записей о версиях>,<Строка Имя файла 1>,<UUID Версия файла 1>,...,<Строка Имя файла N>,<UUID Версия файла N>}
```
Можно попробовать файл versions просто писать таким
```
{1,0}
```
так как 1С, вроде бы, нормально относится к тому, что версии файлов не указаны совсем.

Спасибо большое - ты как всегда очень точно отвечаешь!

Твой совет сработал, исправление заняло минут 10 (с учетом прогона тестов) :)

**Comment by artbear** [comment]
@bf0rce Проверишь.

ИМХО все проблемы решены.
Закроешь issue?

**Comment by bf0rce** [comment]
Спасибо за помощь!
