### ISSUE TITLE
Плагин СтроковыеУтилиты

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#592]
Предлагаю портировать из oscript-library/src/strings/СтроковыеФункции.os
Появился в https://github.com/xDrivenDevelopment/xUnitFor1C/issues/590#issuecomment-176292788

Реализацию взял на себя @bf0rce

**Comment by bf0rce** [comment]
А тесты на строковые функции нужны?

**Comment by artbear** [comment]
Да, очень хотелось бы получить и тесты

**Comment by artbear** [comment]
Хотя бы по одному простейшему тесту на каждую публичную функцию

**Comment by bf0rce** [comment]
Принято)

**Comment by artbear** [comment]
@bf0rce ИМХО в описании каждой функции есть примеры.
Вот их и нужно вставить в тест :)

**Comment by karnilaev** [comment]
Плагин не позволяет загрузить тестраннер ни в тонком, ни в толстом клиенте на версии платформы 8.2.

**Comment by bf0rce** [comment]
Вижу три варианта.

- Удалить неподдерживаемый в 8.2 конструктор ФорматированнаяСтрока, вместе с функцией, которая его использует.

- Обернуть конструктор ФорматированнаяСтрока в метод Выполнить(), а перед выполнением проверять на версию платформы. Если версия < 8.3.3, то обходиться совсем без форматированных строк. Это будет некоторая деградация функции, но ошибку исправит.

- И, третий вариант такой. Поскольку метод СтроковыеУтилиты.ФорматированаяСтрока как бы намекает, что на выходе мы должны получить форматированную строку, то использование его в версии < 8.3.3 должно быть не доступно. Это значит, что в самом начале функции нужно проверять версию и выбрасывать исключение, если форматированная строка не поддерживается платформой. Метод Выполнить() тут также будет использоваться, но лишь для исключения синтаксических ошибок в 8.2.

@artbear, что скажешь?

**Comment by artbear** [comment]
3-й вариант ИМХО наиболее правильный.
Если функционал не работает, лучше выбрасывать исключение

**Comment by artbear** [comment]
@bf0rce Поправить сможешь?

**Comment by bf0rce** [comment]
Да, поправлю.
