### ISSUE TITLE
Проблемы с использованием точек маршрута бизнес-процессов при создании тестовых данных

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#595]
Описание проблемы от @MikolaKar (в терминах тестовой базы продукта)
Есть БизнесПроцесс1. У него есть карта маршрута с Действие1, где Действие1 это Имя, по которому будет выполняться обращение к точке маршрута в алгоритме модуля.
Теперь создаем еще один БизнесПроцесс2. У него будет своя карта маршрута. В ней также может быть Действие1.
Понятно, Действие1 БП1 <> Действие1 БП2, т.к. это разные процессы, только с одинаковым названием точек маршрутов.
В ЗадачаИсполнителя есть стандартные реквизиты ТочкаМаршрута и БизнесПроцесс, по которым мы можем судить о том, где в данный момент находится задача.
Если я хочу в макете создать задачу, которая бы располагалась в точке Действие1 БП2, то я в реквизитах задачи ставлю
Действие1 (Предопределенный) и БизнесПроцесс БизнесПроцесс2 (Перем). Когда в коде проверяю точку маршрута задачи, оказывается, что она равна Действие1, но из БП1.
В коде сравнение точки маршрута происходит таким образом:
ЗадачаИсполнителя.ТочкаМаршрута = БизнесПроцессы.БизнесПроцесс2.ТочкиМаршрута.Действие1.
Получается, что при создании точки маршрута у задачи необходимо учитывать к какому БП она относится, т.к. у каждого
БП свой маршрут со своими точками, а наименования точек у разных маршрутов могут совпадать.
Для примера, в Документообороте есть 2 различных БП: Ознакомление и Согласование. И там, и там есть точка Ознакомиться, но обращаемся к точкам по разному:
БизнесПроцессы.Ознакомление.ТочкиМаршрута.Ознакомиться и БизнесПроцессы.Согласование.ТочкиМаршрута.Ознакомиться

**Comment by artbear** [comment]
Подтверждаю проблему при использовании одинаковых имен точек маршрутов в разных бизнес-процессов.
Есть простое решение:
В макете в колонке `"Режим"` можно использовать режим `"Выражение"`, тогда в поле `Значение` нужно подставлять точную ссылку на точку маршрута определенного бизнес-процесса
Например, `БизнесПроцессы.БизнесПроцесс2.ТочкиМаршрута.Действие1`

Вот скриншот макета из работающего теста:
![image](https://cloud.githubusercontent.com/assets/2920817/12754324/d63a10a2-c9db-11e5-8bd5-c8bef289621c.png)

**Comment by artbear** [comment]
@MikolaKar у меня при подобном исправлении макета твой тест стал зеленым :)
Что скажешь?

**Comment by artbear** [comment]
Пример теста выложен и в ветке develop (версия 3), и в ветке develop_v4_reborn (версия 4)

**Comment by MikolaKar** [comment]
Да, отлично, спасибо. Я упустил из виду, что можно было еще использовать и такой вариант.
