### ISSUE TITLE
Генератор макета неверно именует переменные больше 999

### ISSUE THREAD

**Issue by nalsa** [xDrivenDevelopment/xUnitFor1C#604]
Если наименование нумерованных переменных доходит до 1000, 
то в макете записывается: "1 000". Из за знака разделения разрядов не возможно в дальнейшем загрузить такой макет.
![2016-03-18_12-47-38](https://cloud.githubusercontent.com/assets/9250186/13874322/3b131d08-ed08-11e5-9003-da23a1b33444.png)
![2016-03-18_12-47-00](https://cloud.githubusercontent.com/assets/9250186/13874323/3b12ed4c-ed08-11e5-87a1-206d5e396f34.png)
![2016-03-18_12-47-17](https://cloud.githubusercontent.com/assets/9250186/13874321/3b117a5c-ed08-11e5-951c-dc0866c747fa.png)

**Comment by artbear** [comment]
На какой версии выявлено подобное поведение?

**Comment by artbear** [comment]
ИМХО подобную ошибку я уже увидел и ИМХО исправлял.

**Comment by nalsa** [comment]
версия 3.0.0.3

**Comment by artbear** [comment]
Исправлено в #636 для версии 4.1.Х
