### ISSUE TITLE
Плагин "Загрузчик каталога", ошибка при подключении обработки для различных клиента и сервера.

### ISSUE THREAD

**Issue by pumbaEO** [xDrivenDevelopment/xUnitFor1C#610]
### Предварительно

* [ x ] Вы используете [последнюю версию продукта](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop)  ?
* [ x ] Вы проверили [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8) ?

## Описание
При загрузке тестов в случаи различного сервера и клиента, при этом когда сервер не имеет доступа к внешней обработке с тестом, тогда происходит ошибка подключения. 

**Укажите:**
* reborn 4.0.4
* 8.3.8-1502
* управляемое приложение, тонкий клиент, настройка модальности "Разрешить с предупреждением"

**Comment by artbear** [comment]
Баг поправил. Предыдущая версия на моем окружения клиента-сервера падала, сейчас не падает.
@pumbaEO проверь у себя, жду.

**Comment by artbear** [comment]
Исправлено в 4.0.0.5
