### ISSUE TITLE
Ошибка при загрузке списка тестов в режиме отключенных модальных окон

### ISSUE THREAD

**Issue by KrapivinAndrey** [xDrivenDevelopment/xUnitFor1C#613]
## Описание

При загрузке тестов в интефейсе Такси с отключенными модальными окна выходит ошибка и тесты не загружаются.
Проверка на Рознице 2.2.2.14 - текущий актуальный релиз.

** Шаги для воспроизведения **

1. Открываем xddRunner.
2. Загружаем типовой тест 2+2=4.

**Ожидаемое поведение:** Должно заполнится дерево тестов.

**Текущее поведение:** Ошибка при вызове метода ПоместитьФайл. Использование модальных окон запрещено

* Розница 2.2.2.14
* 8.3.7.1949
* Управляемое приложение толстый/тонкий клиент

Предполагаемое решение: http://1c.chistov.pro/2013/07/blog-post.html

**Comment by artbear** [comment]
Спасибо за информацию о проблеме.

Пока работа в режиме отключенных модальных окон не реализовано.
Доработка будет выполнена в очередном релизе или следующем после него.

**Comment by artbear** [comment]
Для решения проблемы до внесения указанных изменения
предлагаю 
+ использовать версию 3.Х 
+ или включить использование модальных окон.

**Comment by KrapivinAndrey** [comment]
Спасибо. База типовая так что отключать не хочется. А тесты уже есть готовые. Если сделаю исправление отпишусь.

**Comment by a-sitnikov** [comment]
код исправления

&НаКлиенте
Процедура ПодключитьВнешнююОбработку(ФайлОбработки) Экспорт
	Если ПодключенныеВнешниеОбработки.Получить(ФайлОбработки.ИмяБезРасширения) = Неопределено Тогда
		
		ЭтоОтчет = (НРег(ФайлОбработки.Расширение) = ".erf");
		АдресХранилища = "";
		
		//Ситников++
		ДополнительныеПараметры = Новый Структура;
		ДополнительныеПараметры.Вставить("ЭтоОтчет", ЭтоОтчет);
		
		ОписаниеОповещения = Новый ОписаниеОповещения("НачатьПомещениеФайлаОкончание", ЭтаФорма, ДополнительныеПараметры);
		НачатьПомещениеФайла(ОписаниеОповещения, АдресХранилища, ФайлОбработки.ПолноеИмя, Ложь, ЭтаФорма.УникальныйИдентификатор); 
		Возврат;
		//ПоместитьФайл(АдресХранилища, ФайлОбработки.ПолноеИмя, , Ложь, ЭтаФорма.УникальныйИдентификатор);
		//Ситников--
		
		ПодключитьФайлОбработкиНаСервере(АдресХранилища, ФайлОбработки.ИмяБезРасширения, ЭтоОтчет);
		
		ПодключенныеВнешниеОбработки.Вставить(ФайлОбработки.ИмяБезРасширения, Истина);
	КонецЕсли;
КонецПроцедуры

//Ситников++
&НаКлиенте
Процедура НачатьПомещениеФайлаОкончание(Результат, АдресХранилища, ВыбранноеИмяФайла, ДополнительныеПараметры) Экспорт
	
	ФайлОбработки = Новый Файл(ВыбранноеИмяФайла);
	
	ПодключитьФайлОбработкиНаСервере(АдресХранилища, ФайлОбработки.ИмяБезРасширения, ДополнительныеПараметры.ЭтоОтчет);
	ПодключенныеВнешниеОбработки.Вставить(ФайлОбработки.ИмяБезРасширения, Истина);
	
КонецПроцедуры

**Comment by artbear** [comment]
@a-sitnikov После этой правки загрузка тестов начинает работать, верно?
А выполнение тестов будет работать?

**Comment by artbear** [comment]
Выполнено в #644
