### ISSUE TITLE
Проведение тестов через обработчик ожидания

### ISSUE THREAD

**Issue by a-sitnikov** [xDrivenDevelopment/xUnitFor1C#615]
Я хочу выполнить такой тест:
Открыть форму и нажать кнопку.
Вся загвоздка в том, что мне нужно нажать кнопку только после полного открытия формы, то бишь в обработчике ожидания после открытия.

Но testRunner не умеет асинхронно выполнять тесты. Те он не будет ожидать выполнения всех моих подключенных оработчиков, а просто скажет что тест прошел.

Можно конечно использовать менеджер тестирования, но это требует запуска отдельного экземпляра 1с, что не всегда удобно

Есть ли какие-нибудь способы решения вопроса или подвижки в разработке на эту тему?
Например в  нагрузочном тестировании от 1С, такой механизм реализован

**Comment by yuriybylinkin** [comment]
Толстая форма?
29 марта 2016 г. 17:51 пользователь "Anatoliy Sitnikov" <
notifications@github.com> написал:

**Comment by pumbaEO** [comment]
Пауза?

**Comment by a-sitnikov** [comment]
УФ.
Суть в том что послать нажатие кноки через SendKeys можно только для уже открытой формы.
Но простое ОткрытьФорму еще не успевает ее открыть

**Comment by a-sitnikov** [comment]
Пауза тоже не подойдет. Так как пока выполняется код, форма не открывается

**Comment by yuriybylinkin** [comment]
Можете привести пример теста?
07 апр. 2016 г. 17:19 пользователь "Anatoliy Sitnikov" <
notifications@github.com> написал:

**Comment by artbear** [comment]
У меня давно была идея об асинхронном запуске тестов. Также есть идея с
запуском тестов в несколько потоков

чт, 7 Апр 2016, 18:35 Юрий Былинкин <notifications@github.com>:

**Comment by a-sitnikov** [comment]
Пример теста:
Конфигурация ЕРП.
Формирование заказов на перемещение по потребностям.
Нужно последовательно нажать далее 4 раза
