### ISSUE TITLE
Ошибка при конвертации тестов с xUnitFor1C 3.0.0.5 на 4.0.0.6

### ISSUE THREAD

**Issue by MihailovAlexander** [xDrivenDevelopment/xUnitFor1C#616]
1С:Предприятие 8.2 (8.2.19.83)
"Управление торговлей", редакция 10.3 (10.3.12.3) 

Ошибка при конвертации тестов с xUnitFor1C 3.0.0.5 на 4.0.0.6

C:\Users\КалининДИ\Desktop\Иванов\Группа тестов для конвертации\xUnit_ТестированиеПодсистемыРитейл_v2.epf : {ВнешняяОбработка.xddTestsConvertIntoRebornFormat.МодульОбъекта(186)}: Ошибка при вызове конструктора (ЧтениеТекста)

Текст = Новый ЧтениеТекста(Файл.ПолноеИмя, КодировкаТекста.UTF8);

C:\Users\КалининДИ\Desktop\Иванов\Группа тестов для конвертации\xUnit_ТестированиеПодсистемыРитейл_ВнЗаказ_v2.epf : {ВнешняяОбработка.xddTestsConvertIntoRebornFormat.МодульОбъекта(186)}: Ошибка при вызове конструктора (ЧтениеТекста)

  Текст = Новый ЧтениеТекста(Файл.ПолноеИмя, КодировкаТекста.UTF8);

Найдено внешних обработок - 0 шт.

Найдено файлов-тестов в старом формате - 0 шт.

Конвертировано в новый формат тестов - 0 шт.

**Comment by artbear** [comment]
Сам исходный файл теста ( `xUnit_ТестированиеПодсистемыРитейл_v2.epf` ?) мне на мыло сможешь прислать?

**Comment by MihailovAlexander** [comment]
Да, отправил

**Comment by MihailovAlexander** [comment]
Спасибо
