### ISSUE TITLE
Дымовые тесты, в чем необходимость пропуска для УФ

### ISSUE THREAD

**Issue by pumbaEO** [xDrivenDevelopment/xUnitFor1C#617]
В чем необходимость пропуска управляемых форм? 
https://github.com/xDrivenDevelopment/xUnitFor1C/blob/develop/src/Tests/Smoke/%D1%82%D0%B5%D1%81%D1%82%D1%8B_%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5%D0%A4%D0%BE%D1%80%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/ObjectModule.bsl#L296

**Comment by artbear** [comment]
@pumbaEO 
Там сверху написано
`ИспользоватьУФ = Метаданные.ИспользоватьУправляемыеФормыВОбычномПриложении;`
Соответственно, если этот флаг в конфигурации выключен, УФ нет смысла открывать, т.к. они все равно не откроются или откроются пустыми (без выполнения обработчиков)
```
ИспользоватьУФ = Метаданные.ИспользоватьУправляемыеФормыВОбычномПриложении; // !!
	МетаФормы = Новый Массив();
	Для Каждого ИмяОсновнойФормы Из ИменаОсновныхФорм Цикл
		Попытка
			МетаФорма = МетаОбъект[ИмяОсновнойФормы];
		Исключение
			Продолжить;
		КонецПопытки;
		Если МетаФорма = Неопределено Тогда
			Продолжить;
		КонецЕсли; 
		Если МетаФормы.Найти(МетаФорма) <> Неопределено Тогда
			Продолжить;
		КонецЕсли; 
		Если НЕ ИспользоватьУФ И МетаФорма.ТипФормы = Метаданные.СвойстваОбъектов.ТипФормы.Управляемая Тогда
			Продолжить;
		КонецЕсли;
		МетаФормы.Добавить(МетаФорма);
	КонецЦикла;
	Возврат МетаФормы;```

**Comment by pumbaEO** [comment]
В зависимости от режима совместимости этой настройки в новых версиях нет http://prntscr.com/aujqnl

**Comment by Irekovich** [comment]
А так?
[image: Inline images 1]

**Comment by pumbaEO** [comment]
Да, так показывает. Но это не объясняет почему он откроются пустыми. Т.к. для той же ERP эти флаги стоят и в управляемом режиме все открывается и запускается. 
http://prntscr.com/aukc5i

**Comment by artbear** [comment]
@pumbaEO 
>Но это не объясняет почему он откроются пустыми. Т.к. для той же ERP эти флаги стоят и в управляемом режиме все открывается и запускается. 

Я уже писал выше, что указанный код работает в толстом режиме ОФ, а не в управляемом режиме. В этом режиме **нет смысла открывать УФ**, если в конфигурации нет упоминаемого флага.

Или я что-то не знаю?

**Comment by artbear** [comment]
@pumbaEO Вопрос решен, закрываем?

**Comment by naa4sb** [comment]
ИспользоватьУФ = Ложь
ТекущийРежимЗапуска() = Управляемое приложение
настройки конфигурации такие
http://take.ms/ZFMQa

Из-за этого все управляемые формы пропускаются:
```
		Если НЕ ИспользоватьУФ И МетаФорма.ТипФормы = Метаданные.СвойстваОбъектов.ТипФормы.Управляемая Тогда
			Продолжить;
		КонецЕсли;
```
Или я что-то не так запускаю?

**Comment by artbear** [comment]
@naa4sb Ага, теперь понял проблему. Подумаю, как поправить

**Comment by naa4sb** [comment]
@artbear пока вот так работает,
`	ИспользоватьУФ = Метаданные.ИспользоватьУправляемыеФормыВОбычномПриложении ИЛИ (ТекущийРежимЗапуска() <> РежимЗапускаКлиентскогоПриложения.ОбычноеПриложение);
`

**Comment by artbear** [comment]
@naa4sb Сможешь пулл-реквест сделать?

**Comment by das999** [comment]
я - нуб, но попробую) тестов вот только не обещаю, хотя теоретически в
новых версиях платформы поведение метода ТекущийРежимЗапуска() может
измениться, и это надо тестить.

2016-06-06 21:15 GMT+03:00 Artur Ayukhanov <notifications@github.com>:

**Comment by naa4sb** [comment]
@artbear Немножко вопросов)
1) Прогнал тесты на cf до внесения своих изменений
Запущено тестов - 288, ошибочных тестов - 0, не прошло проверку - 0, пропущено - 1
ТестДолжен_ПроверитьРавенствоФайловСУчетомПереданныхПараметровСравнения, путь C:\GIT\naa4sb\xUnitFor1C\Tests\Plugins\ТестыПроверитьРавенствоФайлов.epf
Отсутствует реализация тестового метода (ТестДолжен_ПроверитьРавенствоФайловСУчетомПереданныхПараметровСравнения).
Не обращать внимания?
2) Надо ли менять минорную версию xddTestRunner с учетом того, что изменяется совсем другая epf? Или версия xddTestRunner  - это версия всего продукта в целом, а не конкретно обработки xddTestRunner, и ее надо менять, если меняется какая-то часть продукта?

**Comment by artbear** [comment]
@naa4sb 
+ Да, `ТестДолженПроверитьРавенствоФайловСУчетомПереданныхПараметровСравнения)` пропускаем.
+ версия браузере - это как версия всего продукта. менять не нужно.
+ ты сохранял файлы только в 8.3 или в 8.2 ?
+ Тесты прогонял на УФ (тонкий и толстый) и ОФ ? :)

**Comment by artbear** [comment]
Командой `git diff develop YPermitin/develop-ypermitin --name-only *.bsl`
смотрим все изменения модулей между твоей и общей веткой
все остальные файлы (внешние обработки и исходники) нужно откатить
```
src/Plugins/ГенераторОтчетаMXL/ObjectModule.bsl
src/Plugins/ЗагрузчикИзПодсистемКонфигурации/Form/УправляемаяФорма/Форма.bsl
src/Plugins/ЗагрузчикКаталога/ObjectModule.bsl
src/Plugins/ЗагрузчикФайла/Form/Форма/Форма.bsl
src/Plugins/ЗагрузчикФайла/ObjectModule.bsl
src/Plugins/ПарсерКоманднойСтроки/ObjectModule.bsl
src/Plugins/СтроковыеУтилиты/ObjectModule.bsl
src/PluginsTemplates/ШаблонГенератораОтчета/Form/Форма/Форма.bsl
src/PluginsTemplates/ШаблонГенератораОтчета/ObjectModule.bsl
src/PluginsTemplates/ШаблонЗагрузчика/Form/Форма/Форма.bsl
src/PluginsTemplates/ШаблонЗагрузчика/ObjectModule.bsl
src/PluginsTemplates/ШаблонУтилиты/Form/Форма/Форма.bsl
src/PluginsTemplates/ШаблонУтилиты/ObjectModule.bsl
src/Tests/Core/Тесты_ЗапускВПакетномРежиме/ObjectModule.bsl
src/Tests/Core/Тесты_СистемаПлагинов/Form/Форма/Форма.bsl
src/Tests/Core/Тесты_СистемаПлагинов/ObjectModule.bsl
src/Tests/Gui83/юнитТест_UI_83/Form/Форма/Форма.bsl
src/Tests/Plugins/Тесты_ГенераторОтчетаJUnitXML/ObjectModule.bsl
src/Tests/Plugins/Тесты_ГенераторОтчетаMXL/ObjectModule.bsl
src/Tests/Plugins/Тесты_ЗагрузчикФайла/Form/Форма/Форма.bsl
src/Tests/Plugins/Тесты_ЗагрузчикФайла/ObjectModule.bsl
src/Tests/Utils/Тест_КонвертацияТестов_в_версию4/ObjectModule.bsl
src/Utils/xddTestsConvertIntoRebornFormat/ObjectModule.bsl
src/xddTestRunner/Form/УправляемаяФорма/Форма.bsl
src/xddTestRunner/Form/Форма/module.bsl
src/xddTestRunner/ObjectModule.bsl
```

**Comment by artbear** [comment]
А с этими файлами нужно разобраться и устранить ненужные изменения.

**Comment by naa4sb** [comment]
@artbear Это не мои изменения, а Юры Пермитина)
По моим получается строчка кода изменений в дымовом, если версию в браузере тестов не надо менять.
С тестами каюсь, схалтурил, ибо руками пока) Только 8.3.8, тонкий и УФ. Прогоню по остальным)
Вопрос: имеет значение в какой версии платформы сохраняется измененный бинарник (epf)? Если имеет, то в какой надо сохранять? Сейчас была 8.3.8.

**Comment by nixel2007** [comment]
@naa4sb 
> Вопрос: имеет значение в какой версии платформы сохраняется измененный бинарник (epf)? Если имеет, то в какой надо сохранять? Сейчас была 8.3.8.

Да, имеет. Надо сохранять на 8.2, так как 8.3 сохраняет картинки в обычных формах не так, как было до 8.2.19. Заявленная же поддержка начинается от 8.2.14

**Comment by rsyuzyov** [comment]
@nixel2007 Извините, дяденьки, что встреваю, но
![image](https://cloud.githubusercontent.com/assets/7994115/15898821/1bc80b98-2db3-11e6-8162-7e1ad804c161.png)
И имхо пора поднять хотя бы до 8.2.19...

**Comment by nixel2007** [comment]
@rsyuzyov да ладно уж, дяденька...)

Это вопрос к @artbear 

На мой взгляд, если люди, сидящие на 8.2 (sic!) до сих пор не перешли на 8.2.19 (sic!), то им можно вообще ничего не тестировать, и так все плохо.

**Comment by rsyuzyov** [comment]
Ну вот и я о чем :)

**Comment by rsyuzyov** [comment]
Призываю @artbear - допустимо ли?

**Comment by allustin** [comment]
@nixel2007 я просто также оставлю это здесь

с точки зрения денег - лучше потратить время (деньги) на перевод конфигурации на более старшую платформу, чем на покрытие тестами. с точки зрения бизнеса и здравого смысла - это будет эффективней.

**Comment by YPermitin** [comment]
@nixel2007 все же с 8.2.14?

Вчера проверил, с этой версии точно не работает. В PR #622 в конце отписался по ошибкам, которые нашел на первых порах.

**Comment by artbear** [comment]
ИМХО Совместимость с 8.2.17 пусть пока остается.
Усилия по ее поддержке минимальны, только сохранять файлы в 8.2.19, а не в 8.3
