### ISSUE TITLE
Встроить фреймворк в состав конфигурации

### ISSUE THREAD

**Issue by YPermitin** [xDrivenDevelopment/xUnitFor1C#619]
**Изначально xUnitFor1C имел возможность внедрения в состав конфигурации и использование его уже оттуда. Однако, в период развития эта возможность "отпала".** 

Сейчас при попытке встроить его в конфигурацию появляется множество ошибок, связанных с отсутствием плагинов и утилит (они находятся в других каталогах как отдельные отчеты и обработки).

Предлагаю исправить этот недочет, т.к. использование фреймворка, встроенного в состав конфигурации, иногда более предпочтителен.

В работе использую xUnitFor1C, уже несколько адаптировал его для того, чтобы встраивать в состав конфигурации, но не считаю свое решение универсальным. Хотел бы здесь обсудить решение, чтобы сделать  сразу для pull-request'а =)

**Мое решение:**
При запуске браузера тестов делается проверка - запущена внешняя обработка или встроенная в конфигурацию. В дальнейшем результат проверки используется в процедурах получения плагинов, утили, в команде перезапуска браузера тестов, в период создания и открытия формы для инициализации настроек.

Самым "сомнительным" с моей точки зрения решением оказалось встраивание плагинов и утилик в качестве макетов во внешнюю обработку (см. скриншот).
![default](https://cloud.githubusercontent.com/assets/4200891/15446424/141f0338-1f3a-11e6-93e3-7351a2ee6bba.PNG)

Если обработка встроена в конфигурацию, то вместо каталогов плагинов и утилиты обработка получает их из макетов и сохраняет во временный каталог. После чего работа уже ведется с ним.

Делал все это пока только для управляемого интерфейса. Если вариант с макетами подходит, то реализую для обычных форм и отправлю p-r. 
Но решение, еще раз повторю, не считаю универсальным. По мне правильней, например, при встраивании создавать константу и загружать плагины и утилиты туда. При запуске проверять наличие константы. При первом запуске, когда константа еще не инициализирована, предупредить пользователя и попросить указать каталоги с плагинами и утилитами для загрузки.

Вообщем, ваше мнение =)

**Comment by artbear** [comment]
@YPermitin да, ИМХО сомнительное решение - хранить плагины в макетах.
В случае изменений в них очень сложно выполнять код-ревью, также сложно разбирать на исходники.
А почему ты не выбрал простейшее решение в виде использования спец.подсистемы (например, xUnitFor1C) c вложенными подсистемами аналогично файловой системе (например, xUnitFor1C.Plugins, xUnitFor1C.Utils и т.п.) ?

**Comment by artbear** [comment]
@YPermitin и соответственно, плагины храним в виде встроенных обработок, включенных в соответствующие подсистемы.

**Comment by YPermitin** [comment]
@artbear изначально была задача встроить обработку с минимальными изменениями конфигурации без каких-бы то не было объектов.

К тому же сейчас браузер тестов и сами тесты сделаны таким образом, что ищут плагины, файлы тестов и т.д. в каталоге браузера тестов. В случае создания подсистемы пришлось бы все это переделывать, здесь вопрос в затраченном времени.

Конечно, использование подсистемы это элегантное решение, но изначально я предпологал, что встраивание браузера тестов должно требовать минимум действий: вставил обработку и все.

# Решение с подсистемами
Раз вариант с макетами плох в части поддержки, то сделаю вариант с подсистемами.
Как на счет такой структуры:
![image](https://cloud.githubusercontent.com/assets/4200891/15553688/b0f01646-22d9-11e6-905c-22d3d1e651c7.png)

Сам браузер тестов будет находится на верхнем уровне системы, остальные обработки будут во вложенных.

В подсистеме Tests добавлю вложенную подсистему Internall, куда будут входить тесты самого фреймворка.
В дальнейшем предполагаю, что в подсистему Tests разработчики будут добавлять свои подсистемы со своими тестами.

Остальное это переделать процедуры получения тестов из подсистем, вместо макетов.

# Вопросы
1. Нужно ли включать в подсистему xUnitFor1C шаблоны плагинов?
2. Как быть с пакетным запуском xUnitFor1C для встроенной обработки? В том плане, что запуск встроенной обработки с параметрами запуска ИБ не получится сделать. Тут вижу несколько вариантов, но сначала хотелось бы услышать как это решали до того, как исчезла поддержка встраивания в конфигурацию.
3. Если развивать дальше внедрения фреймворка как подсистемы, то может сразу обсудить добавление для подсистемы ролей и т.д.? Стоит ли это делать или оставить все на усмотрение внедряющего?)

**Comment by artbear** [comment]
@YPermitin Да, я говорил о подобной схеме организации при встраивании в конфу.
Один момент - встроенные тесты самого xUnitFor1C не нужно встраивать, пусть остаются внешними. В конфигурацию нужно встраивать только то, что понадобится разработчику тестов - браузер тестов, плагины, утилиты.
Т.е. подсистема Tests будет нужна конкретному разработчику тестов для помещения собственных тестов.

По вопросам:
1 шаблоны плагинов встраивать не нужно
2 Пакетный запуск для встроенных тестов мы делали через спец.обработку-заглушку, которая при открытии просто вызывала встроенный браузер. Посмотри в ветке 3.Х (находится рядом с браузером)
3 дополнительные вопросы предлагаю обсуждать в отдельном issue. здесь только те вопросы, что касаются встраивания системы тестирования.

Спасибо за столь развернутый ответ. Ради него можно было и подождать :)

**Comment by YPermitin** [comment]
@artbear Окей, в ближайшие дни постараюсь сделать реализацию на подсистемах.

**Comment by YPermitin** [comment]
@artbear Вариант реализации с подсистемой в pull-request'е.

Но у меня все же предложение, почему бы не сделать что-то вроде "portable"-версии обработки браузера тестов, в которой будет встроены необходимые плагины и утилиты. Возможно с поддеркой такого варианта будет сложнее, но это ведь куда удобнее работать с одним файлом.

Можно что-нибудь придумать для автообновления содержимого макетов с обработками.Сейчас для себя оставил такой вариант:
![image](https://cloud.githubusercontent.com/assets/4200891/15800093/f2a1a69c-2a89-11e6-8722-e654cbb23324.png)

Один файл и нет проблем =)
Может такую реализацию в отдельной ветке сделать =)))
