### ISSUE TITLE
"Генератор макетов данных" не работает, если "вариант встроенного языка" - английский

### ISSUE THREAD

**Issue by poabor** [xDrivenDevelopment/xUnitFor1C#627]
## Описание

Если у конфигурации, свойство "Вариант встроенного языка" стоит "Английский", то обработка вываливается с ошибкой:
![image](https://cloud.githubusercontent.com/assets/15695218/16338657/bdf42a62-3a26-11e6-8f23-9f5be281b901.png)

Не воспринимает свойство "Ссылка", ожидает "Ref".

**Укажите:**
- [ версия продукта] 1C:Small Business 1.4.7
- [ версию платформы 1С ] 8.3.7.1790
- [ управляемое приложение, тонкий клиент]

**Comment by artbear** [comment]
Да, продукт пока не планировался для работы с другими языками.

А прогон тестов работает в английском окружении ? Не работает только генератор?

**Comment by poabor** [comment]
да, тесты работают.

**Comment by poabor** [comment]
я решил этот вопрос у себя. 
Создал соответствие русского и английского. При обращении, в зависимости от языка, возвращается нужное значение.
Тесты прогоню и отправлю pull request.

**Comment by artbear** [comment]
Спасибо. Жду

**Comment by artbear** [comment]
Выполнено в #628
