### ISSUE TITLE
Табличная часть ПользователиИБ плагина СериализаторMXL имеет ограничение в 10 символов для реквизита Имя

### ISSUE THREAD

**Issue by naa4sb** [xDrivenDevelopment/xUnitFor1C#629]
## Используется

https://github.com/xDrivenDevelopment/xUnitFor1C/commit/b0206440009f301ce6cdf14586d7803e05c67f0f
## Описание

Табличная часть ПользователиИБ плагина СериализаторMXL(\Plugins\СериализаторMXL.epf) имеет ограничение в 10 символов для реквизита Имя

*\* Шаги для воспроизведения **
1. Создать в ИБ пользователя с именем длиннее 10 символов. Например, "Администратор"
2. Открыть в режиме предприятия обработку СериализаторMXL. Перейти на закладку "Пользователи ИБ"
3. Выбрать строку с пользователем, созданным на шаге 1.
4. Нажать кнопку "Создать макет данных"
5. Получить ошибку "Не найден пользователь ИБ по имени <Администра>"

**Ожидаемое поведение:** Формирование макета данных по любому пользователю ИБ вне зависимости от длины имени.

**Текущее поведение:** Нет возможности выгрузить в макет пользователей ИБ с длиной имени больше 10 символов.

**Comment by artbear** [comment]
@poabor Сможешь поправить эту проблему в рамках своего PR #628 #627 ?

**Comment by poabor** [comment]
ок.

**Comment by artbear** [comment]
Исправлено еще в 28 Июня :)
