### ISSUE TITLE
Устаревшая версия утилиты "Преобразование действий пользователя"

### ISSUE THREAD

**Issue by YPermitin** [xDrivenDevelopment/xUnitFor1C#632]
## Описание
Утилита "Преобразование действий пользователя", поставляемая с фрейморком, имеет неактуальную.

* Версия xUnitFor1C: 4.0.0.6

После получения записи последовательности действий пользователя и попытке преобразования в код или тест, появляется ошибка:
![image](https://cloud.githubusercontent.com/assets/4200891/16547031/bcdccd5c-4177-11e6-83d4-c1a8acbfbb3b.png)

Пример сгенерированного XML:
[logui.zip](https://github.com/xDrivenDevelopment/xUnitFor1C/files/345235/logui.zip)

** Шаги для воспроизведения **
Достаточно взять текст из приложеного XML и вставить в утилиту для преобразования.
![image](https://cloud.githubusercontent.com/assets/4200891/16547041/259b8752-4178-11e6-82ad-65b496e8d1af.png)

Это не единственная ошибка. Существует множество неизвестных атрибутов для текущей версии утилиты.

**Ожидаемое поведение:**
Нужно обновить версию утилиты с помощью последней версии обработки с ИТС с учетом добавленного функционала.

**Текущее поведение:** 
Утилита не может обрабатывать запись действий пользователей для новых версий платформы.

**Укажите:**
* xUnitFor1C: 4.0.0.6
*  1С:Предприятие 8.3.7 и выше (возможно ошибка актуальна и для старых версий)
 * управляемое приложение, тонкий/толстый клиент

## Также приветствуется описание в формате Gherkin
Пока без него =)

**Comment by YPermitin** [comment]
@artbear Если я правильно понял утилита была сделана на базе типовой обработки? Можно старую типовую обработку, которую брали за основу, получить. 

Хочу сравнить какие изменения сделали, чтобы их на новую версию перенести.

**Comment by artbear** [comment]
@YPermitin Напомни, ты обновил эту утилиты в своих PR ? английская версия уже залита в ветку develop ?

**Comment by YPermitin** [comment]
@artbear еще пока не успел этим заняться. Хочу поскорее залить. Думаю что до вторника сделаю.

**Comment by YPermitin** [comment]
Думаю, что проблема решена.
PR замержен.
