### ISSUE TITLE
Plugin:ЗагрузчикФайла не загружает тесты из внешних *отчетов*.

### ISSUE THREAD

**Issue by pumbaEO** [xDrivenDevelopment/xUnitFor1C#633]
### Предварительно

* [ x ] Вы используете [последнюю версию продукта](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop)  - Да
* [ x ] Вы проверили [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8) - Да 

## Описание

При написание тестов во внешнем отчете, не подгружает тестовые случаи. 

**Шаги для воспроизведения**

1. Создать внешний отчет. 
2. Прописать экспортные функции для загрузки тестов
3. В режиме предприятия в xUnitfor1c указать загрузку из каталога и ничего не появилось.

**Ожидаемое поведение:** должны загрузиться тесты из erf файла и выполнится.

**Текущее поведение:** сейчас при создании объекта не анализируется внешняя обработка это или отчет, в результате для файла erf не может создать ВнешниеОбработки.Подключить()

**Укажите:**
*  Запуск управляемое приложение, тонкий клиент.

**Comment by YPermitin** [comment]
@pumbaEO исправлял этот момент для себя, но PR не стал делать.
Могу залить изменения в уже существующий pull-request #631.

**Comment by pumbaEO** [comment]
Давай, ибо тестировать правильность формирования СКД шных вариантов отчета со всякими изменениями метаданных надо очень, очень.

**Comment by YPermitin** [comment]
@pumbaEO отправил изменения в рамках уже созданного мной pull-request'а. Он давно висит, сразу адаптировал изменения под этот PR.

Теперь доступна работа с отчетами (внешними и встроенными в конфигурацию):
![default](https://cloud.githubusercontent.com/assets/4200891/16710092/bba1ee00-4612-11e6-9ac2-04370f7c2c97.PNG)

Тесты прогонял, все ок. Дальше уже смотри. Это ли нужно было =)

**Comment by YPermitin** [comment]
@pumbaEO Думаю Issue можно закрывать или еще какие-то доработки будем вносить?
