### ISSUE TITLE
Добавление произвольных дополнительных свойств к объектам, выгружаемым с помощью Сериализатора MXL

### ISSUE THREAD

**Issue by SonicNorg** [xDrivenDevelopment/xUnitFor1C#634]
### Предварительно

* [x] Вы используете [последнюю версию продукта](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop)  ?
* [x] Вы проверили [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8) ?

## Описание

При выгрузке элементов справочников и документов в макет с помощью СериализаторMXL невозможно указать произвольные дополнительные свойства, которые затем будут использованы при загрузке. В моем случае это привело к невозможности загрузки, так как в базе-приемнике запись новых объектов разрешена только в случае наличия допсвойства "ЗаписьРазрешена" со значением Истина.

## Также приветствуется описание в формате Gherkin

```Gherkin
   Для передачи произвольных дополнительных свойств в базу-приемник при загрузке из макета
   Как пользователь Сериализатора MXL
   Я хочу иметь возможность добавить выгружаемым объектам произвольные дополнительные свойства

Контекст
  Дано <версия продукта>
  И <версия платформы 1С>
  и <параметры запуска>

Сценарий Выгрузка произвольно добавленных дополнительных свойств
  Допустим, что есть таблица "ДополнительныеСвойства" с колонками "Имя, Значение", в которой содержится список допсвойств для выгружаемых объектов
  Когда таблица "ДополнительныеСвойства" не пустая
  И все колонки всех строк таблицы "ДополнительныеСвойства" заполнены
  Тогда в сформированном табличном документе у каждого объекта присутствует раздел "ДополнительныеСвойства"
  И в этом разделе перечислены все указанные в таблице "ДополнительныеСвойства" строки

```

**Comment by artbear** [comment]
Выполнено
