### ISSUE TITLE
В Wiki некоторые ссылки в секции "Создание файлов-тестов" ведут на 404

### ISSUE THREAD

**Issue by ruimage** [xDrivenDevelopment/xUnitFor1C#641]
### Предварительно
В Wiki некоторые ссылки в секции "Создание файлов-тестов" ведут на 404
## Описание

На странице https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2

Ссылки ведущие на 404

- простой тест для обычной формы
- этот же простой тест для управляемой формы
- Код теста xUnitFor1C с параметрами

**Comment by artbear** [comment]
Спасибо.
Исправил.
