### ISSUE TITLE
Ошибка при загрузке макета данных с циклическими ссылками

### ISSUE THREAD

**Issue by wezoowy** [xDrivenDevelopment/xUnitFor1C#642]
## Описание

При загрузке из макета данных определенной конфигурации возникает ошибка:

_{ВнешняяОбработка.СериализаторMXL.МодульОбъекта(931)}: Ошибка при вызове метода контекста (Записать): Значение поля "Владелец" не заполнено или заполнено неверно_

**Описание метаданных**

Есть справочник Контрагенты и два подчиненных справочника: "Банковские счета" и "Договоры".
При этом у самого контрагента есть ссылка на его основной банковский счет и ссылка на его основной договор.

При формировании макета в базе 1, он создается корректно, тестирование загрузки макета в эту же базу проходит без ошибок.

Но при загрузке этого макета в базу с аналогичной конфигурацией происходит ошибка.

![01](https://cloud.githubusercontent.com/assets/21204699/17906842/0737f3c4-698a-11e6-944a-3d6542b789a2.JPG)

Вероятно проблема из-за циклических ссылок: контрагент ссылается на договор и счет своими реквизитами, а договор и счет имеют владельцем контрагента.

**Параметры**
* версия модуля xUnitFor1C: 4.0.0.7
* версия генератора макета: 3.0.0.5
* версия платформы 1С: 8.3.8.1652
* обычное приложение

Создал специальную простейшую конфигурацию для тестирования этой проблемы.
Архив с базой источником и базой приемником:
[Bases.zip](https://github.com/xDrivenDevelopment/xUnitFor1C/files/433382/Bases.zip)

**Comment by artbear** [comment]
Да, здесь проблема в циклических ссылках.
Я специально не стал разруливать подобное автоматически, т.к. это
очень-очень редкий случай.

Разорвите цикл. Например, реквизиты одного из элементов создавайте через
ссылку, без использования Перем.

вт, 23 Авг 2016, 22:36 wezoowy <notifications@github.com>:

**Comment by wezoowy** [comment]
Понял, спасибо.
Попробую что-нибудь придумать своими силами - у нас в основной разрабатываемой конфигурации очень много подобных коллизий.
