### ISSUE TITLE
Ошибка при конвертации тестов из 3 в 4 версию.

### ISSUE THREAD

**Issue by MikolaKar** [xDrivenDevelopment/xUnitFor1C#648]
При запуске Utils/xddTestsConvertIntoRebornFormat.epf
выскакивает ошибка:
{(1,15)}: Ожидается выражение
КонтекстЯдра =<<?>> .Создать("")

[2016-09-22_13-24-18.pdf](https://github.com/xDrivenDevelopment/xUnitFor1C/files/487110/2016-09-22_13-24-18.pdf)

**Comment by artbear** [comment]
- Версия 1С
- версия хЮнит ?
- файловая ИБ или клиент-серверная ?
- Проверь конвертацию на одной-двух обработках из твоей папки из приложенного пдф-файла.

Я прогнал тесты на 1С 8.3.8.1784, хЮнит 4.1 - ошибок нет.
Вручную сконвертировал 1 старую обработку, ошибок нет

Жду инфы от тебя

**Comment by MikolaKar** [comment]
- 1C была 8.3.8.1784, сейчас 8.3.9.1818. 
- хЮнит 4.1.0.0
- ИБ файловая
- конвертация все-равно вываливается на ту же ошибку, какую бы обработку не запускал.

Посмотрел по коду. При запуске xddTestsConvertIntoRebornFormat в процедуре Инициализация() не определена ПолноеИмяБраузераТестов. Соответственно и дальше, при попытке выполнить ПолучитьКонтекстЯдраНаСервере() вываливается ошибка, которая была приложена в пдф.
Когда вручную вставил в коде 
Выполнить("КонтекстЯдра = " + МенеджерОбъектов + ".Создать("""+ИмяОбъекта+""")");   
МенеджерОбъектов = "ВнешниеОбработки", а ИмяОобъекта=Полный путь к xddTestRunner.epf, то код продолжил выполняться и вывалился уже на ошибку при создании плагинов в функции СоздатьОбъектПлагина() модуля xddTestRunner.
Получается, что проблема возникновения ошибки в том, что xddTestsConvertIntoRebornFormat должна запускаться в определенном окружении, либо как-то надо прописывать пути к xddTestRunner.epf.

**Comment by artbear** [comment]
Да, баг подтверждаю.
Исправлю

**Comment by artbear** [comment]
Исправлено.
Баг был внесен при добавлении фичи вставки в конфигурации @YPermitin - как обычно, никакие тесты не найдут 100% ошибок :)

**Comment by YPermitin** [comment]
@artbear блин, я тут оказывается дров наломал...
