### ISSUE TITLE
xddTestRunner не запускается в 8.2.19.83

### ISSUE THREAD

**Issue by 1823244** [xDrivenDevelopment/xUnitFor1C#649]
### Предварительно

* [x] Вы используете [последнюю версию продукта](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop)  ?
* [x] Вы проверили [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8) ?

## Описание

xddTestRunner не запускается в 8.2.19.83, при открытии платформа выдает ошибку:
{Форма.УправляемаяФорма.Форма(121,22)}: Тип не определен (ОписаниеОповещения)
		Оповещение = Новый <<?>>ОписаниеОповещения("КомандаПерезагрузитьФормуЗавершение", ЭтаФорма);
{Форма.УправляемаяФорма.Форма(951,22)}: Тип не определен (ОписаниеОповещения)
		Оповещение = Новый <<?>>ОписаниеОповещения("ОткрытьИнструментЗавершение", ЭтаФорма, Новый Структура("ИмяИнструмента, ИмяФормыИнструмента", ИмяИнструмента, ИмяФормы));
{Форма.УправляемаяФорма.Форма(985,14)}: Тип не определен (ОписаниеОповещения)
		Оп = Новый <<?>>ОписаниеОповещения("ПодключитьВнешнююОбработкуЗавершение", ЭтаФорма, Новый Структура("ФайлОбработки, ЭтоОтчет", ФайлОбработки, ЭтоОтчет));

** Шаги для воспроизведения **

1. Открыть обработку
2. Получить ошибку платформы

**Ожидаемое поведение:** [ Что вы хотите получить? ]
Нормальное открытие обработки
**Текущее поведение:** [ Что происходит в действительности? ]
Обработка не открывается, платформа выдает ошибку.
**Причина: Вы используете метод языка, которого нет в версии платформы 8.2**

**Укажите:**
* [4.1.0.0]
* [8.2.19.83 ]
* [ управляемое приложение, тонкий клиент, толстый клиент ]

** Прикладывайте скриншоты **

## Также приветствуется описание в формате Gherkin

```Gherkin
Функционал <Открытие обработки>
   Как <Программист>
   Я хочу <Чтобы обработка открывалась на платформе 8.2, а не выдавала ошибку>

Контекст
  Дано <4.1.0.0>
  И <8.2.19.83>
  и <без параметров запуска>

Сценарий <Обработка откроется в управляемом приложении , тонком и толстом клиенте>
  Допустим <Исходные данные - нет исходных данных>
  Когда <Что-то вызывается - выполняется открытие обработки>
  Тогда <Получаем результат - обработка открывается>

```

**Comment by artbear** [comment]
Начиная с версии 4.1 продукт xUnitFor1C работает только в 1С версии 8.3 и выше

Для 8.2 используйте xUnitFor1C 4.0 или 3.Х
