### ISSUE TITLE
Ошибки при отказе загрузки тестов в xddTestRunner

### ISSUE THREAD

**Issue by Alucardinio** [xDrivenDevelopment/xUnitFor1C#652]
## Описание

При отказе от загрузки тестов(из подсистем, файлов, каталога) появляются различные ошибки.

**Шаги для воспроизведения**

1. Запускаем xddTestRunner.epf
2. Выбираем "Загрузить тесты из конфигурации/каталога/файлов"
3. Отказываемся от загрузки

**Ожидаемое поведение:** 

Ничего не происходит. Ошибок быть не должно.

**Текущее поведение:** 

Загрузка из подсистем - ошибка "Слишком много фактических параметров"
Загрузка из файлов/каталога ошибка модуля формы соответствующего pluginа

* xUnitFor1C 4.1.0.0
* 1с 8.3.8.2027
* Управляемое приложение тонкий клиент

![image](https://cloud.githubusercontent.com/assets/10996209/20541039/f38b39c6-b114-11e6-9489-c50e91aa402f.png)

![image](https://cloud.githubusercontent.com/assets/10996209/20540917/76a1169c-b114-11e6-9b21-55ec0bb468a7.png)

**Comment by artbear** [comment]
Исправлено
