### ISSUE TITLE
Выгрузка n уровней зависимостей в СериализатореMXL

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/xUnitFor1C#659]
### Предварительно

* [x] Вы используете [последнюю версию продукта](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop)  ?
* [x] Вы проверили [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8) ?

## Описание

> еще нужна фича - очень нужна. выгрузка по объектов зависимостям на 1 уровень зависимости
руками постоянно набирать объекты, которые нужны для более-менее нормальной работы сценария - немного ад. а тестировать это добро - тоже задача не тривиальная

> Artur Ayukhanov @artbear 18:44
т.е. спр.1 включает спр.2, который включает спр.3, выгружать нужно только спр.1 и спр.2 ?

> Nikita Gryzlov @nixel2007 18:45
если к выгрузке отмечен спр.1 + стоит выгружать по зависимостям, то да, только спр.1 и спр 2. если к выгрузке отмечены спр.1 и спр.2 + стоит выгружать по зависимостям, тогда все три спр.

Я злобный буратино и стер почти весь шаблон.

**Comment by artbear** [comment]
Т.е. ты предлагаешь всегда выгружать только первый уровень зависимости?
а как же режим - выгрузить все?

**Comment by nixel2007** [comment]
Я предлагаю некую дополнительную настройку, которая будет анализировать значение флага "данные для выгрузки" и флага "при необходимости".

Если "данные для выгрузки" = ложь и это уровень зависимости больше N, тогда такой объект выгружать **не надо**
если "данные для выгрузки" = ложь и это уровень зависимости меньше или равен N, тогда такой объект выгружать **надо**
Если "данные для загрузки" = истина, то такой объект **выгружается** в любом случае

**Comment by artbear** [comment]
А теперь давай придумаем, как эту настройку расположить на форме и как обозначить ее назначение :)

**Comment by nixel2007** [comment]
Ограничить уровень выгружаемых зависимых объектов: N
тип число. расположить рядом с галками, которых уже порядком.
Если значение = 0, то данный механизм не применяется

**Comment by artbear** [comment]
Вот такой вариант подсказки получается:

>Ограничить уровень выгружаемых зависимых объектов: N
Если значение = 0, то данный механизм не применяется и выгружаются элементы с признаком "При необходимости"
Значение = 1 нужно для выгрузки вообще без подчиненных, только явно заданные метаданные
Если значение > 1, то выгружаем подчиненные элементы этого или меньшего уровня зависимости

Формулировка нормально или сложновато звучит? другого варианта пока не придумал.

**Comment by nixel2007** [comment]
Погоди, вообще без подчиненных это тоже самое, что снятые признаки "при необходимости" со всех объектов. я имел ввиду, что 1 - это все же объекты + их первые зависимости

**Comment by artbear** [comment]
Для повышения юзабельности пришлось сделать автозамену флажков "при необходимости" в зависимости от нашего ограничителя.
А в этом случае я посчитал, что нужен отдельный режим выгрузки только выбранных объектов.
Хотя это можно достичь и ручным снятием флага "При необходимости" для корня конфигурации :)

В общем, можно и переделать, это несложно.
Жду предложений от @xDrivenDevelopment/contributors @all

**Comment by snov1kov** [comment]
@nixel2007  @artbear 
В некоторых случаях можно еще сильнее уменьшить размер макета, если знаешь перечень нужных реквизитов, которые нужны для Задачи. И если бы была возможность указания реквизитов к выгрузке, можно было бы еще сильнее сократить размер макетов :)

**Comment by nixel2007** [comment]
@snov1kov да, интересная идея. но видимо это надо делать уже не на первой вкладке с деревом метаданных, а на второй с списком конкретных объектов. типа "вот выгрузи мне такой-то объект и такие-то его реквизиты". жаль, что вторая вкладка не содержит всех галочек, что есть на первой. хотя бы режимы выгрузки перем/гуид, выгружать ссылку и движения

**Comment by artbear** [comment]
>@nixel2007  @artbear 
В некоторых случаях можно еще сильнее уменьшить размер макета, если знаешь перечень нужных реквизитов, которые нужны для Задачи. И если бы была возможность указания реквизитов к выгрузке, можно было бы еще сильнее сократить размер макетов :)

Конечно, я в свое время думал над уменьшением размера макета.
Возражения:
+ для каждого метаданного и каждого сценария не очень удобно настраивать этот список полей
+ я специально в макете убрал "пустые" поля, у которых значения совпадают со значениями по-умолчанию
+ главный довод - можешь вручную в макете удалить любые ненужные поля, удобно и мощно :)

**Comment by das999** [comment]
А сериализатор умеет такое: если у объекта метаданных сняты обе галки для
выгрузки, то если в выгружаемых данных есть реквизиты типа этого объекта,
то они не выгружаются в макет совсем?

15 дек. 2016 г. 6:53 PM пользователь "Nikita Gryzlov" <
notifications@github.com> написал:

**Comment by artbear** [comment]
Ну и еще один важный довод - мы очень часто выгружаем данные из реальной базы, для таких данных лучше выгружать все поля, а уже потом, непосредственно в макете заниматься анализом и убирать ненужные поля. Намного нагляднее, чем вручную ставить галочки.

**Comment by artbear** [comment]
>А сериализатор умеет такое: если у объекта метаданных сняты обе галки для
выгрузки, то если в выгружаемых данных есть реквизиты типа этого объекта,
то они не выгружаются в макет совсем?

Конечно, это важное свойство инструмента :)
В этом случае для таких реквизитов ставится режим поиска существующего элемента в базе. (ссылка, наименование, код, гуид, предопределенный)

**Comment by snov1kov** [comment]
@artbear Главный контраргумент ручному удалению - количество строк в макете (когда их число превышает несколько тысяч, то руки опускаются)

**Comment by 1cgh** [comment]
@artbear  я вот про другое, наверно. допустим, есть документ Реализация. в нем есть реквизит Организация типа СправочникСсылка.Организации.
И есть ли режим, при котором:
У справочника Организации сняты обе галки (выгружать и при необходимости) = В макете в выгрузке конкретного документа Реализация нет строчки с реквизитом Организация. Совсем нет.

**Comment by artbear** [comment]
@1cgh Нет, такого режима нет.
ИМХО @snov1kov о подобном говорит.

Можете добавить, я возражать не буду :)

**Comment by artbear** [comment]
Закрываю?
