### ISSUE TITLE
Некорректная выгрузка пустой коллекции движений документа Сериализатором

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/xUnitFor1C#661]
### Предварительно

* [x] Вы используете [последнюю версию продукта](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop)  ?
* [x] Вы проверили [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8) ?

## Описание

При включении выгрузки движений вместе с документами в макет подставляется пустая строка с именем регистра, однако такое движение не может обратно загрузиться.

**Воспроизведение**

* Создаем документ с движениями в несколько регистров, часть движений - пустые.
* Выгружаем движения, получаем макет
* Жмем кнопку "Протестировать загрузку макета"
* Ловим ошибку

**Укажите:**
* [ версию продукта ] last
* [ версию платформы 1С ] 8.2.19
* [ параметры запуска
  * обычное/управляемое приложение, тонкий/толстый клиент и т.п. ] - обычное приложение

**Comment by artbear** [comment]
@nixel2007 8.2.19 ?
Начиная с версии 4.1 продукт работает только с 1С 8.3 :(
Соответственно исправление будет только для 8.3.

Для 8.2 если только энтузиаст-контрибьютор доработает версию 3.0.0.8

**Comment by nixel2007** [comment]
> Соответственно исправление будет только для 8.3.

сериализатору ничего не мешает работать в 8.2.19. Сам xUnit может и не работает

**Comment by artbear** [comment]
Да, сериализатор пока не юзает ничего нового из 8.3
А вдруг начнет юзать СтрНайти, например? :)

Лады, поставлю в очередь
