### ISSUE TITLE
Пакетный запуск не поддерживает вывод отчёта в нескольких форматах

### ISSUE THREAD

**Issue by realMaxA** [xDrivenDevelopment/xUnitFor1C#666]
### Предварительно

* [x] Вы используете [последнюю версию продукта](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop)  ?
* [x] Вы проверили [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8) ?

## Описание

При выполнении пакетного запуска с указанием вывода отчёта о тестировании в нескольких форматах происходит формирование отчёта в формате, указанном в последнем параметре запуска "xddReport"

** Шаги для воспроизведения **

1. Запустить обработку командой

```
1cv8.exe ENTERPRISE /F"ib" /DisableStartupMessages /Execute "xUnitFor1C/xddTestRunner.epf" /C "xddRun ЗагрузчикКаталога ""tests/""; xddReport ГенераторОтчетаAllureXML ""res-testsuite.xml""; xddReport ГенераторОтчетаJUnitXML ""res.xml""; xddShutdown;"
```

убеждаемся, что сгенерировался только отчёт "res.xml".

2. Запустить обработку командой

```
1cv8.exe ENTERPRISE /F"ib" /DisableStartupMessages /Execute "xUnitFor1C/xddTestRunner.epf" /C "xddRun ЗагрузчикКаталога ""tests/""; xddReport ГенераторОтчетаJUnitXML ""res.xml""; xddReport ГенераторОтчетаAllureXML ""res-testsuite.xml""; xddShutdown;"
```

убеждаемся, что сгенерировался только отчёт "res-testsuite.xml".

**Ожидаемое поведение:** Ожидается, что будут сгенерированы сразу два отчёта "res-testsuite.xml" и "res.xml"

**Текущее поведение:** Формируется только один вид отчёта, указанный в параметрах последним.

**Укажите:**
* [ версию продукта ] - 4.1.0.1
* [ версию платформы 1С ] - 8.3.8.2054
* [ параметры запуска
  * обычное/управляемое приложение, тонкий/толстый клиент и т.п. ] - управляемое приложение

**Comment by artbear** [comment]
@MaksimGr Сможешь посмотреть и поправить?

**Comment by MaksimGr** [comment]
Могу поправить, но также предлагаю сразу доработать плагин для Allure:
- Добавить команду xddReportAllure у которой будет параметр путь к папке, а не путь к файлу как у xddReport.
- В указанной папке сразу создавать не один, а несколько файлов с именем  %UID%-testsuit.xml где %UID% это случайный уникальный идентификатор для каждого файла. Создавать файлы по принципу один набор тестов (одна обработка) - один файл.

Аналогично выполняется формирование отчета в ванессе. На это есть причины - таковы особенности allure. Я так понял, что в одном файле нельзя отобразить сложную иерархию тестов (Наборы тестов - Группы тестов - Тесты). 
Подробности должны быть здесь https://github.com/allure-framework/allure1/issues/558

**Comment by artbear** [comment]
@MaksimGr Сам ишуз я почти подготовил.
Меняю `xddTestRunner`
Теперь нормально должна отрабываться строка `xddReport ГенераторОтчетаJUnitXML ПутьОтчета; xddReport ГенераторОтчетаAllureXML ПутьОтчета2`

Плагин для Аллюр можешь дорабатывать.

**Comment by realMaxA** [comment]
Как поведёт себя плагин для allure, если в качестве пути указать имя файла?
Возможное поведение: если файл существует, то он удалится, а затем создастся каталог с таким именем.

**Comment by MaksimGr** [comment]
Допустим мы выполним запуск команды xddReportAllure "C:\reports\allure.xml". 
Сначала будет выполнена проверка, что каталог "C:\reports\allure.xml\" существует. 
Если такого каталога нет, то произойдет вызов исключения.

**Comment by MaksimGr** [comment]
Команда xddReport будет работать как и раньше

**Comment by artbear** [comment]
Ждем доработки от @MaksimGr

**Comment by artbear** [comment]
@MaksimGr Будешь реализовывать, как ты ранее говорил?

**Comment by artbear** [comment]
Исправлено в #741
