### ISSUE TITLE
СериализаторMXL: Некорректная выгрузка пустой ссылки составного типа

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/xUnitFor1C#667]
### Предварительно

* [x] Вы используете [последнюю версию продукта](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop)  ?
* [x] Вы проверили [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8) ?

## Описание

При включенном режиме связи по гуид при выгрузке пустой ссылки поля составного типа в данные выгружается пустой ГУИД, колонка ДополнительныйТип остается пустой.

Это приводит к некорректной загрузке этих данных.

Наверное было бы лучше, чтобы это поле не выгружалось в макет.

**Comment by artbear** [comment]
Иногда нужно, чтобы как раз выгрузилось пустая ссылка нужного типа для реквизита с составным типом.
Поэтому я и оставил выгрузку реквизитов с такими значениями.

Проверил сценарий, подтверждаю.

**Comment by artbear** [comment]
Исправлено.
Проверяй.
