### ISSUE TITLE
Allure не распознает файл для него созданный

### ISSUE THREAD

**Issue by git22ura** [xDrivenDevelopment/xUnitFor1C#676]
В результате выполнения команды (прописанной по инструкции из вики):

> C:\smoke_test>"C:\Program Files\1cv8\8.3.9.1850\bin\1cv8.exe" ENTERPRISE /F"C:\smoke_test\test_base" /Nadmin /P1 /RunModeManagedApplication /Execute "C:\smoke_test\xUnitFor1C\xddTestRunner.epf" /C "xddRun ЗагрузчикКаталога ""C:\smoke_test\Tests\""; xddReport ГенераторОтчетаAllureXML ""C:\smoke_test\Reports\\report-allure.xml""; xddShutdown;"

Получаем файл

`<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name xmlns="">тесты_ОткрытиеФормКонфигурации_ограничениеКоличества</name>
	<labels xmlns="" xmlns:d2p1="urn:model.allure.qatools.yandex.ru">
		<label name="framework" value="xUnitFor1C"/>
		<label name="language" value="1С"/>
	</labels>
	<test-cases xmlns="" xmlns:d2p1="urn:model.allure.qatools.yandex.ru">
		<test-case start="63621022246268" stop="63621022246393" status="passed">
			<title>ТестДолжен_ПроверитьБагПлатформыПриОткрытииУправляемойФормыПриОткрытииКоторойЕстьИсключение</title>
		</test-case>
		<test-case start="63621022246424" stop="63621022246596" status="passed">
			<title>Новые : Справочник.ПервыйСправочник.Форма.ФормаЭлемента</title>
		</test-case>
		<test-case start="63621022246627" stop="63621022246912" status="passed">
			<title>Существующие : Справочник.ПервыйСправочник.Форма.ФормаЭлемента</title>
		</test-case>
	</test-cases>
</ns2:test-suite>
`

Скармливаю Аллюру, а он ругается

>c:\test\Reports>allure generate .
>Exception in thread "main" ru.yandex.qatools.allure.data.ReportGenerationExcepti
>on: **Could not find any allure results**
>        at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureRe
>portGenerator.java:58)
>        at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureRe
>portGenerator.java:53)
>        at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
>Command aborted due to exception {}.
>org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit
>value: 1)
>        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecut
>or.java:404)
>        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:
>166)
>        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:
>153)
>        at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGener
>ate.java:48)
>        at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.
>java:52)
>        at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)
>
>c:\test\Reports>`
Что я делаю не так?

**Comment by git22ura** [comment]
Ответ такой: Allure воспринимает только файлы которые заканчиваются на "-testsuite.xml". Наткнулся в gitter, спасибо @MaksimGr

**Comment by artbear** [comment]
Добавил проверку правильности имени файла для Allure - требуется окончание имени на "-testsuite.xml"
