### ISSUE TITLE
Битая ссылка на странице "Создание файлов тестов"

### ISSUE THREAD

**Issue by vpozdnyakov** [xDrivenDevelopment/xUnitFor1C#679]
на страничке https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2

в самом конце ссылка с текстом "Код теста xUnitFor1C с параметрами" возвращает 404 ошибку

**Comment by artbear** [comment]
Спасибо.
Исправил

Добавил ссылки на 2 примера кодов
