### ISSUE TITLE
В дымовом тесте для тестирования добавляются общие формы (отчёта и настроек отчёта)

### ISSUE THREAD

**Issue by realMaxA** [xDrivenDevelopment/xUnitFor1C#682]
### Предварительно

* [x] Вы используете [последнюю версию продукта](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop)  ?
    Коммит 6d62d23e
* [x] Вы проверили [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8) ?

## Описание

Проблема воспроизводится в том числе на демо конфигурации БСП 2.3.4.107.

**Шаги для воспроизведения**

1. Открыть обработку xddTestRunner.epf
2. Загрузить тесты из каталога файловой системы (Tests\Smoke\)
3. Убедиться, что в дереве тестов есть тесты на открытие форм
    - ОбщаяФорма.ФормаОтчета
    - ОбщаяФорма.ФормаНастроекОтчета
    причём эти формы указаны множество раз. Вероятно эти формы добавляются в дерево тестов, т. к.  указаны в качестве основных форм ряда отчётов.
4. Изменить обработку тесты_ОткрытиеФормКонфигурации.epf, добавив в функцию "ПолучитьСписокИсключений_Отчеты()" модуля объекта все отчёты иp конфигурации

```
Функция ПолучитьСписокИсключений_Отчеты() Экспорт
	Результат = Новый СписокЗначений;
	
	Результат.Добавить("_ДемоДинамикаИзмененийФайлов");
	Результат.Добавить("_ДемоКнигаПокупок");
	Результат.Добавить("_ДемоОборотноСальдоваяВедомость");
	Результат.Добавить("_ДемоОстаткиТоваровВМестахХранения");
	Результат.Добавить("_ДемоОтчетПоСчетамНаОплатуГлобальный");
	Результат.Добавить("_ДемоОтчетПоСчетамНаОплатуКонтекстный");
	Результат.Добавить("_ДемоСтатусыЗаказовПокупателей");
	Результат.Добавить("_ДемоФайлы");
	Результат.Добавить("_ДемоФайлыВспомогательный");
	Результат.Добавить("АнализВерсийОбъектов");
	Результат.Добавить("АнализЖурналаРегистрации");
	Результат.Добавить("АнализОпроса");
	Результат.Добавить("АналитическийОтчетПоАнкетированию");
	Результат.Добавить("БизнесПроцессы");
	Результат.Добавить("ДатыЗапретаЗагрузки");
	Результат.Добавить("ДатыЗапретаИзменения");
	Результат.Добавить("ДосьеКонтрагента");
	Результат.Добавить("ЗависшиеЗадачи");
	Результат.Добавить("Задания");
	Результат.Добавить("Задачи");
	Результат.Добавить("ЗадачиИстекающиеНаДату");
	Результат.Добавить("ИнструментыРазработчикаБыстрыеНастройкиОтчетов");
	Результат.Добавить("ИнструментыРазработчикаЗависимостиПодсистем");
	Результат.Добавить("ИнструментыРазработчикаСтатистикаВыполненияОбработчиковОбновления");
	Результат.Добавить("ИспользуемыеВнешниеРесурсы");
	Результат.Добавить("МестаИспользованияСсылок");
	Результат.Добавить("ОбъемНенужныхФайлов");
	Результат.Добавить("ПраваДоступа");
	Результат.Добавить("ПроверкаВнедренияБСП");
	Результат.Добавить("ПроверкаЦелостностиТома");
	Результат.Добавить("ПрогрессОтложенногоОбновления");
	Результат.Добавить("ПросроченныеЗадачи");
	Результат.Добавить("СведенияОПользователях");
	Результат.Добавить("СогласияНаОбработкуПерсональныхДанныхДействующие");
	Результат.Добавить("СогласияНаОбработкуПерсональныхДанныхИстекающие");
	Результат.Добавить("УниверсальныйОтчет");
	
	Возврат Результат;
КонецФункции
```

5. Повторно загрузить тесты
6. Убедиться, что общие формы
    - ОбщаяФорма.ФормаОтчета
    - ОбщаяФорма.ФормаНастроекОтчета
    Всё ещё выбраны для тестирования
7. Запустить тесты
8. Убедиться, что при тестировании форм
    - ОбщаяФорма.ФормаОтчета
    - ОбщаяФорма.ФормаНастроекОтчета
    возникла ошибка

```
"{ВнешняяОбработка.тесты_ОткрытиеФормКонфигурации.Форма.УправляемаяФорма.Форма(291)}: Ошибка при вызове метода контекста (ОткрытьФорму)
		ТестируемаяФорма = ОткрытьФорму(ПолноеИмяФормы, ПараметрыФормы,, КлючВременнойФормы);
по причине:
Получать форму объекта - отчета возможно только для конкретного отчета"
```

**Ожидаемое поведение:**
1. Формы, добавляемые для тестирования не должны дублироваться или
2. если тестирование формы зависит от контекста (проверяемый отчёт), то в форму должны передаваться соответствующие параметры
3. Общие формы, указанные как основные формы отчётов не должны добавляться для тестирования, если сам отчёт добавлен в исключения

**Текущее поведение:**
См. Шаги для воспроизведения.

**Версии:**
* Продукт из ветки develop, commit 6d62d23e
* Версия платформы: 8.3.9.1850, 8.3.8.2322
* параметры запуска: Нет
    * управляемое приложение
    * тонкий клиент
    * интерфейс Такси

**Comment by artbear** [comment]
Выполнено в ветке develop

**Comment by artbear** [comment]
@realMaxA Сможешь проверить на своих примерах?
