### ISSUE TITLE
Проверить отдачу результата тестирования на управляемых формах через vanessa-runner

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/xUnitFor1C#685]

**Comment by artbear** [comment]
Старая задача https://github.com/xDrivenDevelopment/xUnitFor1C/issues/594
Из Вики 3.Х

> 1. `xddExitCodePath` / `Тесты_Путь_КЛогам` _обязательно при наличии команды `xddRun`_ - путь к специальному тестовому файлу с кодом возврата, который содержит одну цифру (0 или 1). 0 означает успешное выполнение, 1 - неуспешно. Файл нужен, т.к. 1С:Предприятие по завершении работы не возвращает код возврата. Следующим параметром должен идти путь к файлу.

**Comment by artbear** [comment]
Реализовано на ОФ+УФ
