### ISSUE TITLE
Использование СтрШаблон в плагине ГенерацияКодаВозврата накладывает ограничение на версию платформы >= 8.3.6

### ISSUE THREAD

**Issue by antowski** [xDrivenDevelopment/xUnitFor1C#687]
В плагине **ГенерацияКодаВозврата** используется функция **СтрШаблон**, которая появилась в платформе в версии 8.3.6. Это приводит к ошибке **Процедура или функция с указанным именем не определена (СтрШаблон)** при открытии обработки на платформе версии младше 8.3.6 или при использовании режима совместимости младше 8.3.6 .
Функция вызывается в [модуле объекта](https://github.com/xDrivenDevelopment/xUnitFor1C/blob/develop/src/Plugins/%D0%93%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F%D0%9A%D0%BE%D0%B4%D0%B0%D0%92%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%82%D0%B0/ObjectModule.bsl#L29) и [модуле формы](https://github.com/xDrivenDevelopment/xUnitFor1C/blob/develop/src/Plugins/%D0%93%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F%D0%9A%D0%BE%D0%B4%D0%B0%D0%92%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%82%D0%B0/Form/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0.bsl#L36) плагина **ГенерацияКодаВозврата**.

**Comment by asheichenko** [comment]
Тоже столкнулся с этой ошибкой при проверке загрузки макета, в УПП для решения этих проблем добавлен общий глобальный модуль ГлобальныйМодуль с функциями повторяющими типовые СтрШаблон.

**Comment by artbear** [comment]
Да, только что также наши клиенты попали на эту свежую доработку.
Исправим.

**Comment by artbear** [comment]
Исправлено
