### ISSUE TITLE
Плагин генерации макета. Флажки на форме.

### ISSUE THREAD

**Issue by 1cgh** [xDrivenDevelopment/xUnitFor1C#694]
### Предварительно

Плагин по генерации макета MXL (СериализаторMXL.epf)
Версия 4.1.0.4

## Описание

На форме плагина на закладке "Метаданные" каша из флажков, отсутствуют подсказки к флажкам.

**Шаги для воспроизведения**

1. Открыть СериализаторMXL.epf
2. Увидеть месиво)

**Ожидаемое поведение:**
Отображение текста флажков, чтобы понимать их назначение.
Наличие подсказок к флажкам, что позволит понять их назначение, если текст не помещается на экране.

**Текущее поведение:**

Скриншот при разрешении 1920*1080:
![2017-03-27 10 17 29](https://cloud.githubusercontent.com/assets/24507052/24345109/39c8ddb6-12d7-11e7-85c0-7acda2716e25.png)

**Comment by 1cgh** [comment]
Упс. По ходу дублирует #668 
Хотя там нет про подсказки (:

**Comment by artbear** [comment]
Для УФ доработано в #741
