### ISSUE TITLE
Ошибка на ЗагрузчикФайла.epf в режиме совместимости 8.3.5

### ISSUE THREAD

**Issue by 1cgh** [xDrivenDevelopment/xUnitFor1C#702]
### Предварительно

* [x] Вы используете [последнюю версию продукта](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop)  ?
да
* [x] Вы проверили [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8) ?
да

## Описание

Ошибка при открытии управляемой формы xddTestRunner:
{ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(217)}: Поле объекта не обнаружено (C:\GIT\xDrivenDevelopment\xUnitFor1C\Plugins\ЗагрузчикФайла.epf)
			ОписаниеПлагина = ОписанияПлагинов[ЗагруженныйФайл.Имя];

**Шаги для воспроизведения**

1. Платформа 8.3.9.2170.
2. Создать пустую конфигурацию. Основной режим запуска: Управляемое приложение.
3. Переключить конфигурацию в режим совместимости 8.3.5
4. Запустить в режиме предприятия. Запустить xddTestRunner. Получить ошибку.

**Ожидаемое поведение:** [ Что вы хотите получить? ]
Запуск обработки без ошибок

**Текущее поведение:** [ Что происходит в действительности? ]
Почему-то в режиме совместимости только на плагине ЗагрузчикФайла падает код
ОбъектОбработки = ВнешниеОбработки.Создать(ИмяПлагина, Ложь);
т.е. эта обработка не подключается почему-то.

**Укажите:**
* [ версию продукта ] 4.1.1.0
* [ версию платформы 1С ] 8.3.9.2170
* [ параметры запуска
  * обычное/управляемое приложение, тонкий/толстый клиент и т.п. ] Управляемое приложение, режим совместимости 8.3.5

**Comment by artbear** [comment]
У нас в коде начал юзаться СтрШаблон, а он доступен после 8.3.5

ИМХО проблема в этом или подобном методе, несовместимым с 8.3.5

**Comment by 1cgh** [comment]
@artbear там в цикле подключаются внешние обработки через
ПодключитьФайлОбработкиНаСервере(ОписаниеФайла.Хранение, ИмяПлагина);
а потом создаются объекты обработок. и вот только для одного плагина создание объекта обработки падает

**Comment by 1cgh** [comment]
т.е. изначально падает вот этот код
https://github.com/xDrivenDevelopment/xUnitFor1C/blob/develop/src/xddTestRunner/Form/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%B0%D1%8F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0.bsl#L239

**Comment by yadimetrio** [comment]
На загрузчик так же ругается в режиме совместимости 8.2.13. (Платформа 8.3.10.2168)
`ВнешняяОбработка.ЗагрузчикФайла.МодульОбъекта(135,4)}: Процедура или функция с указанным именем не определена (СтрНайти)
			<<?>>СтрНайти(Инфо.ИсходнаяСтрока, "Обработка.ЗаполнитьНаборТестов(ЭтотОбъект, КонтекстЯдра);") > 0`
В данном случае, понятно в чем причина. В ридми ограничения устанавливаются на версию платформы, или на режимы совместимости?

**Comment by artbear** [comment]
Закрываю, т.к. в 4.1.1.0 поддержка 8.3.6 и выше.
Доку сейчас исправлю
