### ISSUE TITLE
Разное наименование типа объекта метаданных в СериализаторMXL

### ISSUE THREAD

**Issue by yadimetrio** [xDrivenDevelopment/xUnitFor1C#705]
### Предварительно

* [ ] Вы используете [последнюю версию продукта](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop)  ? - Да
* [ ] Вы проверили [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8)  ? - Да

## Описание

При генерации макета для планов видов расчета устанавливается тип "ПланВидовРасче**та**", а в коде, при определении типа объекта к загрузке сравнивается с типом "ПланВидовРасчет**ов**", в итоге объект ПВР не загружается.

**Шаги для воспроизведения**

1. Сгенерировать макет данных для загрузки с любым объектом типа "Планы видов расчета"
2. Протестировать загрузку. Вместо ссылки будет возвращаться "Неопределено". И по факту объект не загружается.
```
Проверка загрузки объектов в ИБ из макета данных выполнена успешно.
В ИБ загружены объекты: 1 шт.
    Загружен объект.Имя Оклад, Тип Не определено
```
3. Если в макете изменить значение в колонке "Тип" с "ПланВидовРасчета" на "ПланВидовРасчетов", загрузка выполняется.
```
Проверка загрузки объектов в ИБ из макета данных выполнена успешно.
В ИБ загружены объекты: 1 шт.
    Загружен объект.Имя Оклад, Тип Управленческие начисления, ГУИД 678ccb8b-220d-11df-81f8-0016e612cf39
``` 
**Ожидаемое поведение:** 

Ожидается предсказуемая работа обработки генерации тестовых данных.

**Текущее поведение:**

Объекты типа "План видов расчета" не загружаются генератором тестовых данных.

**Укажите:**
* [ СериализаторMXL v4.1.0.4 ]
* [ 8.3.10.2168 ]
* [ управляемое приложение, тонкий клиент ]

**Прикладывайте скриншоты**
![1](https://cloud.githubusercontent.com/assets/28138187/26217333/a89a71c6-3c0f-11e7-8693-c24810c72efe.png)
![2](https://cloud.githubusercontent.com/assets/28138187/26217332/a8918656-3c0f-11e7-95e6-7d4d2a03a5dc.png)

**Comment by artbear** [comment]
Спасибо.
Насколько я понимаю, нужно в коде исправить на "ПланВидовРасчета".

**Comment by artbear** [comment]
Выполнено в https://github.com/xDrivenDevelopment/xUnitFor1C/pull/743
