### ISSUE TITLE
Перестали работать тесты в УТ 10.3 

### ISSUE THREAD

**Issue by viskvortsov** [xDrivenDevelopment/xUnitFor1C#706]
Стоит режим совместимости: Версия 8.2.13

```
{ВнешняяОбработка.ЗагрузчикФайла.МодульОбъекта(135,4)}: Процедура или функция с указанным именем не определена (СтрНайти)
			<<?>>СтрНайти(Инфо.ИсходнаяСтрока, "Обработка.ЗаполнитьНаборТестов(ЭтотОбъект, КонтекстЯдра);") > 0

```

Я так понимаю, что этот режим совместимости больше не поддерживается.
Есть ли релиз, который еще будет поддерживать режим совместимости?

**Comment by antowski** [comment]
> Я так понимаю, что этот режим совместимости больше не поддерживается.

Верно. Из README:

> Версии с 4.1.0.0 работают только с платформой 1С версии 8.3.6 и выше в режиме совместимости с 8.3.6 и выше.
> 
> Для использования на платформе 1С 8.2 и 8.3 до 8.3.6 используйте версии 4.0.0.0 и 3.0.0.8

**Comment by antowski** [comment]
Версия 4.0.0.7 - последний релиз для 8.2:
https://github.com/xDrivenDevelopment/xUnitFor1C/releases/tag/4.0.0.7
