### ISSUE TITLE
При запуске тестов из отчета где тесты добавлены в форму УФ происходит ошибка подключения обработки

### ISSUE THREAD

**Issue by ruimage** [xDrivenDevelopment/xUnitFor1C#707]
## Предварительно

Версия продукта - ветка develop, коммит ab0c243d43805e1d5c6399947582d2166677fcbd 
Версия платформы - 8.3.8.1652, управляемое приложение

## Описание

При подключении отчета-теста в xunit выполняется заполнение всех тестов указанных в файле отчета. Верно создаются наборы тестов, сами тесты в дереве.

При попытке запуска выполнения тестов появляется ошибка:

{ВнешняяОбработка.ЗагрузчикФайла.Форма.Форма.Форма(92)}: Ошибка при вызове метода контекста (ПолучитьФорму)
	Контекст = ПолучитьФорму("ВнешняяОбработка." + ФайлОбработки.ИмяБезРасширения + ".Форма", , ЭтаФорма, Новый УникальныйИдентификатор);
по причине:
"Неизвестное имя формы. Имя: "ВнешняяОбработка._ИмяМоейОбработки_.Форма

**Шаги для воспроизведения**

1. Создать отчет с формой "Форма"
2. В форме создать набор тестов + тест
3. Загрузить в обработке xunit файл теста через пункт меню "Загрузить тесты из файлов"
4. Нажать кнопку выполнить все тесты

**Ожидаемое поведение:** [ Что вы хотите получить? ]

Начало тестирования и получение информации об успешности прохождения теста

**Текущее поведение:** [ Что происходит в действительности? ]

появляется ошибка 

Неизвестное имя формы. Имя: "ВнешняяОбработка._ИмяМоейОбработки_.Форма

![default](https://cloud.githubusercontent.com/assets/15168946/26583647/1ef142c8-4557-11e7-98c3-4ec3e2dbded3.jpg)

**Comment by agaltsoff** [comment]
Саму обработку бы посмотреть. 
Может там какой-то инициализации в форме не хватает?
Я создавал обработку через преобразование журнала пользователя в текст, проблемы с подключением к тестируемому приложению были, но тест по крайней мере запускался.
