### ISSUE TITLE
Плагин СериализаторMXL. Добавить кнопку для загрузки данных

### ISSUE THREAD

**Issue by 1cgh** [xDrivenDevelopment/xUnitFor1C#709]
### Предварительно

* [x] Вы используете [последнюю версию продукта](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop)  ?
* [x] Вы проверили [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8) ?

## Описание

Требуется загрузка данных интерактивно из макета в некоторых случаях:
разбор полетов вручную по тестам - нужно создать контекст теста и проверить вручную;
повторная выгрузка данных макета с уточнением - текущий макет данных избыточен, можно загрузить в пустую базу и, наложив дополнительные условия отбора, повторно сформировать новый макет.

**Ожидаемое поведение:** Кнопка "Загрузить данные из макета" в форме обработки плагина с действием, аналогичным действию кнопки "Протестировать загрузку макета", но без отката транзакции. Т.е. загруженные данные остаются в системе.

**Текущее поведение:** Нет отдельной кнопки для загрузки данных макета.

## Также приветствуется описание в формате Gherkin

```Gherkin
Функционал Загрузка данных макета интерактивно
   Как разработчик
   Я хочу иметь возможность загрузить данные макета интерактивно

Контекст
  Дано версия продукта последняя
  И версия платформы 1С любая из поддерживаемых

Сценарий Загрузка данных из макета
  Допустим я открыл форму обработки плагина
  И в обработке в макете присутствуют данные для загрузки
  Когда я нажимаю кнопку "Загрузить данные из макета"
  Тогда данные макета загружаются в систему

```

**Comment by ivanov660** [comment]
Мы реализовали подобный функционал (см. issue 732) (загрузку макета в базу без отката). 
Дополнительно добавили команду загрузить макет из файла, что также повышает удобство использования данного плагина.

Как мы используем подобный функционал: пользователь сообщает об ошибке или аналитик/тестировщик воспроизводит ошибочную ситуацию в базе для тестов и далее заливает этот пример в базу разработчика. В результате имеем существенный профит в разборе и передачи ошибок.

**Comment by artbear** [comment]
Реализовано в #741
