### ISSUE TITLE
Упростить инструкцию по скачиванию

### ISSUE THREAD

**Issue by yarsergo** [xDrivenDevelopment/xUnitFor1C#712]
### Предварительно
* [ ] Я использую (клон) этого репозитария... загружен 13.06.2017

## Описание
Добрый день, у меня может совсем "тупой" вопрос... но всё же

Почему просто нельзя пользоваться ОДНОЙ обработкой xddTestRunner.epf
или только 1 конфигурацией 1С xUnitFor1C\Tests\TestConfig.cf?

зачем этот "лес" файлов ? зачем мне весь git - репозитарий?
я же ничего править в нём не буду...
и вот вся эта лишняя информация - отпугивает 1С-программистов
(так как наверное я не один такой "тупой")

Пожелание:
напишите в инструкции лучше как пользоваться через Git GUI (он идёт автоматом в составе установки Git), как там подключать разные репозитарии...

тогда всего 2 инструмента надо будет - git и выкачать Ваш репозитарий

3 вопрос уж сразу... чем ZIP-архив плох зачем вообще git ставить?
тогда вообще ставить ничего не надо... а достаточно скачать архив... это ВСЕМ понятно

**Шаги для воспроизведения**
1. скачать ZIP-файл 
2. использовать только ОДИН файл конфигурации 1С:  xUnitFor1C\Tests\TestConfig.cf

если так нельзя, сделайте  "облечгенный" вариант - 1 инструмент Git  и ВСЁ!
1. напишите подробную инструкцию как ставить git - обязательно в CMD (а не Git-Bash!) например,
2. как пользоваться Git GUI (который идёт автоматом в составе установки Git), 
3. как там подключать разные репозитарии... и качать ваши...

**Ожидаемое поведение:** [ Что вы хотите получить? ]
Использовать ОДИН ФАЙЛ конфигурации 1С:  xUnitFor1C\Tests\TestConfig.cf
Чтобы 
не надо было качать git
не надо было устанавливать git (с несколькими шагами... про которые никто не говорит!), 
не надо делать регистрацию в Atlassian - создавать новый аккаунт
не надо ставить SourceTree - (тормозная и глючная очень!)
не надо клонировать репозитарии OneScript
не надо клонировать ВЕСЬ репозитарии xUnitFor1C
не надо их устанавливать в CMD

**Текущее поведение:** [ Что происходит в действительности? ]
Для использования 1 файла - надо делать 7 шагов? 
почему не достаточно просто скачать ZIP-архив или только 1 файл?

Сейчас надо:
надо качать git
надо устанавливать git (с несколькими шагами... про которые никто не говорит!), 
надо делать регистрацию в Atlassian - создавать новый аккаунт
надо ставить SourceTree - (тормозная и глючная очень!)
надо клонировать репозитарии OneScript
надо клонировать ВЕСЬ репозитарии xUnitFor1C
надо их устанавливать в CMD

**Укажите:**
* клон от 13.06.2017
*  у меня лично платформа "старая" 1С 8.2.19 
*  обычное приложение, толстый клиент, УТ 10.3

**Прикладывайте скриншоты**

## Также приветствуется описание в формате Gherkin

```Gherkin
Функционал Получить простой и быстрый способ использования файлов
   Как Программист 1С
   Я хочу скачать ТОЛЬКО ОДИН  ZIP-файл 
  И          использовать только 1 файл  в этом архиве    xUnitFor1C\Tests\TestConfig.cf
И не делать лишних действий, которые мне лично не нужны, такие как нижеперечисленнные
  И          не качать git 
  И          не регистрироваться на Atlassian
  И          не ставить SourceTree
  И          не регистрироваться в GitHub
  И          не создавать свой репозиторий
  И          не клонировать OneScript репозиторий
  И          не клонировать xUnitFor1C репозиторий
  И          не писать в cmd  какbе-то-там    xxx -- install

Контекст
  Дано последняя xUnitFor1C от 13.06.2017 
 И версия платформы 1С - 8.2.19
 и СПАСИБО, что для 8.2 Вы тоже поддерживаете и всё работает

Сценарий   Идеальное скачивание для Программиста 1С
  Допустим В Инструкции написано, что ДОСТАТОЧНО 
                      скачать только ОДИН файл ZIP-архива
  Когда я нажму скачать ZIP-архив 
    И        укажу <Папку на своём компьютере>
  Тогда  Я сразу получу ОДИН файл архива <Папку на своём компьютере> 

```

**Comment by artbear** [comment]
>Почему просто нельзя пользоваться ОДНОЙ обработкой xddTestRunner.epf
или только 1 конфигурацией 1С xUnitFor1C\Tests\TestConfig.cf?

Кратко отвечу:
+ `xUnitFor1C\Tests\TestConfig.cf` - это тестовая конфигурация самого фреймворка
+ Нельзя скачать ОДНУ обработку `xddTestRunner.epf`, т.к. продукт - это фреймворк и состоит из нескольких связанных модулей/обработок.
+ мы не сторонники все возможности и весь код запихивать в один огромный модуль одной обработки, ибо это зло, причины всем известны.
+ можно скачать один зип-архив и использовать только внутри 1С, но тогда не будет всяких полезных плюшек в виде автоматических CI/CD (гуглите, если не знаете), автосборок на билд-серверах, удобных отчетов и многое другое.

**Comment by artbear** [comment]
>напишите в инструкции лучше как пользоваться через Git GUI (он идёт автоматом в составе установки Git), как там подключать разные репозитарии...

Есть куча разных бесплатных вебинаров, где разными способами рассказывается, как работать с Гит и его клиентами, в т.ч. SourceTree
Есть платные вебинары SilverBulleters, где рассказывается это и еще многое-многое другое.

Есть платные имплементации SilverBulleters, на которых наши тренеры рассказывают, показывают, и на ваших примерах/серверах/базах демонстрируют/настраивают много чего.

Дублировать обучающую информацию, как работать с Гитом еще где-то, нет смысла.

**Comment by artbear** [comment]
>СПАСИБО, что для 8.2 Вы тоже поддерживаете и всё работает

Огорчу немного :)

Из офиц.доки 
>Версии с 4.1.0.0 работают только с платформой 1С версии 8.3.6 и выше в режиме совместимости с 8.3.6 и выше.

>Для использования на платформе 1С 8.2 и 8.3 до 8.3.6 используйте версии 4.0.0.0 и 3.0.0.8

старые версии уже не дорабатываются, если только энтузиаст какой перенесет код, благо, это не слишком сложно.

**Comment by artbear** [comment]
>Сейчас надо:
надо качать git
надо устанавливать git (с несколькими шагами... про которые никто не говорит!),
надо делать регистрацию в Atlassian - создавать новый аккаунт
надо ставить SourceTree - (тормозная и глючная очень!)
надо клонировать репозитарии OneScript
надо клонировать ВЕСЬ репозитарии xUnitFor1C
надо их устанавливать в CMD

для работы именно `xUnitFor1C` нужно только 
+ или скачать зип-архив продукта и развернуть его 
+ или склонировать репо, если есть гит.

ничего остального из списка выше делать не нужно :)

**Comment by artbear** [comment]
>Есть платные имплементации SilverBulleters, на которых наши тренеры рассказывают, показывают, и на ваших примерах/серверах/базах демонстрируют/настраивают много чего.

И даже в режиме парного программирования работают с каждым участником тренинга индивидуально :)

**Comment by yarsergo** [comment]
спасибо за подробное разъяснение... 
как Вы сами пишете:
"для работы именно xUnitFor1C нужно только
... скачать зип-архив продукта и развернуть его"
это я и хотел услышать!

т.е. всё-таки Достаточно... скачать ТОЛЬКО архив
а вовсе нет прямой необходимости делать что-то ещё...

вот акцент на этом Достаточно...  хотелось бы как раз сделать... 

Спасибо за эту разработку... тестирование реально нужно и под 8.2
тем более что тестирование появилось в платформе 8.3.9
а в 8.2 уже не появится никогда... и Ваша разработка ОЧЕНЬ нужна!
ну...  то что дальше развивать её не будете... под 8.2 наверное не так страшно
платформу 8.2 тоже больше 1С "не развивает"... ставим костыли как можем...
кто-то до сих пор на 7.7 сидит - вот их жаль... 

 всякие там дополнительные "плюшки" мне лично не нужны... пока
а то ещё советуют обязательно питон и jenkins ставить... cucumber-ы всякие
а мозг и так взрывается от обилия новых терминов...   :)

**Comment by artbear** [comment]
ОФФ. питон уже не обязателен, onescript (язык 1С) рулит.
jenkins также пригодится, CI построить.

cucumber для 1С не нужен.
BDD - для 1С есть vanessa-behavior
для onescript есть 1bdd
