### ISSUE TITLE
Дымовые тесты. Требуется возможность выбора файла настроек исключений

### ISSUE THREAD

**Issue by realMaxA** [xDrivenDevelopment/xUnitFor1C#715]
### Предварительно

* [x] Вы используете [последнюю версию продукта]
* [x] Вы проверили [Известные проблемы при тестировании]

## Описание

На данный момент для версии 4.1.Х.Х, чтобы добавить формы в исключения дымовых тестов рекомендуется создать файл настройки исключений "smoke.json"
 (https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop/Tests/Smoke#Исключения-для-версии-41ХХ-и-выше).

Теоретически один и тот же инструмент может использоваться для тестирования разных конфигураций с разными списками исключений тестируемых форм. В этом случае требуется возможность выбора файла настроек исключений.

По отношению к инструменту, файл настроек исключений может находиться в любом месте файловой системы, предположительно в одном из каталогов репозитария тестируемого продукта, поэтому, возможно, имеет смысл задавать путь к файлу исключений в командной строке запуска тестов.

**Comment by artbear** [comment]
Подобная фича уже реализована.
Посмотри https://github.com/xDrivenDevelopment/xUnitFor1C/issues/697
изучи чек-лист ишуза

**Comment by artbear** [comment]
реализация выполнена не до конца, что видно по чек-листу (не все флаги отмечены)
но уже вполне можно юзать в бою.
