### ISSUE TITLE
Поддержка инфраструктуры для автоматизированного тестирования

### ISSUE THREAD

**Issue by VladFrost** [xDrivenDevelopment/xUnitFor1C#727]
## Описание

Запускать клиент тестирования для каждого теста слишком долго.
Если случайно в момент начала прогона тестов запущен клиент тестирования в другой базе, менеджер тестирования подключится к этому тесту, и тесты будут выполнены не для той базы, в которой требуется выполнить тестирование. 
Нужно уметь передать параметры (имя пользователя, пароль, порт) для одного или нескольких клиентов тестирования, которые среда xUnitFor1C запустит перед прогоном пакета, а после окончания работы закроет только те клиенты тестирования, которые были запущены (определит их по номеру порта).

**Comment by artbear** [comment]
Выполнено в #728
