### ISSUE TITLE
СериализаторMXL ошибка при работе с ПланомВидовРасчета

### ISSUE THREAD

**Issue by ramzesvvsu** [xDrivenDevelopment/xUnitFor1C#729]
### Предварительно

* [  Да] Вы используете [последнюю версию продукта](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop)  ?
* [ Да] Вы проверили [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8) ?

## Описание

[ Вставьте описание бага или проблемы ]

**Шаги для воспроизведения**

1. [С помощью обработки СериализаторMXL делаю выгрузку документа содержащего ссылку на план видов расчета ]
2. [ С помощью обработки СериализаторMXL нажимаю кнопку "Протестировать загрузку макета ]
3. [ Ловим ошибку что объект не найден]

Исправление ошибки - 
Вместо строки
	ИначеЕсли ПротоОбъект.Тип = ВернутьЗначениеСоответствия("ПланВидовРасчетов") ТогдаТогда
		ОбъектСсылка = СоздатьОбъект_ПланВидовРасчетов(ПротоДанные,ПротоОбъект);

Строку

	ИначеЕсли ПротоОбъект.Тип = ВернутьЗначениеСоответствия("ПланВидовРасчета") Или ПротоОбъект.Тип = ВернутьЗначениеСоответствия("ПланВидовРасчетов") Тогда
		ОбъектСсылка = СоздатьОбъект_ПланВидовРасчетов(ПротоДанные,ПротоОбъект);

**Ожидаемое поведение:** [ Что вы хотите получить? ]
Загрузку данных без ошибок
**Текущее поведение:** [ Что происходит в действительности? ]
Выходит ошибка 
**Укажите:**
* [ версию продукта 4.1.0.4]
* [ версию платформы 1С 8.3.10.2299]
* [ параметры запуска
  * обычное/управляемое приложение, тонкий/толстый клиент и т.п. ]

**Прикладывайте скриншоты**
![image](https://user-images.githubusercontent.com/21278865/29425911-9a9c0ace-838d-11e7-935d-148d5e5033c3.png)

**Comment by ramzesvvsu** [comment]
Пока решил временно проблему вручную изменив в макете ПланВидовРасчета на ПланВидовРасчетов
Значит возможно ошибка в формировании макета

**Comment by isolarisi** [comment]
Видимо в названии ошибка ПланВидовХарактеристик = ПланВидовРасчета?

**Comment by ramzesvvsu** [comment]
Спасибо большое, исправил топик.

**Comment by yadimetrio** [comment]
Дублирует https://github.com/xDrivenDevelopment/xUnitFor1C/issues/705 ?

**Comment by artbear** [comment]
Да, есть дублирование.
Предложение для исправления из текущего ишуза мне кажется верным.

@yadimetrio Можешь вставить данное исправление в код Сериализатора для ВР и проверить загрузку/выгрузку?
у меня просто нету планов видов расчетов, да и я с ними очень давно не работал.
Не знаю, как будет правильно :(

@yadimetrio Поможешь?

**Comment by artbear** [comment]
Выполнено в https://github.com/xDrivenDevelopment/xUnitFor1C/pull/743
