### ISSUE TITLE
Ошибки открытия формы обработки xddTestRunner.epf в типовой конфигурации ЗУП

### ISSUE THREAD

**Issue by isolarisi** [xDrivenDevelopment/xUnitFor1C#730]
## Описание

Ошибки открытия формы обработки xddTestRunner.epf в типовой конфигурации ЗУП:

**Шаги для воспроизведения**

1. Открыть типовую конфигурацию ЗУП 2.5.116.1
2. Запустить обработку xddTestRunner.epf 

**Ожидаемое поведение:** Откроется форма обработки

**Текущее поведение:** Открывается окно с ошибками:
 {ВнешняяОбработка.ГенераторОтчетаAllureXML.МодульОбъекта(181,7)}: Процедура или функция с указанным именем не определена (СтрНайти)
	Если <<?>>СтрНайти(Файл.Имя, "-testsuite") = 0 Тогда
{ВнешняяОбработка.ГенераторОтчетаAllureXML.МодульОбъекта(182,15)}: Процедура или функция с указанным именем не определена (СтрШаблон)
		Сообщение = <<?>>СтрШаблон("%1
{ВнешняяОбработка.ГенераторОтчетаAllureXML.МодульОбъекта(188,15)}: Процедура или функция с указанным именем не определена (СтрШаблон)
		Сообщение = <<?>>СтрШаблон("%1

**Укажите:**
* ЗУП 2.5.116.1 (доработанная)
* 8.3.8.2027 (Запускается в режиме совместимости Версия 8.2.13 - ошибка в этом)
* обычное приложение

Для себя поправил, где сваливалось: переделал СтрНайти на Найти и СтрШаблон на конкатенацию строк.

**Comment by nixel2007** [comment]
Из README:
> Версии с 4.1.0.0 работают только с платформой 1С версии 8.3.6 и выше в режиме совместимости с 8.3.6 и выше.
