### ISSUE TITLE
Не запускается xddTestRunner внешкой в УФ

### ISSUE THREAD

**Issue by ImHunter** [xDrivenDevelopment/xUnitFor1C#739]
### Предварительно

* [v ] Вы используете [последнюю версию продукта](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop)  ?
* [v ] Вы проверили [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8) ?

## Описание

Происходит ошибка при открытии xddTestRunner внешкой в УФ (8.3.7.2008).
При авто-загрузке плагина ПостроительДереваТестов выходит ошибка, говорящая об отсутствии экспортного метода формы Инициализация:

xddTestRunner.Формы.УправляемаяФорма:
```
&НаКлиенте
Функция Плагин(Знач Идентификатор) Экспорт
	
	ОбъектПлагин = Неопределено;
        [пропущено]			
			Попытка
				ОбъектПлагин.Инициализация(ЭтаФорма); // ошибка здесь
			Исключение
				Инфо = ИнформацияОбОшибке();
				Если Инфо.Описание = "Метод объекта не обнаружен (Инициализация)" И
```

> {Форма.УправляемаяФорма.Форма(286)}: Метод объекта не обнаружен (Инициализация)
> 				ОбъектПлагин.Инициализация(ЭтаФорма);

**Шаги для воспроизведения**

1. Запустить 1С в режиме Предприятие, УФ
2. Открыть внешку xddTestRunner

**Ожидаемое поведение:** Хех, чтобы открылось...

**Текущее поведение:** Не открывается

**Укажите:**
* [ версию продукта ]
* 8.3.7.2008
* тонкий клиент, режим совместимости: Версия 8.3.6

**Comment by nixel2007** [comment]
Вы скачали репозиторий целиком?

**Comment by ImHunter** [comment]
Да... Пробовал и master, и develop.

**Comment by ImHunter** [comment]
Уважаемые разработчики! Скажите чего-нить по предмету задачи...
Или тестировать лучше в ОФ?

**Comment by asfursov** [comment]
Та же проблема в УФ

**Comment by artbear** [comment]
@ImHunter @asfursov Опишите свои действия.
+ Скачали полный архив репо? Какой именно скачали?
+ развернули его в пустую папку, верно?
+ открыли 1С в режиме УФ тонкий клиент?
+ далее открыли файл xddTestRunner.epf из папки выше?
+ и ошибка сразу вылетает?

Попробуйте аккуратно пройтись по шагам с самого начала.

**Comment by ImHunter** [comment]
Скачал master, развернул в пустую папку, открыл в УФ (ТК), открыл xddTestRunner.epf. И получил все ту же ошибку...

**Comment by artbear** [comment]
Могу вечером, после работы, подключиться удаленно к Вам и посмотреть в реале, что происходит не так. Если возможно удаленное подключение, конечно.

У меня время московское.

**Comment by ImHunter** [comment]
Настрою дома тестовую площадку и покажу через скайп (на работе он запрещен). Или через ТимВ лучше? Показать уже только на след неделе получится.

**Comment by artbear** [comment]
Можно и через скайп.
ТимВ хорош тем, что я могу с твоего разрешения быстро сам что-то проверить/исправить.
через скайп дольше получится

**Comment by ImHunter** [comment]
Ок, подготовлюсь - отпишусь.

**Comment by ImHunter** [comment]
На пустой тестовой БД - в УФ открылось нормально. Буду пока смотреть, что в рабочей БД такого влияет на не-запуск.

**Comment by ImHunter** [comment]
Похоже, что влияет клиент-сервер. Вот код:
xddTestRunner.УправляемаяФорма
```
&НаКлиенте
Функция Плагин(Знач Идентификатор) Экспорт
................
Исключение
	Инфо = ИнформацияОбОшибке();
	Если Инфо.Описание = "Метод объекта не обнаружен (Инициализация)" И
		СтрНайти(Инфо.ИсходнаяСтрока, "ОбъектПлагин.Инициализация(ЭтаФорма);") > 0 И
                // Различие здесь!
		СтрНайти(Инфо.ИмяМодуля, "xddTestRunner.Форма.УправляемаяФорма.Форма") > 0 
		Тогда
		Иначе
			ВызватьИсключение;
		КонецЕсли;
КонецПопытки;
```
В файловой версии Инфо.ИмяМодуля = "ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма" - как и задумано.
А в клиент-сервере Инфо.ИмяМодуля = "Форма.УправляемаяФорма.Форма" - без ВнешняяОбработка.xddTestRunner. 

К удаленным тестам таки готовиться? Или этого пока достаточно?

**Comment by artbear** [comment]
Попробуй заменить строку
`СтрНайти(Инфо.ИмяМодуля, "xddTestRunner.Форма.УправляемаяФорма.Форма") > 0 `
на `СтрНайти(Инфо.ИмяМодуля, "Форма.УправляемаяФорма.Форма") > 0 `

и проверь поведение на своей клиент-сервер базе.

Я пока проверить на клиент-сервер не могу.
Жду результатов.

**Comment by ImHunter** [comment]
В таком виде, ожидаемо, работает. И в файловой версии, и в клиент-сервере.
Может для надежности изменить имя формы на более уникальное?

**Comment by artbear** [comment]
Этого исправления достаточно.
Верхняя проверка и так отсечет практически все что нужно
```bsl
Если Инфо.Описание = "Метод объекта не обнаружен (Инициализация)" И
		СтрНайти(Инфо.ИсходнаяСтрока, "ОбъектПлагин.Инициализация(ЭтаФорма);") > 0 И
```
