### ISSUE TITLE
Перевести на исходники

### ISSUE THREAD

**Issue by pumbaEO** [xDrivenDevelopment/xUnitFor1C#746]

**Comment by pumbaEO** [comment]
https://github.com/pumbaEO/xUnitFor1Csrc/tree/develop

**Comment by artbear** [comment]
@pumbaEO По указанной ссылке актуальная версия?

**Comment by pumbaEO** [comment]
https://github.com/pumbaEO/xUnitFor1Csrc/commits/develop да, последний коммит из develop

**Comment by artbear** [comment]
Спасибо.
Прикольно, нужно посмотреть.
У меня раньше были попытки перейти на твою более раннюю версию в декабре 2016
даже 3 ветки до сих пор остались.
+ feature/config-sources-1
+ feature/config-sources-long
+ feature/config-sources-old

**Comment by pumbaEO** [comment]
Сделал по аналогии с vanessa, только надо реализовать tasks/xunit.os для запуска локального тестирования.

**Comment by artbear** [comment]
Работа через исходники реализована в рамках проекта ADD

**Comment by artbear** [comment]
Выполнено в ADD
