### ISSUE TITLE
Падает тест `ТестДолжен_СоздатьСчет()` СериализатораMXL

### ISSUE THREAD

**Issue by kuntashov** [xDrivenDevelopment/xUnitFor1C#747]
Использую develop-ветку

## Описание

Падает тест `ТестДолжен_СоздатьСчет()` СериализатораMXL

**Шаги для воспроизведения**

Выполняю тесты из папки Tests/Plugins

**Укажите:**
* xUnitFor1C develop (последняя)
* 1С 8.3.10.2580,  Управляемое приложение

Текст исключения: 

```
{ВнешняяОбработка.СериализаторMXL.МодульОбъекта(1076)}: ПланСчетов.ПланСчетов1 не удалось создать новый элемент.
{ВнешняяОбработка.СериализаторMXL.МодульОбъекта(1073)}: Метод объекта не обнаружен (СоздатьЭлемент)
				ВызватьИсключение "ПланСчетов."+ПротоОбъект.Вид+" не удалось создать новый элемент."+Символы.ПС+Ошибка;

```

**Comment by artbear** [comment]
Такой баг уже зарегистрирован https://github.com/xDrivenDevelopment/xUnitFor1C/issues/708
там даже код исправления есть.
только самого исправления никто не сделал :(

**Comment by kuntashov** [comment]
Ок, эту закрою как дубль тогда.
