### ISSUE TITLE
Реализовать или кратко документировать отладку тестов

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/xUnitFor1C#748]
- [ ] Документировать
  - [ ] для файлового варианта простейший вариант

    - [ ] @artbear 
включить отладчик в Конфигураторе, далее сначала нужно открыть форму плагина, далее открыть форму хддТестРаннер
все, можно поставить точку останова в форме плагина и запускать тесты
должно работать, связка-то часто происходит по имени обработки из Конфигуратора.
Так что открывайте файл плагина сначала, а потом отладка.
при изменении кода плагина все по новой - закрываем хддТестРаннер, переоткрываем форму плагина и т.п.
ну и при изменении кода надежнее перегрузить 1С, потом открыть форму плагина и т.п.

- [ ] Добавить проверку в коде - для файлового варианта других проверок не нужно вообще, достаточно варианта выше!

- [ ] Вот пример от @VladFrost , демонстрирующий обход всех форм, и вызов метода только у той, у которой данный метод существует. Исключений не бросается: https://gist.github.com/VladFrost/f4128a6d3937f38265871d673299ab7b

- [ ] Использовать вариант отладки плагинов от @pumbaEO 
https://gitter.im/xDrivenDevelopment/xUnitFor1C?at=59e9ebdad6c36fca31762b2c
 ```bsl
&НаКлиенте
Процедура ПодключитьВнешниеОбработкиДляОтладки() 
	Перем МассивФорм;
	МассивФорм = Новый Массив;
	ФормаVanessa = Неопределено;
	
	Окна = ПолучитьОкна();
	Для каждого Окн Из Окна Цикл
		Если ТипЗнч(Окн) = Тип("ОкноКлиентскогоПриложения") Тогда
			Если Найти(НРег(Строка(Окн.Заголовок)), "тест_")>0 ИЛИ 
				Найти(НРег(Строка(Окн.Заголовок)), "test_")>0 Тогда
				
				МассивФорм.Добавить(Окн.ПолучитьСодержимое());
				
			КонецЕсли;
		КонецЕсли;
		
	КонецЦикла;
	
	Если МассивФорм.Количество() > 0 Тогда
		
		Для каждого Форма Из МассивФорм Цикл
			Попытка
				ДобавитьВнешнийСписокПроцедур(Форма.ПолучитьСписокТестов(ЭтаФорма), Форма.УникальныйИдентификатор, Форма);
				Сообщить("Подключили для отладки форма " + Форма.Заголовок);
			Исключение
				Сообщить("Не удалось подключить форма " + Форма.Заголовок + " по причине:" + ОписаниеОшибки());
			    //ОписаниеОшибки()
			КонецПопытки; 
		КонецЦикла; 
	КонецЕсли;
	
КонецПроцедуры
```
или 
https://github.com/silverbulleters/vanessa-behavior2/commit/17c95b84943e9481d9b912e66095a61a02d03d15

- [ ] Использовать спец.шаблон для отладки
  - [ ] `Добавить шаблон с возможностью отладки теста`  #733

  - [ ] или аналогичная схема
 @VladFrost окт. 18 15:34
Мои пять копеек про отладку.
Если тесту нужна сложная отладка, я делаю его автономным: добавлю ему форму и интерфейс, чтобы дергать тесты.
И модуле этой формы примерно такой код:
```bsl
&НаКлиенте
Перем КонтекстЯдра;
&НаКлиенте
Перем Утверждения;

&НаСервере
Процедура ПриСозданииНаСервере(Отказ, СтандартнаяОбработка)
    ВнешниеОбработки.Создать("C:\xUnitFor1C\xddTestRunner.epf", Ложь); // Магический путь. Некрасиво, но позволяет пробиться к отладчику.
КонецПроцедуры

&НаКлиенте
Процедура ПриОткрытии(Отказ)
    Инициализация(ОткрытьФорму("ВнешняяОбработка.xddTestRunner.Форма"));
    ЗаполнитьСписокТестовДляИнтерактивнойОтладки();
КонецПроцедуры
```
Соответственно, открываю обработку с этим тестом непосредственно, а не через xddTestRunner, и отлаживаю.
https://gitter.im/xDrivenDevelopment/xUnitFor1C?at=59e74a5432e080696ef61680

- [ ] Разные способы

    - [ ] @JohnyDeath окт. 18 18:16
Ещё вариант отладки - это поставить вызов исключения в самом начале. Запустить. Перейти из предприятия в конфигурационных по ошибке. Всё. Можно ставить точки останова, не забыв убрать исключение 
https://gitter.im/xDrivenDevelopment/xUnitFor1C?at=59e7705c01110b7231d019af

    - [ ] @pumbaEO окт. 18 15:50
ясно придется решать самому. Простой сценарий, xdd стартует, проходится по открытым окнам, если есть окно с магическим названием типа префика "pluginXDD_" тогда считаем что это уже подключенные плагин и не делаем его подключение из файловой системы, а сразу сохраняем форму как контекст плагина.
Тогда сначала открываем плагин, потом xdd и у оп, отладка работает. 
Я так в ванеесе делаю 
https://gitter.im/xDrivenDevelopment/xUnitFor1C?at=59e74e23614889d475cd78d5

  - [ ] @artbear окт. 18 15:56
да там все проще - если форма уже открыта, ее всегда можно получить через
ПолучитьФорму (ВнешняяОбработка.<имя обработки>.Форма.<имя формы>)
или
ПолучитьФорму (ВнешняяОбработка.<имя обработки>.<имя стандартной формы>)
т.е. окна даже перебирать не нужно, просто идем по списку файлов плагинов, подразумевая, что имя плагина (в Конфигураторе) совпадает с именем файла плагина
т.е. сначала пытаемся ПолучитьФорму плагина, если не нашли, подключаем файл.
вроде бы должно работать. 
https://gitter.im/xDrivenDevelopment/xUnitFor1C?at=59e74f935c40c1ba79b71af4

  - [ ] @artbear самый простой вариант - отлаживать в толстом клиенте на ОФ, вообще нет проблем

**Comment by agaltsoff** [comment]
Как вариант, можно попробовать использовать [отладку внешних обработок из Инструментов разработчика](http://devtool1c.ucoz.ru/index/otladka_vneshnikh_obrabotok_bsp/0-50).

- Интегрировать в тестовую конфигурацию Инструменты разработчика
- Интегрировать в тестовую конфигурацию Дополнительные отчёты и обработки из БСП
- Дать возможность загружать плагины и тесты из Дополнительных отчётов и обработок

И тогда, возможно, сработает эта чёрная магия отладки внешних обработок ИР.

**Comment by codenull** [comment]
Здравствуйте.
Прошу извинить, если вопрос задаю не в той ветке. Пришлось разбираться с отладкой теста, в котором много однотипных проверок на ЭтоНеопределено(). Одна из этих проверок падает, а какая - непонятно. Фреймворк возвращает ошибку вида:
`{ВнешняяОбработка.УтвержденияBDD.МодульОбъекта(286)}: [Failed] Ожидали, что проверяемое значение () НЕ является НЕОПРЕДЕЛЕНО.	ВызватьИсключение Префикс + " " + СообщениеОшибки;`
Существует какой-либо иной способ, кроме отладки, для точного определения строки вызвавшей падение теста?

**Comment by nixel2007** [comment]
@codenull передавайте в метод Что() вторым параметром строковое описание, что вы проверяете.
`Ожидаем.Что(2+2, "дважды два четыре").Равно(4);`

**Comment by artbear** [comment]
Реализовано в ADD.
Читайте [п.4 FAQ ADD](https://github.com/silverbulleters/add/blob/master/F.A.Q.MD)
