### ISSUE TITLE
Ошибка при загрузке сгенерированного макета если в данных есть группа плана видов характеристик

### ISSUE THREAD

**Issue by Andrewww123** [xDrivenDevelopment/xUnitFor1C#750]
## Описание

[ Если в сгенерированном макете присутствует группа плана видов характеристик, имеющего табличную часть, то при загрузке получаем следующую ошибку:  
{ВнешняяОбработка.СериализаторMXL.МодульОбъекта(1004)}: Ошибка при вызове метода контекста (Очистить)
				Объект[мдТабЧасть.Имя].Очистить();
по причине:
Объект недоступен для изменения.]

**Шаги для воспроизведения**

1. Сгенерировать макет, содержащий группу плана видов характеристик, имеющего табличную часть.
2. Нажать "Протестировать загрузку макета".

**Укажите:**
* [ СериализаторMXL 4.2.0.0]
* [ 8.3.10.2466 ]
* [  обычное приложение, толстый клиент]
```

**Comment by artbear** [comment]
Выполнено в ADD
