### ISSUE TITLE
СериализаторMXL, возможность сохранять установленные отборы

### ISSUE THREAD

**Issue by Andrewww123** [xDrivenDevelopment/xUnitFor1C#752]
## Описание

В обработке "СериализаторMXL" очень не хватает возможности сохранить настроенные отборы. Если обработка была закрыта и в существующий макет нужно добавить объект, то нужно заново настроить все отборы.

**Ожидаемое поведение:** 
Возможность сохранять настройки отбора объектов в файл.

**Текущее поведение:** 
Данной возможности нет.

**Укажите:**
* [ 4.2.0.0 ]
* [ 8.3.10.2466 ]
* [ обычное приложение, толстый клиент ]
```

**Comment by artbear** [comment]
В 4.2.0.2 (пока в ветке девелоп) данная возможность уже реализована.
Забирайте оттуда
