### ISSUE TITLE
Вызов утверждений на серевере

### ISSUE THREAD

**Issue by ebugusey** [xDrivenDevelopment/xUnitFor1C#786]
### Предварительно

* [ ] Вы используете [последнюю версию продукта](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop)  ?
* [x] Вы проверили [Известные проблемы при тестировании](https://github.com/xDrivenDevelopment/xUnitFor1C/wiki/%D0%98%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8) ?

## Описание

Наше решение сделано в виде внешней обработки для управляемого приложения. При этом проверять возвращаемые значения мы можем только на сервере, так как работаем с SOAP сервисом и проверям объекты XDTO.

Встала проблема с передачей контекста ядра на сервер, потому что не хочется писать свой велосипед для проверки значений.

**Укажите:**
* версия xUnit -- 4.2.0.0
* версия платформы -- 8.3.10.2650
* параметры запуска
  * управляемое приложение, тонкий клиент.

Это на самом деле запрос помощи, может есть какой-то мануал как это делать и я его просто не нашел. Но я искал!

**Comment by nixel2007** [comment]
Вы можете использовать мой порт ассертов в виде цф - https://github.com/nixel2007/asserts_cf при желании к Ожидаем аналогично добавляется "Утверждения". Если не хочется мержить в основную конфу, то можно переупаковать в расширение.

**Comment by artbear** [comment]
Все же просто.
Практически любой плагин можно подключать на сервере
```bsl
ЗапросыИзБД = ВнешниеОбработки.Создать("ЗапросыИзБД");
ЗапросыИзБД.ПолучитьКоличествоЭлементовСправочникаПоОтбору(...);
```

**Comment by artbear** [comment]
Документировал в FAQ add

**Comment by artbear** [comment]
Цитата:
1. Как вызвать код плагина на сервере при запуске в управляемой форме?

* Все просто.
* Практически любой плагин можно подключать на сервере
* Например:

```bsl
	ЗапросыИзБД = ВнешниеОбработки.Создать("ЗапросыИзБД");
	ЗапросыИзБД.ПолучитьКоличествоЭлементовСправочникаПоОтбору(...);

	Ожидаем = ВнешниеОбработки.Создать("УтвержденияBDD");
	Ожидаем.Что(Значение, "Должно быть равно 5, а это не так!").
		Равно(5);
```
