### ISSUE TITLE
Документация в виде сайта

### ISSUE THREAD

**Issue by skyksandr** [xDrivenDevelopment/xUnitFor1C#787]
Всем привет. 
Два вопроса:
1. Интересно ли будет мэйнтейнерам и сообществу автогенерируемый сайт с документацией? В очередной раз использовал проект и столкнулся с тем, что приходилось неоднократно смотреть код для того, чтобы понять как с этим работать.
2. Какой статус у проекта? Проект скорее жив или проект скорее завершен, заморожен и т.д.? Спрашиваю, так как последний коммит от 28 января, т.е. 9 месяцев назад.

**Comment by artbear** [comment]
Сейчас проект xUnitFor1C никто не развивает.

А вообще проект переживает очередное перерождение в проекте-наследнике https://github.com/silverbulleters/add

посмотрите хотя бы описание релизов https://github.com/silverbulleters/add/releases

там и дымовые, и плагины, и документация и сам фреймворк тестирования сильно доработан.

и проект активно развивается.

**Comment by artbear** [comment]
Ну и сайт с документацией. конечно, будет очень полезен!

**Comment by artbear** [comment]
и контрибьюторы довольно активно работают в https://github.com/silverbulleters/add

**Comment by artbear** [comment]
старые тесты от xUnitFor1C прекрасно работают в Vanessa.ADD, полная совместимость.

**Comment by skyksandr** [comment]
@artbear Спасибо. Не знал про `Add`. Уже смотрю.
