### ISSUE TITLE
Дымовые тесты по метаданным

### ISSUE THREAD

**Issue by ImHunter** [xDrivenDevelopment/xUnitFor1C#788]
Хочу написать несколько дымовых тестов.
Вроде как, напрашивается новый плагин. Типа ИтераторМетаданных.
Товарищи xDD Instruments for 1C Community, как вы смотрите на появление такого плагина?
Ну или могу без плагина, свое локальное решение сделать.

**Comment by 1cgh** [comment]
Какое назначение плагина?

**Comment by ImHunter** [comment]
Не, похоже, не получается... Коллбэки не удается сделать.
Смысл задумывался примерно следующий.
Создаем плагин. Опционально заполняем допустимые/запрещенные типы или коллекции метаданных.
Выполняем метод Перечислить(). В этот метод как-то бы передать процедуру-событие. И эта процедура-событие заполняла бы список тестов.
Тесты могут быть разные. Например, что у всех записываемых типов есть хотя бы одна роль на Чтение. Или чтобы Синонимы не повторялись. Или Режим блокировки данных - в нужном значении.

**Comment by ImHunter** [comment]
Хотяяя... Можно ведь сделать прим такое:
`ИтераторМетаданных = КонтекстЯдра.Плагин("ИтераторМетаданных");
ИтераторМетаданных.Перечислить(ЭтотОбъект, "ПриСледКоллекции", "ПриСледующемТипе")`

**Comment by artbear** [comment]
@ImHunter Все равно пока что непонятно назначение плагина.

Приведи пример использовании у конечных пользователей 
и пример задания такой функциональности через плагин.

ЗЫ и почему ишуз создан здесь, ведь xUnitFor1C не развивается сейчас, все развитие ведется в наследнике https://github.com/silverbulleters/add/issues
Там уже под 30 плагинов :)

**Comment by ImHunter** [comment]
Пока вот код процедуры плагина:
` Процедура Перечислить(Источник, ПриСледующемОбъектеМетаданных = Неопределено, ПриСледующемТипеМетаданных = Неопределено) Экспорт
	
	Дерево = ДеревоМетаданных();
	
	Для Каждого ТекСтрокаТипа Из Дерево.Строки Цикл 
		ВыполнитьПроцедуруСобытия(Источник, ПриСледующемТипеМетаданных, ТекСтрокаТипа.ОбъектМетаданных);
		Для Каждого ДочерняяСтрока Из ТекСтрокаТипа.Строки Цикл 
			ВыполнитьПроцедуруСобытия(Источник, ПриСледующемОбъектеМетаданных, ТекСтрокаТипа.ОбъектМетаданных);
		КонецЦикла;
	КонецЦикла;
	
КонецПроцедуры`
До реализации теста - чуть позже доберусь.

**Comment by artbear** [comment]
>Все равно пока что непонятно назначение плагина.

>Приведи пример использовании у конечных пользователей
и пример задания такой функциональности через плагин.

@ImHunter И все равно указанные вопросы не прояснились :(

**Comment by ImHunter** [comment]
В общем, пишу дымовые тесты для забывчивых.
Скоро у нас в разработке будет новая самописка. Напишу несколько дымовых тестов, чтобы мы (разработчики) не забывали, например, сразу выставлять права на чтение объектов.
В первом дымовом тесте будет проверяться, что для справ, доков и регистров будет хоть какая-то роль на Чтение, отличная от ролей с администраторскими привилегиями.
Будет еще аналогичный тест - будет проверяться Режим установки блокировки данных. По тесту, будет требоваться установка в значение Управляемый.

**Comment by ImHunter** [comment]
Тест и плагин написаны. В принципе, все работает, как задумано.
Выложить куда-то в виде PR? Или в виде куска кода запостить куда-то?
Если вам не интересно, то сразу на Инфостарт выложу.

**Comment by artbear** [comment]
Интересно.

@ImHunter Предлагаю добавить PR в https://github.com/silverbulleters/add/issues

> Напоминаю - ведь xUnitFor1C не развивается сейчас, все развитие ведется в наследнике https://github.com/silverbulleters/add/issues
Там уже под 30 плагинов :)

**Comment by ImHunter** [comment]
Принято

**Comment by ImHunter** [comment]
Эммм... В ADD докидываются ведь только исходники?

**Comment by ImHunter** [comment]
> Эммм... В ADD докидываются ведь только исходники?

Прочитал про CONTRIBUTING. Попробую.

**Comment by artbear** [comment]
Буду ждать

**Comment by ImHunter** [comment]
Тесты для самого плагина - писать?

**Comment by artbear** [comment]
Было бы круто.
Их можно сделать как в формате tdd (кодом), так и в формате bdd - фичи на геркине
